const $ = (id) => document.getElementById(id);
let selectedStudy=null,currentStep=0,formData={},lastResult=null;
const yes=v=>Number(v)===1;
function factorElevacion(d){const suficiente=(d.nc>0&&d.elevadores>=d.nc/8)||(d.nc>0&&d.camillasRegulables>=d.nc/8&&yes(d.camillaConAyuda))||yes(d.camas3Nodos100);const adecuado=d.st>0&&d.lta/d.st>=.9;return{suficiente,adecuado,fs:suficiente&&adecuado?.5:(!suficiente&&!adecuado?4:2)};}
function factorAyudas(d){const suficiente=(yes(d.sabanaOTabla)&&Number(d.otrasAyudas)>=2)||(yes(d.sabanaOTabla)&&yes(d.camas3Nodos100));const adecuado=d.sp>0&&d.lpa/d.sp>=.9;return{suficiente,adecuado,fa:suficiente&&adecuado?.5:1};}
function factorSillas(d){const na=Number(d.nc||0)+Number(d.pc||0),suficiente=Number(d.sillas||0)>=na*.5,p=Number(d.pmsr||0);let fc=p<=1.33?(suficiente?.75:1):p<=2.66?(suficiente?1.12:1.5):(suficiente?1.5:2);return{suficiente,pmsr:p,fc};}
function factorAmbiente(d){const pmamb=Number(d.pmb||0)+Number(d.pmwc||0)+Number(d.pmh||0);return{pmamb,famb:pmamb<=5.8?.75:pmamb<=11.6?1.25:1.5};}
function factorFormacion(d){const curso=yes(d.cursoAdecuado),c75=yes(d.cobertura75),reciente=yes(d.antiguedad2),c50=yes(d.cobertura50),info90=yes(d.informacion90),eficacia=yes(d.eficacia);if(curso&&c75&&reciente)return{ff:.75,motivo:'Curso adecuado, ≥75% y menos de 2 años.'};if(curso&&c75&&eficacia)return{ff:.75,motivo:'Curso adecuado para ≥75% con eficacia verificada.'};if((curso&&c50)||(info90&&eficacia))return{ff:1,motivo:'Condición intermedia de formación.'};return{ff:2,motivo:'No cumple las condiciones mínimas.'};}
function calcularHospitalizacion(d){if(d.op<=0)throw Error('OP debe ser mayor que 0.');if(d.nc<0||d.pc<0)throw Error('NC y PC no pueden ser negativos.');if(d.lta>d.st||d.lpa>d.sp)throw Error('Los levantamientos con ayuda no pueden superar los correspondientes totales.');const fs=factorElevacion(d),fa=factorAyudas(d),fc=factorSillas(d),famb=factorAmbiente(d),form=factorFormacion(d),terminoNC=d.nc/d.op*fs.fs,terminoPC=d.pc/d.op*fa.fa,mapo=(terminoNC+terminoPC)*fc.fc*famb.famb*form.ff,nivel=mapo===0?'Ausente':mapo<=1.5?'Irrelevante':mapo<=5?'Medio':'Alto';return{mapo,nivel,fs:fs.fs,fa:fa.fa,fc:fc.fc,famb:famb.famb,ff:form.ff,terminoNC,terminoPC,detalle:{fs,fa,fc,famb,form}};}
function renderStep(){const study=MAPO_STUDIES[selectedStudy],step=study.steps[currentStep];$('studyTitle').textContent=study.title;$('studyDescription').textContent=`${study.description} · Paso ${currentStep+1} de ${study.steps.length}: ${step.title}`;const h=step.helpKey?MAPO_HELP[step.helpKey]:null,help=h?`<button type="button" class="help-trigger" data-help="${step.helpKey}" aria-label="${h.title}" title="Mostrar ayuda">?</button><div class="help-popover" id="help_${step.helpKey}" hidden><strong>${h.title}</strong>${h.html}</div>`:'';$('formContainer').innerHTML=`<div class="step-title-row"><h3>${step.title}</h3>${help}</div><div class="grid">${step.fields.map(([id,label,type])=>`<label>${label}<input id="field_${id}" type="${type}" min="0" step="any" value="${formData[id]??''}"></label>`).join('')}</div>`;document.querySelectorAll('.help-trigger').forEach(b=>b.onclick=()=>{const box=$(`help_${b.dataset.help}`),hidden=box.hidden;document.querySelectorAll('.help-popover').forEach(p=>p.hidden=true);box.hidden=!hidden;});$('previousStep').hidden=currentStep===0;$('nextStep').hidden=currentStep===study.steps.length-1;$('calculate').hidden=currentStep!==study.steps.length-1;$('progressBar').style.width=`${(currentStep+1)/study.steps.length*100}%`;}
function saveStep(){for(const[id,label,type]of MAPO_STUDIES[selectedStudy].steps[currentStep].fields){const input=$(`field_${id}`),raw=input.value.trim();if(type==='number'&&raw!==''&&Number(raw)<0)throw Error(`${label} no puede ser negativo.`);formData[id]=type==='number'&&raw!==''?Number(raw):raw;}}
function selectStudy(key){selectedStudy=key;currentStep=0;formData={};$('studySelection').hidden=true;$('studyPanel').hidden=false;$('result').hidden=true;renderStep();}document.querySelectorAll('.study-option').forEach(b=>b.onclick=()=>selectStudy(b.dataset.study));$('changeStudy').onclick=()=>{selectedStudy=null;$('studyPanel').hidden=true;$('result').hidden=true;$('studySelection').hidden=false;};$('nextStep').onclick=()=>{try{saveStep();currentStep++;renderStep();$('error').hidden=true;}catch(e){$('error').textContent=e.message;$('error').hidden=false;}};$('previousStep').onclick=()=>{saveStep();currentStep--;renderStep();};$('calculate').onclick=()=>{try{saveStep();if(selectedStudy==='hospitalizacion')lastResult=calcularHospitalizacion(formData);else{if(!formData.op||formData.op<=0)throw Error('OP debe ser mayor que 0.');const fs=Number(formData.fs||1),fa=Number(formData.fa||1),fc=Number(formData.fc||1),famb=Number(formData.famb||1),ff=Number(formData.ff||1),mapo=((Number(formData.nc||0)/formData.op)*fs+(Number(formData.pc||0)/formData.op)*fa)*fc*famb*ff;lastResult={mapo,nivel:mapo===0?'Ausente':mapo<=1.5?'Irrelevante':mapo<=5?'Medio':'Alto',fs,fa,fc,famb,ff};}$('mapoValue').textContent=`MAPO = ${lastResult.mapo.toFixed(2)}`;$('classification').textContent=`Nivel de exposición: ${lastResult.nivel}`;$('breakdown').innerHTML=`<p>FS = ${lastResult.fs}</p><p>FA = ${lastResult.fa}</p><p>FC = ${lastResult.fc}</p><p>Famb = ${lastResult.famb}</p><p>FF = ${lastResult.ff}</p><p><strong>Fórmula:</strong> [(NC/OP × FS) + (PC/OP × FA)] × FC × Famb × FF</p>`;$('result').hidden=false;$('error').hidden=true;}catch(e){$('error').textContent=e.message;$('error').hidden=false;$('result').hidden=true;}};$('generateReport').onclick=()=>alert('La generación del informe Word se conectará al modelo del estudio seleccionado. Los modelos serán administrados mediante SharePoint.');
