/* Hospitalización UI v2: registros agrupados y cálculos coherentes. */
(function(){
  const baseRender=window.renderStep, baseSave=window.saveStep;
  const keyFor=k=>k==='chair'?'wheelchairTypes':k==='bath'?'bathTypes':k==='wc'?'wcTypes':'roomTypes';
  const fields={
    chair:[['brakes','Frenos con funcionamiento inadecuado',1],['arms','Reposabrazos no extraíbles o abatibles',1],['back','Respaldo inadecuado: H > 90 cm o inclinación > 100°',1],['width','Anchura máxima > 70 cm',1]],
    bath:[['space','Espacio insuficiente para el uso de ayudas',2],['door','Anchura de la puerta < 85 cm',1],['obstacles','Presencia de obstáculos fijos',1]],
    wc:[['space','Espacio insuficiente para el uso de silla de ruedas',2],['height','Altura del WC inadecuada',1],['bar','Ausencia/inadecuación de barra lateral',1],['door','Anchura de la puerta < 85 cm',1],['lateral','Espacio lateral WC-pared < 80 cm',1]],
    room:[['between','Espacio cama-cama/cama-pared < 90 cm',2],['foot','Espacio libre desde pies de cama < 120 cm',2],['bedSection','Cama inadecuada: requiere levantamiento manual de una sección',1],['underbed','Espacio cama-suelo < 15 cm',2],['chairHeight','Altura del asiento del sillón < 50 cm',0.5]]
  };
  const help={chair:'Estas son las cuatro características que suman puntos a PMSR. Reposapiés y mantenimiento son datos descriptivos y no suman puntos.',bath:'Estas tres características son las que puntúan en PMB. La apertura de puerta, ducha y bañera se registran como datos descriptivos.',wc:'Estas cinco características suman puntos a PMWC. La apertura de puerta hacia dentro es descriptiva.',room:'Estas cinco características suman puntos a PMH. Obstáculos, altura fija de cama, barras, anchura de puerta y ruedas son datos descriptivos.'};
  function items(k){return formData[keyFor(k)]||[];}
  function score(x,k){return fields[k].reduce((s,f)=>s+(x[f[0]]===true?f[2]:0),0);}
  function mean(k){const xs=items(k);let n=0,t=0;xs.forEach(x=>{const u=Number(x.units||0);if(u>0){n+=u;t+=u*score(x,k);}});return n?t/n:null;}
  function yes(k,i,f,v){const name=`${k}_${i}_${f[0]}`;return `<div class="choice-row"><label class="choice"><input type="radio" name="${name}" data-rk="${k}" data-ri="${i}" data-rf="${f[0]}" value="yes" ${v===true?'checked':''}> Sí</label><label class="choice"><input type="radio" name="${name}" data-rk="${k}" data-ri="${i}" data-rf="${f[0]}" value="no" ${v===false?'checked':''}> No</label><button type="button" class="help-trigger" data-rhelp="${k}_${f[0]}">?</button></div>`;}
  function renderRegistry(k){const xs=items(k);const title={chair:'Sillas de ruedas (FC)',bath:'Baños para higiene (PMB)',wc:'Baños con WC (PMWC)',room:'Habitaciones (PMH)'}[k];return `<div class="step-title-row"><h3>${title}</h3><button type="button" class="help-trigger" data-rgeneral="${k}">?</button><div class="help-popover" id="rg_${k}" hidden>${help[k]}</div></div><p><strong>Puede agrupar unidades exactamente iguales.</strong> Si una unidad tiene alguna característica diferente, cree otro tipo. Máximo 50 tipos.</p><div class="registry-list">${xs.map((x,i)=>`<div class="registry-card"><div class="registry-card-head"><h4>Tipo ${i+1}</h4><button type="button" class="help-trigger" data-rtype="${k}_${i}">?</button></div><div class="grid"><label>Descripción<input type="text" data-rk="${k}" data-ri="${i}" data-rf="description" value="${x.description||''}"></label><label>Número de unidades<input type="number" min="1" step="1" data-rk="${k}" data-ri="${i}" data-rf="units" value="${x.units??''}"></label></div><div class="registry-questions">${fields[k].map(f=>`<div><strong>${f[1]}</strong>${yes(k,i,f,x[f[0]])}</div>`).join('')}</div><div class="grid">${k==='chair'?`<label>Reposapiés no extraíble/no reclinable<input type="text" data-rk="chair" data-ri="${i}" data-rf="footrest" value="${x.footrest||''}"></label><label>Mal estado de mantenimiento<input type="text" data-rk="chair" data-ri="${i}" data-rf="maintenance" value="${x.maintenance||''}"></label>`:''}${k==='bath'?`<label>Apertura hacia dentro<input type="text" data-rk="bath" data-ri="${i}" data-rf="doorInward" value="${x.doorInward||''}"></label><label>Ducha/bañera fija<input type="text" data-rk="bath" data-ri="${i}" data-rf="fixtures" value="${x.fixtures||''}"></label>`:''}${k==='wc'?`<label>Apertura hacia dentro<input type="text" data-rk="wc" data-ri="${i}" data-rf="doorInward" value="${x.doorInward||''}"></label>`:''}${k==='room'?`<label>Observaciones/obstáculos<input type="text" data-rk="room" data-ri="${i}" data-rf="observations" value="${x.observations||''}"></label><label>Altura cama fija (cm)<input type="number" min="0" step="0.1" data-rk="room" data-ri="${i}" data-rf="bedHeight" value="${x.bedHeight??''}"></label><label>Barras laterales inadecuadas<input type="text" data-rk="room" data-ri="${i}" data-rf="sideRails" value="${x.sideRails||''}"></label><label>Anchura puerta (cm)<input type="number" min="0" step="0.1" data-rk="room" data-ri="${i}" data-rf="doorWidth" value="${x.doorWidth??''}"></label><label>Cama sin ruedas<input type="text" data-rk="room" data-ri="${i}" data-rf="noWheels" value="${x.noWheels||''}"></label>`:''}</div><div class="question-help-popover" id="rt_${k}_${i}" hidden>Solo agrupe aquí unidades que sean exactamente iguales respecto de las condiciones evaluadas.</div></div>`).join('')}</div><button type="button" class="secondary" data-radd="${k}" ${xs.length>=50?'disabled':''}>+ Añadir tipo</button><div class="schedule-preview" id="rs_${k}"></div>`;}
  function read(k){const key=keyFor(k),xs=(formData[key]||[]).slice();document.querySelectorAll(`[data-rk="${k}"]`).forEach(el=>{const i=+el.dataset.ri,f=el.dataset.rf;xs[i]??={};if(el.type==='radio'){if(el.checked)xs[i][f]=el.value==='yes';}else xs[i][f]=el.type==='number'?(el.value===''?'':+el.value):el.value;});formData[key]=xs;const e=$(`rs_${k}`),m=mean(k),n=xs.reduce((s,x)=>s+Number(x.units||0),0);if(e)e.innerHTML=`<strong>${k==='chair'?'TSR / PMSR':k==='bath'?'PMB':k==='wc'?'PMWC':'PMH'}</strong>: ${m===null?'Pendiente':m.toFixed(2)} · Unidades: ${n}`;}
  function bind(k){document.querySelectorAll(`[data-rk="${k}"]`).forEach(el=>el.addEventListener(el.type==='radio'?'change':'input',()=>read(k)));document.querySelectorAll('[data-radd]').forEach(b=>b.onclick=()=>{const key=keyFor(k);formData[key]=formData[key]||[];if(formData[key].length<50){formData[key].push({});window.renderStep();}});document.querySelectorAll('[data-rgeneral]').forEach(b=>b.onclick=()=>{const box=$(`rg_${b.dataset.rgeneral}`);const was=box.hidden;document.querySelectorAll('.help-popover,.question-help-popover').forEach(x=>x.hidden=true);box.hidden=!was;});document.querySelectorAll('[data-rtype]').forEach(b=>b.onclick=()=>{const box=$(`rt_${b.dataset.rtype.replace('_','_')}`);if(!box)return;const was=box.hidden;document.querySelectorAll('.help-popover,.question-help-popover').forEach(x=>x.hidden=true);box.hidden=!was;});document.querySelectorAll('[data-rhelp]').forEach(b=>b.onclick=()=>{const [kk,f]=b.dataset.rhelp.split('_');const box=$(`rg_${kk}`);const was=box.hidden;document.querySelectorAll('.help-popover,.question-help-popover').forEach(x=>x.hidden=true);box.hidden=!was;});}
  function wrappedRender(){const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(step.questionGroup==='fc'){document.getElementById('formContainer').innerHTML=renderRegistry('chair');bind('chair');read('chair');return;}if(step.title==='Factor ambiente — baños'){document.getElementById('formContainer').innerHTML=`<div class="section-heading"><h3>Baños para higiene</h3></div>${renderRegistry('bath')}<hr>${renderRegistry('wc')}`;bind('bath');bind('wc');read('bath');read('wc');return;}if(step.custom==='pmh'){document.getElementById('formContainer').innerHTML=renderRegistry('room');bind('room');read('room');return;}baseRender();}
  window.renderStep=wrappedRender;
  window.saveStep=function(){const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(step.questionGroup==='fc'){read('chair');return;}if(step.title==='Factor ambiente — baños'){read('bath');read('wc');return;}if(step.custom==='pmh'){read('room');return;}baseSave();};
  window.calculateHospitalizacionFactors=function(d){if(window.getHospitalizacionPatientCounts)Object.assign(d,window.getHospitalizacionPatientCounts(d));const official=new Set(MAPO_TASKS.map(x=>x.id));let st=0,lta=0,sp=0,lpa=0;Object.entries(d.tasks||{}).forEach(([id,sh])=>{if(!official.has(id))return;Object.values(sh||{}).forEach(r=>{st+=+(r.tm||0)+ +(r.ta||0);lta+=+(r.ta||0);sp+=+(r.pm||0)+ +(r.pa||0);lpa+=+(r.pa||0);});});const taskTotals={st,lta,sp,lpa,stp:st+sp,pLTA:st?100*lta/st:0,pLPA:sp?100*lpa/sp:0};const fsS=Number(d.nc||0)===0||(yn(d.fs_elevadores)||yn(d.fs_camillas)||yn(d.fs_camas3));const fsA=st>0&&lta/st>=.9;const fs=fsS&&fsA?.5:(!fsS&&!fsA?4:2);const faS=(yn(d.fa_sabana)&&yn(d.fa_dos))||(yn(d.fa_sabana)&&yn(d.fa_camas3));const faA=sp>0&&lpa/sp>=.9;const fa=faS&&faA?.5:1;const pmsr=mean('chair'),tsr=(d.wheelchairTypes||[]).reduce((s,x)=>s+Number(x.units||0),0),na=Number(d.na||0),fcS=tsr>=na*.5;let fc=null;if(pmsr!==null)fc=pmsr<=1.33?(fcS?.75:1):pmsr<=2.66?(fcS?1.12:1.5):(fcS?1.5:2);const pmb=mean('bath'),pmwc=mean('wc'),pmh=mean('room'),pmamb=[pmb,pmwc,pmh].every(x=>x!==null)?pmb+pmwc+pmh:null,famb=pmamb===null?null:(pmamb<=5.8?.75:pmamb<=11.6?1.25:1.5);const course=yn(d.ff_curso),cov=Number(d.ff_cobertura||0),recent=yn(d.ff_antiguedad),eff=yn(d.ff_eficacia),info=yn(d.ff_informacion),ff=(course&&cov>=75&&(recent||eff))?.75:(course&&cov>=50&&cov<75&&recent)||info?1:2;return{fs,fa,fc,famb,ff,taskTotals,details:{fsSufficient:fsS,fsAdequate:fsA,faSufficient:faS,faAdequate:faA,pmsr,tsr,pmamb,pmB:pmb,pmWC:pmwc,pmH:pmh,fcSufficient:fcS}};};
})();
