/* MAPO Analyzer — XLSX local, sin dependencias externas.
   Genera y lee los archivos XLSX creados por MAPO Analyzer sin Internet.
   No sustituye ni modifica ningún cálculo MAPO. */
(function(){
  const te=new TextEncoder(),td=new TextDecoder();
  const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
  function crc32(bytes){let c=0xffffffff;for(let i=0;i<bytes.length;i++){c^=bytes[i];for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
  function u16(a,n){return a[n]|a[n+1]<<8;}
  function u32(a,n){return (a[n]|a[n+1]<<8|a[n+2]<<16|a[n+3]<<24)>>>0;}
  function put16(a,n,v){a[n]=v&255;a[n+1]=(v>>>8)&255;}
  function put32(a,n,v){a[n]=v&255;a[n+1]=(v>>>8)&255;a[n+2]=(v>>>16)&255;a[n+3]=(v>>>24)&255;}
  function zip(files){
    const locals=[],centrals=[];let offset=0;
    for(const f of files){const name=te.encode(f.name),data=typeof f.data==='string'?te.encode(f.data):f.data,crc=crc32(data);const h=new Uint8Array(30+name.length);put32(h,0,0x04034b50);put16(h,4,20);put16(h,6,0);put16(h,8,0);put16(h,10,0);put16(h,12,0);put32(h,14,crc);put32(h,18,data.length);put32(h,22,data.length);put16(h,26,name.length);put16(h,28,0);h.set(name,30);locals.push(h,data);const c=new Uint8Array(46+name.length);put32(c,0,0x02014b50);put16(c,4,20);put16(c,6,20);put16(c,8,0);put16(c,10,0);put16(c,12,0);put16(c,14,0);put32(c,16,crc);put32(c,20,data.length);put32(c,24,data.length);put16(c,28,name.length);put16(c,30,0);put16(c,32,0);put16(c,34,0);put16(c,36,0);put32(c,38,0);put32(c,42,offset);c.set(name,46);centrals.push(c);offset+=h.length+data.length;}
    const centralSize=centrals.reduce((n,x)=>n+x.length,0),end=new Uint8Array(22);put32(end,0,0x06054b50);put16(end,4,0);put16(end,6,0);put16(end,8,files.length);put16(end,10,files.length);put32(end,12,centralSize);put32(end,16,offset);put16(end,20,0);return concat([...locals,...centrals,end]);
  }
  function concat(parts){let n=parts.reduce((s,p)=>s+p.length,0),o=0,r=new Uint8Array(n);for(const p of parts){r.set(p,o);o+=p.length;}return r;}
  function cell(v,r,c){const ref=String.fromCharCode(65+c)+r; if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t>${esc(v)}</t></is></c>`;}
  function sheetXml(rows){let xml='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>';rows.forEach((row,i)=>{xml+=`<row r="${i+1}">`;row.forEach((v,j)=>{if(v!==''&&v!==null&&v!==undefined)xml+=cell(v,i+1,j);});xml+='</row>';});return xml+'</sheetData></worksheet>';}
  function workbookXml(names,hidden){let s=names.map((n,i)=>`<sheet name="${esc(n)}" sheetId="${i+1}" r:id="rId${i+1}"${hidden.includes(i)?' state="hidden"':''}/>`).join('');return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${s}</sheets></workbook>`;}
  function rels(n){let a=[];for(let i=1;i<=n;i++)a.push(`<Relationship Id="rId${i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i}.xml"/>`);return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${a.join('')}</Relationships>`;}
  function contentTypes(n){let a=[];for(let i=1;i<=n;i++)a.push(`<Override PartName="/xl/worksheets/sheet${i}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`);return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${a.join('')}<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`;}
  const rootRels='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>';
  const styles='<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="Calibri"/></font></fonts><fills count="2"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf/></cellStyleXfs><cellXfs count="1"><xf/></cellXfs></styleSheet>';
  function write(wb){const files=[{name:'[Content_Types].xml',data:contentTypes(wb.SheetNames.length)},{name:'_rels/.rels',data:rootRels},{name:'xl/workbook.xml',data:workbookXml(wb.SheetNames,wb.Hidden||[])},{name:'xl/_rels/workbook.xml.rels',data:rels(wb.SheetNames.length)},{name:'xl/styles.xml',data:styles}];wb.SheetNames.forEach((n,i)=>files.push({name:`xl/worksheets/sheet${i+1}.xml`,data:sheetXml(wb.Sheets[n]._rows||[])}));return zip(files).buffer;}
  function readZip(buf){const a=new Uint8Array(buf),files={};let eocd=-1;for(let i=a.length-22;i>=0;i--){if(u32(a,i)===0x06054b50){eocd=i;break;}}if(eocd<0)throw Error('El archivo no es un XLSX válido.');const count=u16(a,eocd+10),cd=u32(a,eocd+16);let p=cd;const promises=[];for(let i=0;i<count;i++){if(u32(a,p)!==0x02014b50)break;const method=u16(a,p+10),cs=u32(a,p+20),us=u32(a,p+24),nl=u16(a,p+28),el=u16(a,p+30),cl=u16(a,p+32),off=u32(a,p+42);const name=td.decode(a.slice(p+46,p+46+nl));const lp=off;const ln=u16(a,lp+26),le=u16(a,lp+28),start=lp+30+ln+le;const raw=a.slice(start,start+cs);if(method===0)files[name]=raw;else if(method===8){if(typeof DecompressionStream==='undefined')throw Error('Este navegador no permite leer XLSX comprimidos.');promises.push(new Response(new Blob([raw]).stream().pipeThrough(new DecompressionStream('deflate-raw'))).arrayBuffer().then(x=>files[name]=new Uint8Array(x)));}else throw Error('Método de compresión XLSX no compatible.');p+=46+nl+el+cl;}return Promise.all(promises).then(()=>files);}
  function tag(xml,name){const m=xml.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`));return m?m[1]:'';}
  function attr(s,n){const m=s.match(new RegExp(`${n}="([^"]*)"`));return m?m[1]:'';}
  async function read(buf){const files=await readZip(buf),wb=td.decode(files['xl/workbook.xml']),relsXml=td.decode(files['xl/_rels/workbook.xml.rels']);const relMap={};for(const m of relsXml.matchAll(/<Relationship\b([^>]*)\/>/g))relMap[attr(m[1],'Id')]=attr(m[1],'Target');const names=[],sheets={};for(const m of wb.matchAll(/<sheet\b([^>]*)\/>/g)){const n=attr(m[1],'name'),rid=attr(m[1],'r:id'),target='xl/'+relMap[rid].replace(/^\//,'');names.push(n);sheets[n]=files[target];}const out={SheetNames:names,Sheets:{}};for(const n of names){const xml=td.decode(sheets[n]),rows=[];for(const rm of xml.matchAll(/<row\b[^>]*>([\s\S]*?)<\/row>/g)){const vals=[];for(const cm of rm[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const head=cm[1],body=cm[2],ref=attr(head,'r'),col=ref.replace(/\d/g,'');let idx=0;for(let j=0;j<col.length;j++)idx=idx*26+col.charCodeAt(j)-64;idx--;let v='';if(head.includes('t="inlineStr"'))v=tag(body,'t');else{const x=tag(body,'v');v=x===''?'':Number(x);}vals[idx]=v;}rows.push(vals);}out.Sheets[n]={_rows:rows};}return out;}
  function aoa_to_sheet(rows){return {_rows:rows};}
  function sheet_to_json(ws){return ws._rows||[];}
  window.XLSX={utils:{aoa_to_sheet,sheet_to_json,book_new(){return {SheetNames:[],Sheets:{},Hidden:[]};},book_append_sheet(wb,ws,name){wb.SheetNames.push(name);wb.Sheets[name]=ws;}},write,read};
})();
