/* MAPO Analyzer — tablas para informe Word. Solo presentación; no modifica cálculos. */
(function(){
'use strict';
const $=id=>document.getElementById(id), n=v=>Number(v||0), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yn=v=>v===true?'Sí':v===false?'No':'', pct=v=>n(v).toFixed(1)+'%';
function data(){return typeof window.MAPOReportState==='function'?window.MAPOReportState():{form:{},result:{}};}
function rows(t){return t.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('');}
function table(title,heads,body){return '<div class="report-table-block"><h3>'+esc(title)+'</h3><table class="mapo-report-table"><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';}
const shifts=['Mañana','Tarde','Noche'];
function personnelTable(f){
 const s=f.workerSchedule||{},full=Array.isArray(s.full)?s.full:[],partial=Array.isArray(s.partial)?s.partial:[];
 const get=(a,i)=>a[i]||{};
 const totalFull=full.reduce((z,r)=>z+n(r.people),0);
 const auxEnf=f.auxEnfermeria??f.aux_enfermeria??'',auxGer=f.auxGeriatria??f.aux_geriatria??'',limit=f.personalLimitacionMMP??f.personal_limitacion_mmp??f.limitacionMMP??'';
 let h='<div class="personnel-report"><h3>1. ENTREVISTA</h3><h4>1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP:</h4><p class="report-note"><strong>Número total de personas trabajadoras de planta.</strong></p>';
 h+='<div class="report-table-block"><h4>Personal de planta</h4><table class="mapo-report-table personnel-summary"><thead><tr><th>Concepto</th><th>Valor</th></tr></thead><tbody><tr><th>Número total de personas trabajadoras de planta</th><td>'+esc(totalFull)+'</td></tr><tr><th>Aux. enfermería</th><td>'+esc(auxEnf)+'</td></tr><tr><th>Aux. geriatría</th><td>'+esc(auxGer)+'</td></tr><tr><th>Personal con limitación para MMP</th><td>'+esc(limit)+'</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 h+='<h4>1.1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP DURANTE LOS 3 TURNOS:</h4><p class="report-note"><strong>Número de personas trabajadoras presentes en toda la duración de cada turno.</strong></p>';
 const fullRows=[0,1,2].map(i=>get(full,i));
 let sh='<table class="mapo-report-table personnel-shifts"><thead><tr><th>TURNO</th>'+shifts.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>';
 sh+='<tr><th>Nº de personas trabajadoras/Turno (A)</th>'+fullRows.map(r=>'<td>'+esc(r.people===''?'':n(r.people))+'</td>').join('')+'</tr>';
 sh+='<tr><th>Horario del turno</th>'+fullRows.map(r=>'<td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td>').join('')+'</tr></tbody></table>';
 h+='<div class="report-table-block"><h4>Personal por turnos</h4>'+sh+'<div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 h+='<h4>1.1.2. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP A TIEMPO PARCIAL:</h4><p class="report-note"><strong>Turno y horario de presencia.</strong><br>(En el caso de horarios diferentes por turno se añaden las filas siguientes tantas veces como sea necesario)</p>';
 let ph='<table class="mapo-report-table personnel-partial"><thead><tr><th>TURNO</th>'+shifts.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>';
 let calculated=null;try{calculated=window.WorkersScheduleV3?.calculate?.();}catch(_){calculated=null;}
 const partialRows=calculated?.rows||[];
 ph+='<tr><th>Nº personas trabajadoras tiempo parcial (B)</th>'+[0,1,2].map(i=>'<td>'+esc(get(partial,i).people??0)+'</td>').join('')+'</tr>';
 ph+='<tr><th>Horario de presencia en la sala</th>'+[0,1,2].map(i=>{const r=get(partial,i);return '<td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td>';}).join('')+'</tr>';
 ph+='<tr><th>Fracción de unidad (C) = Horas de presencia en el turno / Horas del turno</th>'+[0,1,2].map(i=>{const b=n(get(partial,i).people);const d=partialRows[i]?.partialPresent;const c=b>0&&Number.isFinite(Number(d))?Number(d)/b:0;return '<td>'+esc(c.toFixed(2))+'</td>';}).join('')+'</tr>';
 ph+='<tr><th>Fracción de unidad por trabajador (D) = C x B</th>'+[0,1,2].map(i=>{const d=partialRows[i]?.partialPresent;return '<td>'+esc(Number.isFinite(Number(d))?Number(d).toFixed(2):'0.00')+'</td>';}).join('')+'</tr>';
 ph+='</tbody></table>';
 h+='<div class="report-table-block"><h4>Personal a tiempo parcial</h4>'+ph+'<div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 let op=calculated&&Number.isFinite(Number(calculated.OP))?Number(calculated.OP):totalFull;
 h+='<div class="report-table-block personnel-op"><table class="mapo-report-table"><tbody><tr><th>Nº TOTAL DE PERSONAS TRABAJADORAS EN 24 HORAS (Op)</th><td>'+esc(op.toFixed(2))+'</td></tr><tr><td colspan="2">Total de personas trabajadoras/turno de todos los turnos (A) + Fracción de unidad por persona trabajadora (D), ponderadas según las horas de presencia y los días trabajados.</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 return h+'</div>';
}
function taskRows(f){const all=[...(window.MAPO_TASKS||[]).map(x=>({...x,source:'MAPO'})),...(window.EXTRA_MAPO_TASKS||[]).map(x=>({...x,source:'Adicional'}))],t=f.tasks||{},out=[];all.forEach(x=>Object.entries(t[x.id]||{}).forEach(([i,r])=>out.push([x.source,x.label,shifts[+i]||'Turno '+(+i+1),n(r.tm),n(r.ta),n(r.pm),n(r.pa)])));(f.customTasks||[]).forEach(x=>out.push(['Personalizada',x.name||'','—',n(x.tm),n(x.ta),n(x.pm),n(x.pa)]));return out;}
function tableOrEmpty(title,heads,body){return table(title,heads,body||'<tr><td colspan="'+heads.length+'">Sin datos registrados</td></tr>');}
function build(key){const {form:f,result:r}=data(),t=r.taskTotals||{};switch(key){
case'general':return table('Datos generales',['Campo','Valor'],rows([['Hospital / empresa',f.empresa||''],['Sala / unidad',f.unidad||''],['Fecha de evaluación',f.fecha||''],['Código de sala',f.codigo||''],['Número de camas',n(f.camas)]]));
case'workers':return personnelTable(f);
case'patients':{const p=f.patientTypes||{};return table('Tipología de pacientes',['Dato','Valor'],rows([['AUTÓNOMOS',n(p.autonomo)],['COLABORADORES',n(p.colaborador)],['NO COLABORADORES',n(p.noColaborador)],['ENCAMADOS',n(p.encamado)],['NC',n(f.nc)],['PC',n(f.pc)],['NA',n(f.na)]]));}
case'mobilizations':return tableOrEmpty('Movilizaciones',['Origen','Tarea','Turno','Total manual','Total con ayuda','Parcial manual','Parcial con ayuda'],rows(taskRows(f)))+table('Totales de movilización',['Indicador','Valor'],rows([['ST',n(t.st)],['LTA',n(t.lta)],['% LTA',pct(t.pLTA)],['SP',n(t.sp)],['LPA',n(t.lpa)],['% LPA',pct(t.pLPA)],['STP',n(t.stp)]]));
case'fs':return table('Factor de elevación (FS)',['Dato','Valor'],rows([['FS calculado',r.fs==null?'':n(r.fs).toFixed(2)],['% LTA',pct(t.pLTA)]]));
case'fa':return table('Factor de ayudas menores (FA)',['Dato','Valor'],rows([['FA calculado',r.fa==null?'':n(r.fa).toFixed(2)],['% LPA',pct(t.pLPA)]]));
case'wheelchairs':{const w=f.wheelchairs||{},entries=w.entries||{},types=[...(window.WHEELCHAIR_PREDEFINED||[]),...(window.WHEELCHAIR_COMMON||[]),...(Array.isArray(w.custom)?w.custom:[])];let body='';types.forEach(x=>{const e=entries[x.id]||{};const score=(e.brakes?0:1)+(e.arms?0:1)+(e.back?0:1)+(e.width?0:1);body+='<tr>'+[x.name||'',e.count??0,yn(e.brakes),yn(e.arms),yn(e.back),yn(e.width),score].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});if(!body)body='<tr><td colspan="7">Sin datos registrados</td></tr>';return table('Sillas de ruedas (FC)',['TIPO DE SILLA','Nº UNIDADES','FRENOS','REPOSABRAZOS','RESPALDO','ANCHURA','PUNTUACIÓN'],body);}
case'bathrooms':{const b=f.bathTypes||[],w=f.wcTypes||[];let bodyB='',bodyW='';b.forEach((x,i)=>{const score=(x.space===true?2:0)+(x.door===true?1:0)+(x.obstacles===true?1:0);bodyB+='<tr>'+[i+1,x.description||'',x.units??'',yn(x.space),yn(x.door),yn(x.obstacles),score].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});w.forEach((x,i)=>{const score=(x.space===true?2:0)+(x.height===true?1:0)+(x.bar===true?1:0)+(x.door===true?1:0)+(x.lateral===true?1:0);bodyW+='<tr>'+[i+1,x.description||'',x.units??'',yn(x.space),yn(x.height),yn(x.bar),yn(x.door),yn(x.lateral),score].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});if(!bodyB)bodyB='<tr><td colspan="7">Sin datos registrados</td></tr>';if(!bodyW)bodyW='<tr><td colspan="9">Sin datos registrados</td></tr>';return table('Baños de higiene',['Nº','DESCRIPCIÓN','UNIDADES','ESPACIO','PUERTA','OBSTÁCULOS','PUNTUACIÓN'],bodyB)+table('Baños WC',['Nº','DESCRIPCIÓN','UNIDADES','ESPACIO','ALTURA','BARRA','PUERTA','ESPACIO LATERAL','PUNTUACIÓN'],bodyW);}
case'rooms':{const a=f.roomTypes||[];let body=a.map((x,i)=>'<tr>'+[i+1,x.description||'',x.units??'',yn(x.between),yn(x.foot),yn(x.bedSection),yn(x.underbed),yn(x.chairHeight)].map(v=>'<td>'+esc(v)+'</td>').join('')).join('');if(!body)body='<tr><td colspan="8">Sin datos registrados</td></tr>';return table('Habitaciones (PMH)',['Nº','DESCRIPCIÓN','UNIDADES','ESPACIO ENTRE CAMA Y PARED','ESPACIO A LOS PIES','SECCIÓN DE CAMA','ESPACIO BAJO CAMA','ALTURA SILLA'],body);}
case'formation':{return table('Formación (FF)',['CURSO TEÓRICO-PRÁCTICO ≥6 h','COBERTURA (%)','ANTIGÜEDAD <2 AÑOS','VERIFICACIÓN DE EFICACIA','INFORMACIÓN / ADIESTRAMIENTO ≥90%'],rows([[yn(f.ff_curso),f.ff_cobertura??'',yn(f.ff_antiguedad),yn(f.ff_eficacia),yn(f.ff_informacion)]]));}
case'factors':return table('Resultado MAPO y factores',['Indicador','Valor'],rows([['MAPO',r.mapo==null?'':n(r.mapo).toFixed(2)],['Nivel de exposición',r.nivel||''],['FS',r.fs==null?'':n(r.fs).toFixed(2)],['FA',r.fa==null?'':n(r.fa).toFixed(2)],['FC',r.fc==null?'Pendiente':n(r.fc).toFixed(2)],['Famb',r.famb==null?'Pendiente':n(r.famb).toFixed(2)],['FF',r.ff==null?'':n(r.ff).toFixed(2)]]));
default:return '<p>Tabla no disponible.</p>';}}
function tableToHtml(tableEl){const clone=tableEl.cloneNode(true);const sourceCells=tableEl.querySelectorAll('th,td'),cloneCells=clone.querySelectorAll('th,td');clone.style.cssText='width:100%;border-collapse:collapse;font-family:Arial,sans-serif;font-size:10pt;color:#000';cloneCells.forEach((c,i)=>{const s=sourceCells[i],cs=getComputedStyle(s);c.style.cssText='font-family:'+cs.fontFamily+';font-size:'+cs.fontSize+';font-weight:'+cs.fontWeight+';color:'+cs.color+';background-color:'+cs.backgroundColor+';border:'+cs.border+';padding:'+cs.padding+';text-align:'+cs.textAlign+';vertical-align:'+cs.verticalAlign+';line-height:'+cs.lineHeight;});return '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="font-family:Arial,sans-serif;font-size:10pt;">'+clone.outerHTML+'</body></html>';}
async function copyTable(btn){const tableEl=btn.closest('.report-table-block')?.querySelector('.mapo-report-table');if(!tableEl)return;const html=tableToHtml(tableEl),text=tableEl.innerText;try{if(navigator.clipboard&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);else throw new Error('clipboard');const old=btn.textContent;btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent=old,1800);}catch(e){const range=document.createRange();range.selectNode(tableEl);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);try{document.execCommand('copy');btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent='Copiar tabla para Word',1800);}finally{sel.removeAllRanges();}}}
function render(){const host=$('reportTables');if(!host)return;const checks=[...document.querySelectorAll('[data-report-table]')].filter(x=>x.checked);host.innerHTML=checks.map(x=>build(x.dataset.reportTable)).join('')||'<p class="report-tables-empty">Seleccione al menos una tabla.</p>';host.querySelectorAll('.copy-report-table').forEach(b=>b.onclick=()=>copyTable(b));}
function init(){const result=$('result');if(!result)return;let section=document.getElementById('reportTablesPanel');if(!section){section=document.createElement('section');section.id='reportTablesPanel';section.className='card';section.hidden=true;section.innerHTML='<div class="section-heading"><div><h2>Tablas para informe Word</h2><p>Seleccione las tablas que desea preparar.</p></div></div><div class="report-table-selectors">'+[['general','Datos generales'],['workers','Personas trabajadoras y horarios'],['patients','Tipología de pacientes'],['mobilizations','Movilizaciones'],['fs','Factor de elevación (FS)'],['fa','Factor de ayudas menores (FA)'],['wheelchairs','Sillas de ruedas (FC)'],['bathrooms','Baños — PMB y PMWC'],['rooms','Habitaciones — PMH'],['formation','Formación (FF)'],['factors','Resultado MAPO y factores']].map(d=>'<label><input type="checkbox" data-report-table="'+d[0]+'"> '+d[1]+'</label>').join('')+'</div><div class="actions"><button type="button" id="generateReportTables">Generar tablas</button><button type="button" id="copyAllReportTables" class="secondary">Copiar todas las tablas</button></div><div id="reportTables"></div>';result.parentNode.insertBefore(section,result.nextSibling);}
const actions=result.querySelector('.actions');if(actions&&!document.getElementById('openReportTables')){const b=document.createElement('button');b.type='button';b.id='openReportTables';b.className='secondary';b.textContent='Crear tablas para informe Word';actions.appendChild(b);b.onclick=()=>{section.hidden=false;section.scrollIntoView({behavior:'smooth'});};}
const generate=$('generateReportTables');if(generate)generate.onclick=render;const all=$('copyAllReportTables');if(all)all.onclick=async()=>{render();const tables=[...document.querySelectorAll('#reportTables .mapo-report-table')];if(!tables.length)return;const html='<!DOCTYPE html><html><body>'+tables.map(t=>tableToHtml(t).replace(/^<!DOCTYPE html><html><head><meta charset="UTF-8"><\/head><body>|<\/body><\/html>$/g,'')).join('<br>')+'</body></html>',text=tables.map(t=>t.innerText).join('\n\n');try{if(navigator.clipboard&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);else throw new Error('clipboard');all.textContent='✓ Tablas copiadas';setTimeout(()=>all.textContent='Copiar todas las tablas',1800);}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();all.textContent='✓ Tablas copiadas';setTimeout(()=>all.textContent='Copiar todas las tablas',1800);}};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.MAPOReportTables={render,build};})();