/* MAPO Analyzer — tablas para informe Word.
   Responsabilidad única: construir/renderizar/copiar las tablas.
   No calcula MAPO ni modifica los datos de evaluación. */
(function(){
'use strict';
const $=id=>document.getElementById(id),n=v=>Number(v||0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yn=v=>v===true?'Sí':v===false?'No':'',pct=v=>n(v).toFixed(1)+'%';
const shifts=['Mañana','Tarde','Noche'];
function data(){return typeof window.MAPOReportState==='function'?window.MAPOReportState():{form:{},result:{}};}
function rows(t){return t.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('');}
function table(title,heads,body){return '<div class="report-table-block"><h3>'+esc(title)+'</h3><table class="mapo-report-table"><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';}
function personnelTable(f){
 const s=f.workerSchedule||{},full=Array.isArray(s.full)?s.full:[],partial=Array.isArray(s.partial)?s.partial:[];const get=(a,i)=>a[i]||{};
 const totalFull=full.reduce((z,r)=>z+n(r.people),0),auxEnf=f.auxEnfermeria??f.aux_enfermeria??'',auxGer=f.auxGeriatria??f.aux_geriatria??'',limit=f.personalLimitacionMMP??f.personal_limitacion_mmp??f.limitacionMMP??'';
 let h='<div class="personnel-report"><h3>1. ENTREVISTA</h3><h4>1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP:</h4><p class="report-note"><strong>Número total de personas trabajadoras de planta.</strong></p>';
 h+='<div class="report-table-block"><h4>Personal de planta</h4><table class="mapo-report-table personnel-summary"><thead><tr><th>Concepto</th><th>Valor</th></tr></thead><tbody><tr><th>Número total de personas trabajadoras de planta</th><td>'+esc(totalFull)+'</td></tr><tr><th>Aux. enfermería</th><td>'+esc(auxEnf)+'</td></tr><tr><th>Aux. geriatría</th><td>'+esc(auxGer)+'</td></tr><tr><th>Personal con limitación para MMP</th><td>'+esc(limit)+'</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 h+='<h4>1.1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP DURANTE LOS 3 TURNOS:</h4><p class="report-note"><strong>Número de personas trabajadoras presentes en toda la duración de cada turno.</strong></p>';
 let sh='<table class="mapo-report-table personnel-shifts"><thead><tr><th>TURNO</th>'+shifts.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody><tr><th>Nº de personas trabajadoras/Turno (A)</th>'+[0,1,2].map(i=>'<td>'+esc(get(full,i).people===''?'':n(get(full,i).people))+'</td>').join('')+'</tr><tr><th>Horario del turno</th>'+[0,1,2].map(i=>{const r=get(full,i);return '<td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td>';}).join('')+'</tr></tbody></table>';
 h+='<div class="report-table-block"><h4>Personal por turnos</h4>'+sh+'<div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 h+='<h4>1.1.2. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP A TIEMPO PARCIAL:</h4><p class="report-note"><strong>Turno y horario de presencia.</strong><br>(En el caso de horarios diferentes por turno se añaden las filas siguientes tantas veces como sea necesario)</p>';
 let ph='<table class="mapo-report-table personnel-partial"><thead><tr><th>TURNO</th>'+shifts.map(x=>'<th>'+x+'</th>').join('')+'</tr></thead><tbody>';
 let calculated=null;try{calculated=window.WorkersScheduleV3?.calculate?.();}catch(_){calculated=null;}const partialRows=calculated?.rows||[];
 ph+='<tr><th>Nº personas trabajadoras tiempo parcial (B)</th>'+[0,1,2].map(i=>'<td>'+esc(get(partial,i).people??0)+'</td>').join('')+'</tr><tr><th>Horario de presencia en la sala</th>'+[0,1,2].map(i=>{const r=get(partial,i);return '<td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td>';}).join('')+'</tr>';
 ph+='<tr><th>Fracción de unidad (C) = Horas de presencia en el turno / Horas del turno</th>'+[0,1,2].map(i=>{const b=n(get(partial,i).people),d=partialRows[i]?.partialPresent,c=b>0&&Number.isFinite(Number(d))?Number(d)/b:0;return '<td>'+esc(c.toFixed(2))+'</td>';}).join('')+'</tr><tr><th>Fracción de unidad por trabajador (D) = C x B</th>'+[0,1,2].map(i=>{const d=partialRows[i]?.partialPresent;return '<td>'+esc(Number.isFinite(Number(d))?Number(d).toFixed(2):'0.00')+'</td>';}).join('')+'</tr></tbody></table>';
 h+='<div class="report-table-block"><h4>Personal a tiempo parcial</h4>'+ph+'<div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 const op=calculated&&Number.isFinite(Number(calculated.OP))?Number(calculated.OP):totalFull;
 return h+'<div class="report-table-block personnel-op"><table class="mapo-report-table"><tbody><tr><th>Nº TOTAL DE PERSONAS TRABAJADORAS EN 24 HORAS (Op)</th><td>'+esc(op.toFixed(2))+'</td></tr><tr><td colspan="2">Total de personas trabajadoras/turno de todos los turnos (A) + Fracción de unidad por persona trabajadora (D), ponderadas según las horas de presencia y los días trabajados.</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div></div>';
}
function mobilizationRows(f){
 const out=[],tasks=f.tasks&&typeof f.tasks==='object'?f.tasks:{},catalog=Array.isArray(window.HOSPITALIZATION_MOBILIZATIONS)?window.HOSPITALIZATION_MOBILIZATIONS:[],catalogById=new Map(catalog.map(x=>[x.id,x]));
 Object.keys(tasks).forEach(id=>{const task=catalogById.get(id)||{id,name:id,source:'MAPO'},turns=tasks[id]&&typeof tasks[id]==='object'?tasks[id]:{};for(let i=0;i<3;i++){const r=turns[i]||{},tm=n(r.tm),ta=n(r.ta),pm=n(r.pm),pa=n(r.pa);if(tm||ta||pm||pa)out.push([task.name||id,shifts[i],tm,ta,pm,pa]);}});
 const legacy=f.mobilizations&&typeof f.mobilizations==='object'?f.mobilizations:null,entries=legacy&&legacy.entries&&typeof legacy.entries==='object'?legacy.entries:{};
 if(Object.keys(tasks).length===0)Object.keys(entries).forEach(id=>{const task=catalogById.get(id)||((legacy.custom||[]).find(x=>x.id===id))||{id,name:id,source:'MAPO'},e=entries[id]||{};for(let i=0;i<3;i++){const tm=n(e.manualTotal?.[i]),ta=n(e.aidedTotal?.[i]),pm=n(e.manualPartial?.[i]),pa=n(e.aidedPartial?.[i]);if(tm||ta||pm||pa)out.push([task.name||id,shifts[i],tm,ta,pm,pa]);}});
 const customs=Array.isArray(f.customTasks)?f.customTasks:[];customs.forEach((x,i)=>{const tm=n(x.tm),ta=n(x.ta),pm=n(x.pm),pa=n(x.pa);if(tm||ta||pm||pa)out.push([x.name||`Movilización personalizada ${i+1}`,'',tm,ta,pm,pa]);});
 const order=new Map(shifts.map((s,i)=>[s,i]));out.sort((a,b)=>(order.get(a[1])??99)-(order.get(b[1])??99)||String(a[0]).localeCompare(String(b[0]),'es',{sensitivity:'base'}));return out;
}
function tableOrEmpty(title,heads,body){return table(title,heads,body||'<tr><td colspan="'+heads.length+'">Sin datos registrados</td></tr>');}
function scoreTotals(xs,fields){let units=0,points=0,byField={};fields.forEach(f=>byField[f[0]]=0);xs.forEach(x=>{const u=n(x.units);if(u<=0)return;units+=u;fields.forEach(f=>{if(x[f[0]]===true)byField[f[0]]+=u*f[2];});points+=u*fields.reduce((s,f)=>s+(x[f[0]]===true?f[2]:0),0);});return {units,points,byField,mean:units?points/units:null};}
function roomTotals(xs){const fields=[['between',2],['foot',2],['bedSection',1],['underbed',2],['chairHeight',.5]];let units=0,points=0,byField={};fields.forEach(f=>byField[f[0]]=0);xs.forEach(x=>{const u=n(x.units);if(u<=0)return;units+=u;fields.forEach(([f,p])=>{if(x[f]===true)byField[f]+=u*p;});points+=u*fields.reduce((s,[f,p])=>s+(x[f]===true?p:0),0);});return {units,points,byField,mean:units?points/units:null};}
function build(key){const {form:f,result:r}=data(),t=r.taskTotals||{};switch(key){
case'general':return table('Datos generales',['Campo','Valor'],rows([['Hospital / empresa',f.empresa||''],['Sala / unidad',f.unidad||''],['Fecha de evaluación',f.fecha||''],['Código de sala',f.codigo||''],['Número de camas',n(f.camas)]]));
case'workers':return personnelTable(f);
case'patients':{const p=f.patientTypes||{};return table('Tipología de pacientes',['Dato','Valor'],rows([['AUTÓNOMOS',n(p.autonomo)],['COLABORADORES',n(p.colaborador)],['NO COLABORADORES',n(p.noColaborador)],['ENCAMADOS',n(p.encamado)],['NC',n(f.nc)],['PC',n(f.pc)],['NA',n(f.na)]]));}
case'mobilizations':return tableOrEmpty('Movilizaciones',['Tarea','Turno','Total manual','Total con ayuda','Parcial manual','Parcial con ayuda'],rows(mobilizationRows(f)))+table('Totales de movilización',['Indicador','Valor'],rows([['ST',n(t.st)],['LTA',n(t.lta)],['% LTA',pct(t.pLTA)],['SP',n(t.sp)],['LPA',n(t.lpa)],['% LPA',pct(t.pLPA)],['STP',n(t.stp)]]));
case'fs':return table('Factor de elevación (FS)',['Dato','Valor'],rows([['Número total de levantamientos (movilizaciones) de pacientes no colaboradores',n(t.lta)],['FS calculado',r.fs==null?'':n(r.fs).toFixed(2)],['% LTA',pct(t.pLTA)]]));
case'fa':return table('Factor de ayudas menores (FA)',['Dato','Valor'],rows([['¿Hay sábana o tabla deslizante disponible?',yn(f.fa_sabana)],['¿Hay además al menos dos de las otras ayudas menores indicadas en la ficha?',yn(f.fa_dos)],['¿Todas las camas de la unidad son regulables en altura y tienen 3 nodos de articulación?',yn(f.fa_camas3)],['Número de levantamientos parciales (movilizaciones parciales) realizados con equipamiento de ayuda',n(t.lpa)],['Número total de levantamientos parciales (movilizaciones parciales) evaluados',n(t.sp)],['FA calculado',r.fa==null?'':n(r.fa).toFixed(2)],['% LPA',pct(t.pLPA)]]));
case'wheelchairs':{const w=f.wheelchairs||{},entries=w.entries||{},types=[...(window.WHEELCHAIR_PREDEFINED||[]),...(window.WHEELCHAIR_COMMON||[]),...(Array.isArray(w.custom)?w.custom:[])];let body='';types.forEach(x=>{const e=entries[x.id]||{};if(Number(e.count||0)<=0)return;const score=(e.brakes?0:1)+(e.arms?0:1)+(e.back?0:1)+(e.width?0:1);body+='<tr>'+[x.name||'',e.count??0,yn(e.brakes),yn(e.arms),yn(e.back),yn(e.width),score].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});if(!body)body='<tr><td colspan="7">Sin datos registrados</td></tr>';return table('Sillas de ruedas (FC)',['TIPO DE SILLA','Nº UNIDADES','FRENOS','REPOSABRAZOS','RESPALDO','ANCHURA','PUNTUACIÓN'],body);}
case'bathrooms':{const b=f.bathTypes||[],w=f.wcTypes||[],bf=[['space','Espacio insuficiente',2],['door','Puerta inadecuada',1],['obstacles','Obstáculos',1]],wf=[['space','Espacio insuficiente',2],['height','Altura inadecuada',1],['bar','Barra inadecuada/ausente',1],['door','Puerta inadecuada',1],['lateral','Espacio lateral insuficiente',1]],bt=scoreTotals(b,bf),wt=scoreTotals(w,wf);let bodyB='',bodyW='';b.forEach((x,i)=>{const partial=bf.reduce((s,z)=>s+(x[z[0]]===true?z[2]:0),0);const weighted=partial*n(x.units);bodyB+='<tr>'+[i+1,x.description||'',x.units??'',yn(x.space),yn(x.door),yn(x.obstacles),partial,weighted].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});w.forEach((x,i)=>{const partial=wf.reduce((s,z)=>s+(x[z[0]]===true?z[2]:0),0);const weighted=partial*n(x.units);bodyW+='<tr>'+[i+1,x.description||'',x.units??'',yn(x.space),yn(x.height),yn(x.bar),yn(x.door),yn(x.lateral),partial,weighted].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});if(!bodyB)bodyB='<tr><td colspan="8">Sin datos registrados</td></tr>';else bodyB+='<tr class="report-total-row"><th colspan="8">TOTAL BAÑOS DE HIGIENE · Nº TOTAL DE UNIDADES: '+esc(bt.units)+'</th></tr><tr class="report-total-row"><th colspan="8">PUNTUACIÓN MEDIA PMB: '+esc(bt.mean===null?'Pendiente':bt.mean.toFixed(2))+'</th></tr>';if(!bodyW)bodyW='<tr><td colspan="10">Sin datos registrados</td></tr>';else bodyW+='<tr class="report-total-row"><th colspan="10">TOTAL BAÑOS WC · Nº TOTAL DE UNIDADES: '+esc(wt.units)+'</th></tr><tr class="report-total-row"><th colspan="10">PUNTUACIÓN MEDIA PMWC: '+esc(wt.mean===null?'Pendiente':wt.mean.toFixed(2))+'</th></tr>';return table('Baños de higiene',['Nº','Descripción del baño','Nº de unidades','¿Espacio suficiente?','¿Puerta adecuada?','¿Existen obstáculos?','Puntuación parcial por unidad','Puntos totales del tipo'],bodyB)+table('Baños WC',['Nº','Descripción del baño','Nº de unidades','¿Espacio suficiente?','¿Altura adecuada?','¿Dispone de barra de apoyo?','¿Puerta adecuada?','¿Espacio lateral suficiente?','Puntuación parcial por unidad','Puntos totales del tipo'],bodyW);}
case'rooms':{const a=f.roomTypes||[],rf=[['between',2],['foot',2],['bedSection',1],['underbed',2],['chairHeight',.5]],rt=roomTotals(a);let body='';a.forEach((x,i)=>{const partial=rf.reduce((s,[f,p])=>s+(x[f]===true?p:0),0),weighted=partial*n(x.units);body+='<tr>'+[i+1,x.description||'',x.units??'',yn(x.between),yn(x.foot),yn(x.bedSection),yn(x.underbed),yn(x.chairHeight),partial,weighted].map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>';});if(!body)body='<tr><td colspan="10">Sin datos registrados</td></tr>';else body+='<tr class="report-total-row"><th colspan="10">TOTAL HABITACIONES · Nº TOTAL DE UNIDADES: '+esc(rt.units)+'</th></tr><tr class="report-total-row"><th colspan="10">PUNTUACIÓN MEDIA PMH: '+esc(rt.mean===null?'Pendiente':rt.mean.toFixed(2))+'</th></tr>';return table('Habitaciones (PMH)',['Nº','Descripción de la habitación','Nº de unidades','¿Espacio suficiente entre cama y pared?','¿Espacio suficiente a los pies de la cama?','¿Sección de cama adecuada?','¿Espacio suficiente bajo la cama?','¿Altura adecuada de la silla?','Puntuación parcial por unidad','Puntos totales del tipo'],body);}
case'formation':return table('Formación (FF)',['Pregunta / criterio evaluado','Respuesta'],rows([['¿La formación fue un curso teórico-práctico de al menos 6 horas, organizado por el propio centro y con práctica específica en el uso de equipos de ayuda?',yn(f.ff_curso)],['¿Qué porcentaje de las personas trabajadoras que realizan manipulación de pacientes recibió el curso adecuado?',f.ff_cobertura??''],['¿La formación se realizó hace menos de 2 años respecto a esta evaluación?',yn(f.ff_antiguedad)],['Si la formación tiene más de 2 años, ¿se ha verificado su eficacia?',yn(f.ff_eficacia)],['Si no existe curso adecuado, ¿se realizó al menos información/adiestramiento en el uso de equipos o se distribuyó material informativo al 90% de la plantilla y se verificó su eficacia?',yn(f.ff_informacion)],['FF calculado',r.ff==null?'':n(r.ff).toFixed(2)]]));
case'factors':return table('Resultado MAPO y factores',['Indicador','Valor'],rows([['MAPO',r.mapo==null?'':n(r.mapo).toFixed(2)],['Nivel de exposición',r.nivel||''],['FS',r.fs==null?'':n(r.fs).toFixed(2)],['FA',r.fa==null?'':n(r.fa).toFixed(2)],['FC',r.fc==null?'Pendiente':n(r.fc).toFixed(2)],['Famb',r.famb==null?'Pendiente':n(r.famb).toFixed(2)],['FF',r.ff==null?'':n(r.ff).toFixed(2)]]));
default:return '<p>Tabla no disponible.</p>';}}
function tableToHtml(tableEl){const clone=tableEl.cloneNode(true),sourceCells=tableEl.querySelectorAll('th,td'),cloneCells=clone.querySelectorAll('th,td');clone.style.cssText='width:100%;border-collapse:collapse;font-family:Arial,sans-serif;font-size:10pt;color:#000';cloneCells.forEach((c,i)=>{const s=sourceCells[i],cs=getComputedStyle(s);c.style.cssText='font-family:'+cs.fontFamily+';font-size:'+cs.fontSize+';font-weight:'+cs.fontWeight+';color:'+cs.color+';background-color:'+cs.backgroundColor+';border:'+cs.border+';padding:'+cs.padding+';text-align:'+cs.textAlign+';vertical-align:'+cs.verticalAlign+';line-height:'+cs.lineHeight;});return '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body style="font-family:Arial,sans-serif;font-size:10pt;">'+clone.outerHTML+'</body></html>';}
async function copyTable(btn){const tableEl=btn.closest('.report-table-block')?.querySelector('.mapo-report-table');if(!tableEl)return;const html=tableToHtml(tableEl),text=tableEl.innerText;try{if(navigator.clipboard&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);else throw new Error('clipboard');const old=btn.textContent;btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent=old,1800);}catch(e){const range=document.createRange();range.selectNode(tableEl);const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);try{document.execCommand('copy');btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent='Copiar tabla para Word',1800);}finally{sel.removeAllRanges();}}}
function render(){const host=$('reportTables');if(!host)return;const checks=[...document.querySelectorAll('[data-report-table]')].filter(x=>x.checked);host.innerHTML=checks.map(x=>build(x.dataset.reportTable)).join('')||'<p class="report-tables-empty">Seleccione al menos una tabla.</p>';host.querySelectorAll('.copy-report-table').forEach(b=>b.onclick=()=>copyTable(b));}
function init(){const result=$('result');if(!result)return;let section=document.getElementById('reportTablesPanel');if(!section){section=document.createElement('section');section.id='reportTablesPanel';section.className='card';section.hidden=true;section.innerHTML='<div class="section-heading"><div><h2>Tablas para informe Word</h2><p>Seleccione las tablas que desea preparar.</p></div></div><div class="report-table-selectors">'+[['general','Datos generales'],['workers','Personas trabajadoras y horarios'],['patients','Tipología de pacientes'],['mobilizations','Movilizaciones'],['fs','Factor de elevación (FS)'],['fa','Factor de ayudas menores (FA)'],['wheelchairs','Sillas de ruedas (FC)'],['bathrooms','Baños — PMB y PMWC'],['rooms','Habitaciones — PMH'],['formation','Formación (FF)'],['factors','Resultado MAPO y factores']].map(d=>'<label><input type="checkbox" data-report-table="'+d[0]+'"> '+d[1]+'</label>').join('')+'</div><div class="actions"><button type="button" id="generateReportTables">Generar tablas</button><button type="button" id="copyAllReportTables" class="secondary">Copiar todas las tablas</button></div><div id="reportTables"></div>';result.parentNode.insertBefore(section,result.nextSibling);}
 const actions=result.querySelector('.actions');if(actions&&!document.getElementById('openReportTables')){const b=document.createElement('button');b.type='button';b.id='openReportTables';b.className='secondary';b.textContent='Crear tablas para informe Word';actions.appendChild(b);b.onclick=()=>{section.hidden=false;section.scrollIntoView({behavior:'smooth'});};}
 const generate=$('generateReportTables');if(generate)generate.onclick=render;
 const all=$('copyAllReportTables');if(all)all.onclick=async()=>{render();const tables=[...document.querySelectorAll('#reportTables .mapo-report-table')];if(!tables.length)return;const html='<!DOCTYPE html><html><body>'+tables.map(t=>tableToHtml(t).replace(/^<!DOCTYPE html><html><head><meta charset="UTF-8"><\/head><body>|<\/body><\/html>$/g,'')).join('<br>')+'</body></html>',text=tables.map(t=>t.innerText).join('\n\n');try{if(navigator.clipboard&&window.ClipboardItem)await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);else throw new Error('clipboard');all.textContent='✓ Tablas copiadas';setTimeout(()=>all.textContent='Copiar todas las tablas',1800);}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();all.textContent='✓ Tablas copiadas';setTimeout(()=>all.textContent='Copiar todas las tablas',1800);}};
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.MAPOReportTables={render,build};
})();
