/* MAPO Analyzer — tablas para informe Word. */
(function(){
'use strict';
const $=id=>document.getElementById(id),n=v=>Number(v||0),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yn=v=>v===true?'Sí':v===false?'No':'',pct=v=>n(v).toFixed(1)+'%';
function formatDate(v){if(!v)return '';const s=String(v).trim();let d;if(/^\d{4}-\d{2}-\d{2}/.test(s)){const p=s.slice(0,10).split('-');d=new Date(Number(p[0]),Number(p[1])-1,Number(p[2]));}else if(/^\d{2}[\/-]\d{2}[\/-]\d{4}$/.test(s)){const p=s.split(/[\/-]/);d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));}else return s;return Number.isNaN(d.getTime())?s:String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear();}
const shifts=['Mañana','Tarde','Noche'];
function data(){return typeof window.MAPOReportState==='function'?window.MAPOReportState():{form:{},result:{}};}
function rows(t){return t.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c)+'</td>').join('')+'</tr>').join('');}
function table(title,heads,body){return '<div class="report-table-block"><h3>'+esc(title)+'</h3><table class="mapo-report-table"><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+body+'</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';}
function scoreTotals(xs,fields){let units=0,points=0;xs.forEach(x=>{const u=n(x.units);if(u<=0)return;units+=u;points+=u*fields.reduce((s,f)=>s+(x[f[0]]===true?f[1]:0),0);});return{units,points,mean:units?points/units:null};}
function roomTotals(xs){return scoreTotals(xs,[['between',2],['foot',2],['bedSection',1],['underbed',2],['chairHeight',.5]]);}
function qval(f,id){const v=f?.[id];return v===true?'Sí':v===false?'No':v===null||v===undefined||v===''?'Sin responder':v;}
function build(key){const {form:f,result:r}=data(),t=r.taskTotals||{};switch(key){
case'general':{const all=[['Hospital / empresa',f.empresa],['Sala / unidad',f.unidad],['Fecha de evaluación',formatDate(f.fecha)],['Código de sala',f.codigo],['Número de camas',f.camas]];const valid=all.filter(x=>x[1]!==null&&x[1]!==undefined&&String(x[1]).trim()!=='');return table('Datos generales',['Campo','Valor'],rows(valid));}
case'patients':{const p=f.patientTypes||{};return table('Tipología de pacientes',['Dato','Valor'],rows([['AUTÓNOMOS',n(p.autonomo)],['COLABORADORES',n(p.colaborador)],['NO COLABORADORES',n(p.noColaborador)],['ENCAMADOS',n(p.encamado)],['NC',n(f.nc)],['PC',n(f.pc)],['NA',n(f.na)]]));}
case'mobilizations':{const out=[];const tasks=f.tasks&&typeof f.tasks==='object'?f.tasks:{};const catalog=Array.isArray(window.HOSPITALIZATION_MOBILIZATIONS)?window.HOSPITALIZATION_MOBILIZATIONS:[];const by=new Map(catalog.map(x=>[x.id,x]));Object.keys(tasks).forEach(id=>{const task=by.get(id)||{name:id},turns=tasks[id]||{};for(let i=0;i<3;i++){const r0=turns[i]||{},v=[n(r0.tm),n(r0.ta),n(r0.pm),n(r0.pa)];if(v.some(Boolean))out.push([task.name||id,['Mañana','Tarde','Noche'][i],...v]);}});out.sort((a,b)=>(['Mañana','Tarde','Noche'].indexOf(a[1])-['Mañana','Tarde','Noche'].indexOf(b[1]))||String(a[0]).localeCompare(String(b[0]),'es'));return table('Movilizaciones',['Tarea','Turno','Total manual','Total con ayuda','Parcial manual','Parcial con ayuda'],rows(out))+table('Totales de movilización',['Indicador','Valor'],rows([['ST',n(t.st)],['LTA',n(t.lta)],['% LTA',pct(t.pLTA)],['SP',n(t.sp)],['LPA',n(t.lpa)],['% LPA',pct(t.pLPA)],['STP',n(t.stp)]]));}
case'fs':return table('Factor de elevación (FS)',['Dato','Valor'],rows([['¿Hay al menos 1 elevador utilizable por cada 8 pacientes no colaboradores (NC)?',qval(f,'fs_elevadores')],['¿Hay al menos 1 camilla regulable por cada 8 pacientes NC y, cuando se utiliza para la transferencia cama-camilla, se acompaña de tabla, sábana deslizante, rollboard o equivalente?',qval(f,'fs_camillas')],['¿Las camas regulables en altura con 3 nodos están disponibles para el 100% de los pacientes de la unidad?',qval(f,'fs_camas3')],['Número de levantamientos totales realizados con equipamiento de ayuda (movilizaciones)',n(t.lta)],['Número total de levantamientos totales evaluados (movilizaciones)',n(t.st)],['FS calculado',r.fs==null?'':n(r.fs).toFixed(2)],['% LTA',pct(t.pLTA)]]));
case'fa':return table('Factor de ayudas menores (FA)',['Dato','Valor'],rows([['¿Hay sábana o tabla deslizante disponible?',qval(f,'fa_sabana')],['¿Hay además al menos dos de las otras ayudas menores indicadas en la ficha?',qval(f,'fa_dos')],['¿Todas las camas de la unidad son regulables en altura y tienen 3 nodos de articulación?',qval(f,'fa_camas3')],['Número de levantamientos parciales (movilizaciones parciales) realizados con equipamiento de ayuda',n(t.lpa)],['Número total de levantamientos parciales (movilizaciones parciales) evaluados',n(t.sp)],['FA calculado',r.fa==null?'':n(r.fa).toFixed(2)],['% LPA',pct(t.pLPA)]]));
default:return '<p>Tabla no disponible.</p>';}}
function render(){const host=$('reportTables');if(!host)return;const checks=[...document.querySelectorAll('[data-report-table]')].filter(x=>x.checked);host.innerHTML=checks.map(x=>build(x.dataset.reportTable)).join('')||'<p class="report-tables-empty">Seleccione al menos una tabla.</p>';host.querySelectorAll('.copy-report-table').forEach(b=>b.onclick=()=>{});}
function init(){const result=$('result');if(!result)return;let section=document.getElementById('reportTablesPanel');if(!section){section=document.createElement('section');section.id='reportTablesPanel';section.className='card';section.hidden=true;section.innerHTML='<div class="section-heading"><div><h2>Tablas para informe Word</h2></div></div><div id="reportTables"></div>';result.parentNode.insertBefore(section,result.nextSibling);}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();window.MAPOReportTables={build,render};
})();
