/* MAPO report tables boot — un único sistema de botones de copia */
(function(){
'use strict';
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const num=v=>Number(v||0);
const shifts=[['Mañana','morning'],['Tarde','afternoon'],['Noche','night']];
function minutes(v){const m=String(v??'').match(/^(\d{1,2})(?::(\d{2}))?/);return m?Number(m[1])*60+Number(m[2]||0):NaN;}
function overlapHours(a,b,c,d){let s=minutes(a),e=minutes(b),p=minutes(c),q=minutes(d);if(!Number.isFinite(s)||!Number.isFinite(e)||!Number.isFinite(p)||!Number.isFinite(q))return 0;if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best/60;}
function dayFactor(r){const d=r?.daysWorked;if(!d)return 5/7;if(d.type==='longshort')return 1;return Array.isArray(d.selected)?d.selected.length/7:5/7;}
function buildWorkers(){
 const state=typeof window.MAPOReportState==='function'?window.MAPOReportState():{form:{}};
 const f=state.form||{},s=f.workerSchedule||{},full=Array.isArray(s.full)?s.full:[],partial=Array.isArray(s.partial)?s.partial:[];
 const validFull=full.filter(r=>r&&r.start&&r.end&&num(r.people)>0),validPartial=partial.filter(r=>r&&r.start&&r.end&&num(r.people)>0);
 const totalPlant=validFull.reduce((z,r)=>z+num(r.people),0);
 let html='<div class="personnel-report"><h3>1. ENTREVISTA</h3><h4>1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP:</h4><p class="report-note"><strong>Número total de personas trabajadoras de planta.</strong></p>';
 html+='<div class="report-table-block"><h4>Personal de planta</h4><table class="mapo-report-table personnel-summary"><tbody><tr><th>Número total de personas trabajadoras de planta</th><td>'+esc(totalPlant)+'</td></tr><tr><th>Aux. enfermería</th><td>'+esc(f.auxEnfermeria??f.aux_enfermeria??'')+'</td></tr><tr><th>Aux. geriatría</th><td>'+esc(f.auxGeriatria??f.aux_geriatria??'')+'</td></tr><tr><th>Personal con limitación para MMP</th><td>'+esc(f.personalLimitacionMMP??f.personal_limitacion_mmp??f.limitacionMMP??'')+'</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 html+='<h4>1.1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP DURANTE LOS 3 TURNOS:</h4><p class="report-note"><strong>Número de personas trabajadoras presentes en toda la duración de cada turno.</strong></p><div class="report-table-block"><h4>Personal por turnos</h4><table class="mapo-report-table personnel-shifts"><thead><tr><th>TURNO</th><th>Nº de personas trabajadoras/Turno (A)</th><th>Horario del turno</th></tr></thead><tbody>';
 for(let i=0;i<3;i++){const r=validFull[i]||{};html+='<tr><td><strong>'+shifts[i][0]+'</strong></td><td>'+esc(r.people===''?'':num(r.people))+'</td><td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td></tr>';}
 html+='</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 html+='<h4>1.1.2. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP A TIEMPO PARCIAL:</h4><p class="report-note"><strong>Turno y horario de presencia.</strong><br>(En el caso de horarios diferentes por turno se añaden las filas siguientes tantas veces como sea necesario)</p><div class="report-table-block"><h4>Personal a tiempo parcial</h4><table class="mapo-report-table personnel-partial"><thead><tr><th>TURNO</th><th>Horario de presencia</th><th>Fracción de unidad (C)</th><th>Nº personas trabajadoras (D)</th><th>Fracción de unidad por persona trabajadora (C×D)</th></tr></thead><tbody>';
 for(const [name,key] of shifts){const turn=s.shifts?.[key]||{};const entries=validPartial.flatMap(r=>{const h=overlapHours(r.start,r.end,turn.start,turn.end);if(h<=0)return[];return[{r,h}];});if(!entries.length){html+='<tr><td><strong>'+name+'</strong></td><td></td><td>0.00</td><td>0</td><td>0.00</td></tr>';continue;}for(const x of entries){const c=x.h/8,d=num(x.r.people),cd=c*d;html+='<tr><td><strong>'+name+'</strong></td><td>'+esc(x.r.start+'-'+x.r.end)+'</td><td>'+c.toFixed(2)+'</td><td>'+d+'</td><td>'+cd.toFixed(2)+'</td></tr>';}}
 html+='</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>';
 let op=0;const calc=window.WorkersScheduleV3?.calculate; if(typeof calc==='function'){try{op=calc().OP||0;}catch(e){op=num(f.op);}}else op=num(f.op);
 html+='<div class="report-table-block personnel-op"><table class="mapo-report-table"><tbody><tr><th>Nº TOTAL DE PERSONAS TRABAJADORAS EN 24 HORAS (Op)</th><td>'+op.toFixed(2)+'</td></tr><tr><td colspan="2">Total de personas trabajadoras/turno de todos los turnos (A) + Fracción de unidad por persona trabajadora (D), ponderadas según las horas de presencia y los días trabajados.</td></tr></tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div></div>';
 return html;
}
function boot(){
 const result=document.getElementById('result');
 if(!result||!result.parentNode||document.getElementById('openReportTables'))return;
 const section=document.createElement('section');section.id='reportTablesPanel';section.className='card';section.hidden=true;
 const defs=[['general','Datos generales'],['workers','Personas trabajadoras y horarios'],['patients','Tipología de pacientes'],['mobilizations','Movilizaciones'],['fs','Factor de elevación (FS)'],['fa','Factor de ayudas menores (FA)'],['wheelchairs','Sillas de ruedas (FC)'],['bathrooms','Baños — PMB y PMWC'],['rooms','Habitaciones — PMH'],['formation','Formación (FF)'],['factors','Resultado MAPO y factores']];
 section.innerHTML='<div class="section-heading"><div><h2>Tablas para informe Word</h2><p>Seleccione las tablas que desea preparar.</p></div></div><div class="report-table-selectors">'+defs.map(d=>'<label><input type="checkbox" data-report-table="'+d[0]+'"> '+d[1]+'</label>').join('')+'</div><div class="actions"><button type="button" id="generateReportTables">Generar tablas</button><button type="button" id="copyAllReportTables" class="secondary">Copiar todas las tablas</button></div><div id="reportTables"></div>';
 result.parentNode.insertBefore(section,result.nextSibling);
 const actions=result.querySelector('.actions');if(actions){const open=document.createElement('button');open.type='button';open.id='openReportTables';open.className='secondary';open.textContent='Crear tablas para informe Word';actions.appendChild(open);open.onclick=()=>{section.hidden=false;section.scrollIntoView({behavior:'smooth'});};}
 function render(){const host=document.getElementById('reportTables'),api=window.MAPOReportTables;if(!host||!api||typeof api.build!=='function'){if(host)host.innerHTML='<p class="error">No se ha cargado el generador de tablas.</p>';return;}const checks=[...section.querySelectorAll('[data-report-table]')].filter(x=>x.checked);host.innerHTML=checks.map(x=>x.dataset.reportTable==='workers'?buildWorkers():api.build(x.dataset.reportTable)).join('')||'<p class="report-tables-empty">Seleccione al menos una tabla.</p>';host.querySelectorAll('.copy-report-table').forEach(b=>b.onclick=()=>copyOne(b));}
 function copyOne(btn){const t=btn.closest('.report-table-block')?.querySelector('.mapo-report-table');if(!t)return;const html='<!DOCTYPE html><html><body>'+t.outerHTML+'</body></html>',text=t.innerText;const done=()=>{const old=btn.textContent;btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent=old,1600);};if(navigator.clipboard&&window.ClipboardItem)navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]).then(done).catch(fallback);else fallback();function fallback(){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();done();}}
 const generate=document.getElementById('generateReportTables');if(generate)generate.onclick=render;
 const all=document.getElementById('copyAllReportTables');if(all)all.onclick=()=>{render();setTimeout(copyAll,0);};
 function copyAll(){const host=document.getElementById('reportTables');if(!host)return;const tables=[...host.querySelectorAll('.mapo-report-table')];if(!tables.length)return;const html='<!DOCTYPE html><html><body>'+tables.map(t=>t.outerHTML).join('<br>')+'</body></html>';const text=tables.map(t=>t.innerText).join('\n\n');const done=()=>{const old=all.textContent;all.textContent='✓ Tablas copiadas';setTimeout(()=>all.textContent=old,1600);};if(navigator.clipboard&&window.ClipboardItem)navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]).then(done).catch(fallback);else fallback();function fallback(){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();done();}}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();