/* Corrección de presentación de tablas MAPO para Word. No modifica cálculos. */
(function(){
'use strict';
const BLUE='#759CBF';
const $=id=>document.getElementById(id);
const n=v=>Number(v||0);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shifts=['Mañana','Tarde','Noche'];
function state(){return window.MAPOReportState?.()||{form:{},result:{}};}
function cell(v,head=false){return `<${head?'th':'td'}>${esc(v)}</${head?'th':'td'}`;}
function table(title,head,body,cls=''){return `<div class="report-table-block ${cls}"><h3>${esc(title)}</h3><table class="mapo-report-table"><thead><tr>${head.map(x=>cell(x,true)).join('')}</tr></thead><tbody>${body}</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>`;}
function kv(title,rows){return table(title,['',''],rows.map(r=>`<tr>${cell(r[0],true)}${cell(r[1])}</tr>`).join(''));}
function workers(f){const s=f.workerSchedule||{},full=Array.isArray(s.full)?s.full:[],partial=Array.isArray(s.partial)?s.partial:[];const total=full.reduce((a,r)=>a+n(r.people),0);let b='';b+=`<tr>${cell('Enfermeras',true)}${cell(f.enfermeras??'')}</tr>`;b+=`<tr>${cell('Aux. Enfermería',true)}${cell(f.auxEnfermeria??f.aux_enfermeria??'')}</tr>`;b+=`<tr>${cell('Celadores',true)}${cell(f.celadores??'')}</tr>`;b+=`<tr>${cell('Trabajadores con limitación MMP',true)}${cell(f.personalLimitacionMMP??f.personal_limitacion_mmp??'')}</tr>`;b+=`<tr>${cell('Total trabajadores de planta',true)}${cell(total)}</tr>`;let h=table('1.1 Nº TRABAJADORES QUE REALIZAN MMP',['Concepto','Valor'],b);let sh='<tr>'+cell('TURNO',true)+shifts.map(x=>cell(x,true)).join('')+'</tr>';sh+='<tr>'+cell('Nº Trabajadores/Turno (A)',true)+full.slice(0,3).map(r=>cell(r?.people===''?'':n(r?.people))).join('')+'</tr>';sh+='<tr>'+cell('Horario del turno',true)+full.slice(0,3).map(r=>cell(r?.start&&r?.end?`${r.start}-${r.end}`:'')).join('')+'</tr>';h+=`<div class="report-table-block"><h4>1.1.1 Nº TRABAJADORES QUE REALIZAN MMP DURANTE LOS TRES TURNOS</h4><table class="mapo-report-table personnel-shifts"><tbody>${sh}</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>`;let p='<tr>'+cell('TURNO',true)+shifts.map(x=>cell(x,true)).join('')+'</tr>';p+='<tr>'+cell('Nº trabajadores tiempo parcial (B)',true)+shifts.map((_,i)=>cell(partial.filter(r=>r&&r.start&&r.end&&n(r.people)>0).filter(r=>i===i).reduce((a,r)=>a+n(r.people),0))).join('')+'</tr>';p+='<tr>'+cell('Horario presencia en la sala',true)+shifts.map((_,i)=>{const r=partial.find(x=>x&&x.start&&x.end&&n(x.people)>0);return cell(r&&i===0?`${r.start}-${r.end}`:'')}).join('')+'</tr>';h+=`<div class="report-table-block"><h4>1.1.2 Nº TRABAJADORES QUE REALIZAN MMP A TIEMPO PARCIAL</h4><table class="mapo-report-table personnel-partial"><tbody>${p}</tbody></table><div class="report-table-actions"><button type="button" class="copy-report-table">Copiar tabla para Word</button></div></div>`;return h;}
function patients(f){const p=f.patientTypes||{};const rows=[['Anciano con pluripatologías',p.anciano??p.ancianoPluripatologias??'',''],['Hemipléjico',p.hemiplejico??'',''],['Quirúrgico',p.quirurgico??'',''],['Traumático',p.traumatico??'',''],['Demente/Psiquiátrico',p.demente??p.psiquiatrico??'',''],['Otras patologías neurológicas',p.otrasNeurologicas??'',''],['Fractura',p.fractura??'',''],['Obeso',p.obeso??'',''],['Otros',p.otros??'','']];let body=rows.map(r=>`<tr>${cell(r[0],true)}${cell(r[1])}${cell(r[2])}</tr>`).join('');return table('1.2 TIPOLOGÍA DEL PACIENTE',['TIPOLOGÍA','NC / PC',''],body);}
function mobilizations(f){const all=[...(window.MAPO_TASKS||[]),...(window.EXTRA_MAPO_TASKS||[])],t=f.tasks||{};let body='';all.forEach(x=>{const r=[0,1,2].map(i=>t[x.id]?.[i]||{});body+=`<tr>${cell(x.label,true)}${r.map(z=>cell(n(z.tm)+n(z.ta))).join('')}${r.map(z=>cell(n(z.pm)+n(z.pa))).join('')}</tr>`});return table('1.5 TAREAS DE MOVILIZACIÓN DE PACIENTES HABITUALMENTE REALIZADAS EN UN TURNO',['MOVILIZACIÓN MANUAL','LTM Mañana','LTM Tarde','LTM Noche','LPM Mañana','LPM Tarde','LPM Noche'],body);}
function build(key){const {form:f,result:r}=state();const t=r.taskTotals||{};switch(key){case'general':return kv('DATOS GENERALES',[['HOSPITAL / EMPRESA',f.empresa||''],['UNIDAD / SALA',f.unidad||''],['FECHA',f.fecha||''],['SERVICIO',f.servicio||''],['Nº CAMAS',f.camas??''],['Nº MEDIO DÍAS ESTANCIA',f.diasEstancia??'']]);case'workers':return workers(f);case'patients':return patients(f);case'mobilizations':return mobilizations(f);case'fs':return kv('VALOR DEL FACTOR DE ELEVACIÓN (FS)',[['FS',r.fs==null?'':n(r.fs).toFixed(2)],['% LTA',n(t.pLTA).toFixed(1)+'%']]);case'fa':return kv('VALOR DEL FACTOR DE AYUDAS MENORES (FA)',[['FA',r.fa==null?'':n(r.fa).toFixed(2)],['% LPA',n(t.pLPA).toFixed(1)+'%']]);case'wheelchairs':return kv('FACTOR SILLA DE RUEDAS (FC)',[['FC',r.fc==null?'':n(r.fc).toFixed(2)]]);case'bathrooms':return kv('FACTOR AMBIENTE',[['PMB',r.details?.pmB==null?'':n(r.details.pmB).toFixed(2)],['PMWC',r.details?.pmWC==null?'':n(r.details.pmWC).toFixed(2)]]);case'rooms':return kv('HABITACIONES',[['PMH',r.details?.pmH==null?'':n(r.details.pmH).toFixed(2)]]);case'formation':return kv('FACTOR FORMACIÓN (FF)',[['FF',r.ff==null?'':n(r.ff).toFixed(2)]]);case'factors':return table('ÍNDICE DE EXPOSICIÓN MAPO',['INDICADOR','VALOR'],[['MAPO',r.mapo==null?'':n(r.mapo).toFixed(2)],['NIVEL DE EXPOSICIÓN',r.nivel||''],['FS',r.fs==null?'':n(r.fs).toFixed(2)],['FA',r.fa==null?'':n(r.fa).toFixed(2)],['FC',r.fc==null?'':n(r.fc).toFixed(2)],['Famb',r.famb==null?'':n(r.famb).toFixed(2)],['FF',r.ff==null?'':n(r.ff).toFixed(2)]].map(r=>`<tr>${cell(r[0],true)}${cell(r[1])}</tr>`).join(''));default:return '<p>Tabla no disponible.</p>';}}
function styleTables(root){root.querySelectorAll('.mapo-report-table').forEach(t=>{t.style.fontFamily='Arial,sans-serif';t.style.fontSize='10pt';t.style.color='#000';t.style.backgroundColor='#fff';t.style.borderCollapse='collapse';t.querySelectorAll('th,td').forEach(c=>{c.style.fontFamily='Arial,sans-serif';c.style.fontSize='10pt';c.style.padding='4pt 6pt';c.style.border='0.5pt solid #759CBF';c.style.verticalAlign='top';c.style.color=c.tagName==='TH'?BLUE:'#000';c.style.backgroundColor='#fff';});});}
function styleClone(t){t.style.fontFamily='Arial,sans-serif';t.style.fontSize='10pt';t.style.color='#000';t.style.backgroundColor='#fff';t.style.borderCollapse='collapse';t.querySelectorAll('th,td').forEach(c=>{c.style.fontFamily='Arial,sans-serif';c.style.fontSize='10pt';c.style.padding='4pt 6pt';c.style.border='0.5pt solid #759CBF';c.style.verticalAlign='top';c.style.color=c.tagName==='TH'?BLUE:'#000';c.style.backgroundColor='#fff';});}
function render(){const host=$('reportTables');if(!host)return;const checks=[...document.querySelectorAll('[data-report-table]')].filter(x=>x.checked);host.innerHTML=checks.map(x=>build(x.dataset.reportTable)).join('')||'<p class="report-tables-empty">Seleccione al menos una tabla.</p>';styleTables(host);host.querySelectorAll('.copy-report-table').forEach(btn=>btn.addEventListener('click',()=>copy(btn)));}
async function copy(btn){const t=btn.closest('.report-table-block')?.querySelector('.mapo-report-table');if(!t)return;const c=t.cloneNode(true);styleClone(c);const html='<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body>'+c.outerHTML+'</body></html>';const text=t.innerText;try{await navigator.clipboard.write([new ClipboardItem({'text/html':new Blob([html],{type:'text/html'}),'text/plain':new Blob([text],{type:'text/plain'})})]);btn.textContent='✓ Tabla copiada';setTimeout(()=>btn.textContent='Copiar tabla para Word',1800);}catch(e){const r=document.createRange();r.selectNode(t);const s=getSelection();s.removeAllRanges();s.addRange(r);document.execCommand('copy');s.removeAllRanges();}}
window.MAPOReportTablesFormatFix={render};window.addEventListener('DOMContentLoaded',()=>{setTimeout(()=>{if(window.MAPOReportTables)window.MAPOReportTables.render=render;},0);});
})();
