const HOSPITALIZATION_MOBILIZATIONS=[
{id:'head_bed',name:'Desplazamiento hacia la cabecera de la cama',source:'MAPO'},{id:'bed_wheelchair',name:'De la cama a la silla de ruedas / sillón / silla',source:'MAPO'},{id:'wheelchair_bed',name:'De la silla de ruedas / sillón / silla a la cama',source:'MAPO'},{id:'bed_stretcher',name:'De la cama a la camilla',source:'MAPO'},{id:'stretcher_bed',name:'De la camilla a la cama',source:'MAPO'},{id:'wheelchair_toilet',name:'De la silla de ruedas al WC',source:'MAPO'},{id:'toilet_wheelchair',name:'Del WC a la silla de ruedas',source:'MAPO'},{id:'bed_turning',name:'Rotación en la cama y cambio postural (cambio de decúbito)',source:'MAPO'},{id:'sit_to_stand',name:'Levantamiento de posición sentada a postura de pie',source:'MAPO'},{id:'bed_shower',name:'De la cama a la silla de ducha / baño',source:'Complementaria'},{id:'shower_bed',name:'De la silla de ducha / baño a la cama',source:'Complementaria'},{id:'wheelchair_armchair',name:'De la silla de ruedas a sillón / butaca',source:'Complementaria'},{id:'armchair_wheelchair',name:'Del sillón / butaca a la silla de ruedas',source:'Complementaria'},{id:'reposition_chair',name:'Reposicionamiento del paciente en silla de ruedas / sillón',source:'Complementaria'},{id:'move_up_bed',name:'Desplazamiento del paciente hacia arriba en la cama',source:'Complementaria'},{id:'roll_bed',name:'Giro / rodamiento de un lado a otro en la cama',source:'Complementaria'},{id:'sit_edge',name:'Paso de decúbito a sedestación en el borde de la cama',source:'Complementaria'},{id:'floor_recovery',name:'Recuperación de un paciente desde el suelo',source:'Complementaria'},{id:'bed_exam',name:'De la cama a mesa de exploración / procedimiento',source:'Complementaria'},{id:'exam_bed',name:'De mesa de exploración / procedimiento a la cama',source:'Complementaria'}];
const MOBILIZATION_LIMITS={maxCustom:20};
function emptyMobilizationEntry(){return{manualTotal:[0,0,0],manualPartial:[0,0,0],aidedTotal:[0,0,0],aidedPartial:[0,0,0]};}
function emptyMobilizationData(){return{entries:{},custom:[]};}
function mobilizationData(){if(!formData.mobilizations)formData.mobilizations=emptyMobilizationData();return formData.mobilizations;}
function mobInput(k,s,v){return `<input class="mob-count" type="number" min="0" step="1" data-mob-key="${k}" data-mob-shift="${s}" value="${v||0}">`;}
function mobTable(cat,turn,d){const names={manualTotal:'Manual — total',manualPartial:'Manual — parcial',aidedTotal:'Con ayuda — total',aidedPartial:'Con ayuda — parcial'},shift=['Mañana','Tarde','Noche'][turn],rows=HOSPITALIZATION_MOBILIZATIONS;return `<div class="mob-table-wrap"><table class="mob-table"><thead><tr><th>Tarea</th><th>${names[cat]}</th></tr><tr><th></th><th>${shift}</th></tr></thead><tbody><tr class="mob-section"><td colspan="2">Tareas MAPO</td></tr>${rows.filter(x=>x.source==='MAPO').map(x=>{const e=d.entries[x.id]||emptyMobilizationEntry();return `<tr data-mob-id="${x.id}"><td><strong>${x.name}</strong></td><td>${mobInput(cat,turn,e[cat][turn])}</td></tr>`}).join('')}<tr class="mob-section"><td colspan="2">Categorías adicionales de movilización</td></tr>${rows.filter(x=>x.source==='Complementaria').map(x=>{const e=d.entries[x.id]||emptyMobilizationEntry();return `<tr data-mob-id="${x.id}"><td><strong>${x.name}</strong><small class="mob-source">Categoría adicional — contabiliza igual que una tarea MAPO</small></td><td>${mobInput(cat,turn,e[cat][turn])}</td></tr>`}).join('')}<tr class="mob-section"><td colspan="2">Otras movilizaciones definidas por el usuario</td></tr>${d.custom.length?d.custom.map((x,i)=>{const e=d.entries[x.id]||emptyMobilizationEntry();return `<tr data-mob-id="${x.id}" data-custom="true"><td><input class="mob-custom-name" data-custom-index="${i}" value="${x.name||''}" placeholder="Describa la movilización"><small class="mob-source">Movilización personalizada</small></td><td>${mobInput(cat,turn,e[cat][turn])}</td></tr>`}).join(''):'<tr><td colspan="2" class="small">Ninguna.</td></tr>'}</tbody></table></div><div class="actions"><button type="button" id="addCustomMob">Añadir otra movilización</button></div><div id="mobSummary" class="schedule-preview"></div>`;}
function captureMobilizations(){const d=mobilizationData();document.querySelectorAll('[data-mob-id]').forEach(r=>{const id=r.dataset.mobId;if(!d.entries[id])d.entries[id]=emptyMobilizationEntry();r.querySelectorAll('.mob-count').forEach(i=>{const k=i.dataset.mobKey,s=Number(i.dataset.mobShift);d.entries[id][k][s]=Math.max(0,Math.floor(Number(i.value||0)));});if(r.dataset.custom==='true'){const n=Number(r.querySelector('.mob-custom-name')?.dataset.customIndex);if(Number.isInteger(n)&&d.custom[n])d.custom[n].name=r.querySelector('.mob-custom-name').value.trim();}});return d;}
function renderMobilizations(selectedCategory=null,selectedTurn=null){const d=mobilizationData();if(selectedCategory!==null&&selectedTurn!==null){$('formContainer').innerHTML=`<div class="step-title-row"><h3>Tareas de movilización de pacientes</h3><button type="button" class="help-trigger" id="mobHelpBtn">?</button><div class="help-popover" id="mobHelp" hidden><strong>Cómo registrar las movilizaciones</strong><p>Registre únicamente esta combinación de turno y tipo. Los datos de las demás combinaciones se conservan para el cálculo.</p></div></div>${mobTable(selectedCategory,selectedTurn,d)}`;}else{$('formContainer').innerHTML='<div class="step-title-row"><h3>Seleccione turno y tipo de movilización</h3></div>';}bindMobilizations();updateMobilizationSummary();}
function bindMobilizations(){$('mobHelpBtn')?.addEventListener('click',()=>{$('mobHelp').hidden=!$('mobHelp').hidden;});document.querySelectorAll('.mob-count').forEach(i=>i.addEventListener('input',()=>{captureMobilizations();updateMobilizationSummary();}));document.querySelectorAll('.mob-custom-name').forEach(i=>i.addEventListener('input',captureMobilizations));$('addCustomMob')?.addEventListener('click',()=>{captureMobilizations();const d=mobilizationData();if(d.custom.length>=MOBILIZATION_LIMITS.maxCustom){$('error').textContent='Máximo 20 movilizaciones personalizadas.';$('error').hidden=false;return;}const id=`custom_${Date.now()}_${d.custom.length}`;d.custom.push({id,name:''});d.entries[id]=emptyMobilizationEntry();renderMobilizations(window.MAPOMobilizationSelection?.category??null,window.MAPOMobilizationSelection?.turn??null);});}
function mobilizationTotals(){const d=captureMobilizations(),t={manualTotal:[0,0,0],manualPartial:[0,0,0],aidedTotal:[0,0,0],aidedPartial:[0,0,0]};Object.values(d.entries).forEach(e=>['manualTotal','manualPartial','aidedTotal','aidedPartial'].forEach(k=>e[k].forEach((v,i)=>t[k][i]+=Number(v||0))));const sum=k=>t[k].reduce((a,b)=>a+b,0),LTM=sum('manualTotal'),LTA=sum('aidedTotal'),LPM=sum('manualPartial'),LPA=sum('aidedPartial'),ST=LTM+LTA,SP=LPM+LPA,STP=ST+SP;return{totals:t,ST,SP,LTA,LPA,STP,pctLTA:ST?LTA/ST*100:0,pctLPA:SP?LPA/SP*100:0};}
function updateMobilizationSummary(){const x=mobilizationTotals();if($('mobSummary'))$('mobSummary').innerHTML=`<strong>Resultados automáticos de todas las movilizaciones registradas</strong> · ST=${x.ST} · LTA=${x.LTA} · %LTA=${x.pctLTA.toFixed(1)}% · SP=${x.SP} · LPA=${x.LPA} · %LPA=${x.pctLPA.toFixed(1)}% · STP=${x.STP}`;}
function validateMobilizations(){const x=mobilizationTotals();if(x.ST===0&&x.SP===0)throw Error('Debe registrar al menos una tarea de movilización.');return x;}
/* Exponer el catálogo para módulos de informe que solo necesitan leerlo. No cambia datos ni cálculos. */
window.HOSPITALIZATION_MOBILIZATIONS=HOSPITALIZATION_MOBILIZATIONS;
