const HOSPITALIZATION_MOBILIZATIONS=[
{id:'head_bed',name:'Desplazamiento hacia la cabecera de la cama',source:'MAPO'},
{id:'bed_wheelchair',name:'De la cama a la silla de ruedas / sillón / silla',source:'MAPO'},
{id:'wheelchair_bed',name:'De la silla de ruedas / sillón / silla a la cama',source:'MAPO'},
{id:'bed_stretcher',name:'De la cama a la camilla',source:'MAPO'},
{id:'stretcher_bed',name:'De la camilla a la cama',source:'MAPO'},
{id:'wheelchair_toilet',name:'De la silla de ruedas al WC',source:'MAPO'},
{id:'toilet_wheelchair',name:'Del WC a la silla de ruedas',source:'MAPO'},
{id:'bed_turning',name:'Rotación en la cama y cambio postural (cambio de decúbito)',source:'MAPO'},
{id:'sit_to_stand',name:'Levantamiento de posición sentada a postura de pie',source:'MAPO'},
{id:'bed_shower',name:'De la cama a la silla de ducha / baño',source:'Complementaria'},
{id:'shower_bed',name:'De la silla de ducha / baño a la cama',source:'Complementaria'},
{id:'wheelchair_armchair',name:'De la silla de ruedas a sillón / butaca',source:'Complementaria'},
{id:'armchair_wheelchair',name:'Del sillón / butaca a la silla de ruedas',source:'Complementaria'},
{id:'reposition_chair',name:'Reposicionamiento del paciente en silla de ruedas / sillón',source:'Complementaria'},
{id:'move_up_bed',name:'Desplazamiento del paciente hacia arriba en la cama',source:'Complementaria'},
{id:'roll_bed',name:'Giro / rodamiento de un lado a otro en la cama',source:'Complementaria'},
{id:'sit_edge',name:'Paso de decúbito a sedestación en el borde de la cama',source:'Complementaria'},
{id:'floor_recovery',name:'Recuperación de un paciente desde el suelo',source:'Complementaria'},
{id:'bed_exam',name:'De la cama a mesa de exploración / procedimiento',source:'Complementaria'},
{id:'exam_bed',name:'De mesa de exploración / procedimiento a la cama',source:'Complementaria'}];
const MOBILIZATION_LIMITS={maxCustom:20};
function emptyMobilizationEntry(){return{manualTotal:[0,0,0],manualPartial:[0,0,0],aidedTotal:[0,0,0],aidedPartial:[0,0,0]};}
function emptyMobilizationData(){return{entries:{},custom:[]};}
function mobilizationData(){if(!formData.mobilizations)formData.mobilizations=emptyMobilizationData();return formData.mobilizations;}
function mobInput(k,s,v){return `<input class="mob-count" type="number" min="0" step="1" data-mob-key="${k}" data-mob-shift="${s}" value="${v||0}">`;}
function mobRow(x,d){const e=d.entries[x.id]||emptyMobilizationEntry();return `<tr data-mob-id="${x.id}"><td><strong>${x.name}</strong>${x.source==='Complementaria'?'<small class="mob-source">Categoría adicional — contabiliza igual que una tarea MAPO</small>':''}</td>${['manualTotal','manualPartial','aidedTotal','aidedPartial'].flatMap(k=>[0,1,2].map(s=>`<td>${mobInput(k,s,e[k][s])}</td>`)).join('')}</tr>`;}
function customMobRow(x,i,d){const e=d.entries[x.id]||emptyMobilizationEntry();return `<tr data-mob-id="${x.id}" data-custom="true"><td><input class="mob-custom-name" data-custom-index="${i}" value="${x.name||''}" placeholder="Describa la movilización"><small class="mob-source">Movilización personalizada — contabiliza igual que una tarea MAPO</small></td>${['manualTotal','manualPartial','aidedTotal','aidedPartial'].flatMap(k=>[0,1,2].map(s=>`<td>${mobInput(k,s,e[k][s])}</td>`)).join('')}<td><button type="button" class="secondary mob-remove-custom" data-index="${i}">Eliminar</button></td></tr>`;}
function captureMobilizations(){const d=mobilizationData();document.querySelectorAll('[data-mob-id]').forEach(r=>{const id=r.dataset.mobId;if(!d.entries[id])d.entries[id]=emptyMobilizationEntry();r.querySelectorAll('.mob-count').forEach(i=>{const k=i.dataset.mobKey,s=Number(i.dataset.mobShift);d.entries[id][k][s]=Math.max(0,Math.floor(Number(i.value||0)));});if(r.dataset.custom==='true'){const n=Number(r.querySelector('.mob-custom-name')?.dataset.customIndex);if(Number.isInteger(n)&&d.custom[n])d.custom[n].name=r.querySelector('.mob-custom-name').value.trim();}});return d;}
function renderMobilizations(){const d=mobilizationData(),m=HOSPITALIZATION_MOBILIZATIONS.filter(x=>x.source==='MAPO'),e=HOSPITALIZATION_MOBILIZATIONS.filter(x=>x.source==='Complementaria');$('formContainer').innerHTML=`<div class="step-title-row"><h3>Tareas de movilización de pacientes</h3><button type="button" class="help-trigger" id="mobHelpBtn">?</button><div class="help-popover" id="mobHelp" hidden><strong>Cómo registrar las movilizaciones</strong><p>Primero busque la descripción que mejor corresponda a cada rutina real del servicio. Si conoce la categoría oficial MAPO, utilice una de las nueve tareas MAPO. Si la rutina no encaja claramente en una de ellas, puede utilizar una categoría adicional o crear una movilización personalizada.</p><p><strong>Todas las categorías, tanto MAPO como adicionales y personalizadas, se contabilizan exactamente igual</strong> en los campos de movilización: manual total, manual parcial, con ayuda total y con ayuda parcial. No es necesario conocer el nombre oficial MAPO para registrar una movilización.</p><p>Indique cuántas veces se realiza habitualmente cada tarea en cada turno. Separe levantamiento total/parcial y manual/con ayuda. El programa utiliza el conjunto completo de tareas registradas para calcular ST, LTA, SP, LPA, %LTA, %LPA y STP.</p><p>Las nueve primeras tareas corresponden al listado MAPO de Hospitalización. Las categorías adicionales y las personalizadas son únicamente una ayuda para clasificar con mayor claridad las rutinas observadas; <strong>no se excluyen del cálculo por el hecho de no ser categorías oficiales</strong>.</p></div></div><div class="mob-table-wrap"><table class="mob-table"><thead><tr><th rowspan="2">Tarea</th><th colspan="3">Manual — total</th><th colspan="3">Manual — parcial</th><th colspan="3">Con ayuda — total</th><th colspan="3">Con ayuda — parcial</th></tr><tr>${['Mañana','Tarde','Noche','Mañana','Tarde','Noche','Mañana','Tarde','Noche','Mañana','Tarde','Noche'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody><tr class="mob-section"><td colspan="13">Tareas MAPO</td></tr>${m.map(x=>mobRow(x,d)).join('')}<tr class="mob-section"><td colspan="13">Categorías adicionales de movilización</td></tr>${e.map(x=>mobRow(x,d)).join('')}<tr class="mob-section"><td colspan="14">Otras movilizaciones definidas por el usuario</td></tr>${d.custom.length?d.custom.map((x,i)=>customMobRow(x,i,d)).join(''):'<tr><td colspan="14" class="small">Ninguna.</td></tr>'}</tbody></table></div><div class="actions"><button type="button" id="addCustomMob">Añadir otra movilización</button></div><div id="mobSummary" class="schedule-preview"></div>`;bindMobilizations();updateMobilizationSummary();}
function bindMobilizations(){$('mobHelpBtn').onclick=()=>{$('mobHelp').hidden=!$('mobHelp').hidden;};document.querySelectorAll('.mob-count').forEach(i=>i.onchange=()=>{captureMobilizations();updateMobilizationSummary();});document.querySelectorAll('.mob-custom-name').forEach(i=>i.onchange=captureMobilizations);document.querySelectorAll('.mob-remove-custom').forEach(b=>b.onclick=()=>{captureMobilizations();mobilizationData().custom.splice(Number(b.dataset.index),1);renderMobilizations();});$('addCustomMob').onclick=()=>{captureMobilizations();const d=mobilizationData();if(d.custom.length>=MOBILIZATION_LIMITS.maxCustom){$('error').textContent='Máximo 20 movilizaciones personalizadas.';$('error').hidden=false;return;}const id=`custom_${Date.now()}_${d.custom.length}`;d.custom.push({id,name:''});d.entries[id]=emptyMobilizationEntry();renderMobilizations();};}
function mobilizationTotals(){const d=captureMobilizations(),t={manualTotal:[0,0,0],manualPartial:[0,0,0],aidedTotal:[0,0,0],aidedPartial:[0,0,0]};Object.values(d.entries).forEach(e=>['manualTotal','manualPartial','aidedTotal','aidedPartial'].forEach(k=>e[k].forEach((v,i)=>t[k][i]+=Number(v||0))));const sum=k=>t[k].reduce((a,b)=>a+b,0),ST=sum('manualTotal')+sum('aidedTotal'),SP=sum('manualPartial')+sum('aidedPartial'),LTA=sum('aidedTotal'),LPA=sum('aidedPartial');return{totals:t,ST,SP,LTA,LPA,STP:ST+SP,pctLTA:ST?LTA/ST*100:0,pctLPA:SP?LPA/SP*100:0};}
function updateMobilizationSummary(){const x=mobilizationTotals();$('mobSummary').innerHTML=`<strong>Resultados automáticos de todas las movilizaciones registradas</strong> · ST=${x.ST} · LTA=${x.LTA} · %LTA=${x.pctLTA.toFixed(1)}% · SP=${x.SP} · LPA=${x.LPA} · %LPA=${x.pctLPA.toFixed(1)}% · STP=${x.STP}`;}
function validateMobilizations(){const x=mobilizationTotals();if(x.ST===0&&x.SP===0)throw Error('Debe registrar al menos una tarea de movilización.');return x;}
