/* MAPO Analyzer — navegación especial.
   app.js = navegación general; study_io.js = IO; multi_room.js = salas;
   este módulo controla selector de estudio y subnavegación exclusiva de movilizaciones. */
(function(){'use strict';
 const $=id=>document.getElementById(id);
 const TURNS=['Mañana','Tarde','Noche'];
 const CATS=[['aidedTotal','Movilizaciones totales con ayuda'],['aidedPartial','Movilizaciones parciales con ayuda'],['manualTotal','Movilizaciones totales sin ayuda'],['manualPartial','Movilizaciones parciales sin ayuda']];
 const state=window.MAPOMobilizationSelection||{turn:null,category:null}; window.MAPOMobilizationSelection=state;
 const capture=()=>{try{window.captureMobilizations?.()}catch(_){} };
 function loadStudy(){const f=$('loadMultiStudyFile')||$('loadStudyFile');f?.click();}
 function saveStudy(){if(window.MAPOMultiRoom?.saveMultiStudy)return window.MAPOMultiRoom.saveMultiStudy();return $('saveStudy')?.click();}
 function setupNavigation(){const host=$('roomSetup');if(!host)return;host.querySelector('#roomSetupNavigation')?.remove();const bar=document.createElement('div');bar.id='roomSetupNavigation';bar.className='actions';bar.innerHTML='<button type="button" class="secondary" id="roomSetupBack">Anterior</button><button type="button" class="secondary" id="roomSetupSave">Guardar estudio</button><button type="button" class="secondary" id="roomSetupLoad">Cargar estudio</button><button type="button" id="roomSetupNext">Siguiente</button>';host.appendChild(bar);$('roomSetupBack').onclick=()=>{host.hidden=true;$('studySelection').hidden=false;};$('roomSetupSave').onclick=saveStudy;$('roomSetupLoad').onclick=loadStudy;$('roomSetupNext').onclick=()=>{const key=host.dataset.study;if(window.MAPOMultiRoom?.beginSelectedStudy)window.MAPOMultiRoom.beginSelectedStudy(key);else window.selectStudy?.(key);};}
 function openStudySetup(key){const host=$('roomSetup');if(!host)return;host.dataset.study=key;window.MAPOMultiRoom?.setStudyType?.(key);$('studySelection').hidden=true;host.hidden=false;$('studyPanel').hidden=true;$('result').hidden=true;$('globalResults').hidden=true;window.MAPOMultiRoom?.prepareRoomSetup?.();setupNavigation();}
 function installStudySelection(){document.querySelectorAll('.study-option').forEach(b=>{if(b.dataset.moduleNavBound)return;b.dataset.moduleNavBound='1';b.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();openStudySetup(b.dataset.study)},true);});}
 function isMob(){const d=$('studyDescription');return !!(d&&/Tareas de movilización/i.test(d.textContent||''));}
 function standardNav(host){host.querySelector('#mobilizationStandardNavigation')?.remove();const bar=document.createElement('div');bar.id='mobilizationStandardNavigation';bar.className='actions mobilization-standard-navigation';bar.innerHTML='<button type="button" class="secondary" id="mobPrevious">Anterior</button><button type="button" class="secondary" id="mobSave">Guardar estudio</button><button type="button" class="secondary" id="mobLoad">Cargar estudio</button><button type="button" id="mobNext">Siguiente</button>';host.appendChild(bar);$('mobPrevious').onclick=()=>{try{capture();window.saveStep?.();if(window.currentStep>0){window.currentStep--;window.renderStep();}}catch(e){const x=$('error');if(x){x.textContent=e.message;x.hidden=false;}}};$('mobNext').onclick=()=>{try{capture();window.saveStep?.();const total=window.MAPO_STUDIES?.[window.selectedStudy]?.steps?.length||0;if(window.currentStep<total-1){window.currentStep++;window.renderStep();}}catch(e){const x=$('error');if(x){x.textContent=e.message;x.hidden=false;}}};$('mobSave').onclick=saveStudy;$('mobLoad').onclick=loadStudy;}
 function menu(){const h=$('formContainer');if(!h)return;h.innerHTML=`<div class="step-title-row"><h3>Tareas de movilización de pacientes</h3><p class="schedule-preview">Seleccione primero un turno y después una de las cuatro opciones. Solo se mostrará la combinación seleccionada.</p></div><div class="mobilization-navigation"><h4>Seleccione un turno</h4><div class="mobilization-turn-buttons">${TURNS.map((x,i)=>`<button type="button" class="secondary mob-turn-btn" data-turn="${i}">${x}</button>`).join('')}</div><div id="mobilizationOptions" class="mobilization-options" hidden></div></div>`;h.querySelectorAll('[data-turn]').forEach(b=>b.onclick=()=>cats(+b.dataset.turn));standardNav(h);}
 function cats(turn){state.turn=turn;state.category=null;const b=$('mobilizationOptions');if(!b)return;b.hidden=false;b.innerHTML=`<h4>Turno de ${TURNS[turn]}</h4><p>Seleccione una de las cuatro categorías.</p><div class="mobilization-option-grid">${CATS.map((c,i)=>`<button type="button" class="module-hub-item" data-cat="${i}"><strong>${c[1]}</strong><small>Turno de ${TURNS[turn]}</small></button>`).join('')}</div>`;b.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>select(turn,+x.dataset.cat));standardNav(document.getElementById('formContainer'));}
 function categoryButtons(host){host.querySelector('#mobilizationCategoryNav')?.remove();const box=document.createElement('div');box.id='mobilizationCategoryNav';box.className='mobilization-category-nav';box.innerHTML=`<div class="schedule-preview"><strong>Otras movilizaciones del turno de ${TURNS[state.turn]}</strong><div class="actions mobilization-category-actions">${CATS.map((c,i)=>`<button type="button" class="secondary ${i===state.category?'active':''}" data-mob-cat="${i}">${c[1]}</button>`).join('')}</div></div>`;host.appendChild(box);box.querySelectorAll('[data-mob-cat]').forEach(b=>b.onclick=()=>{capture();state.category=+b.dataset.mobCat;renderSelected();});}
 function select(turn,cat){capture();state.turn=turn;state.category=cat;renderSelected();}
 function renderSelected(){if(state.turn===null||state.category===null)return;const h=$('formContainer');if(!h||typeof window.renderMobilizations!=='function')return;window.renderMobilizations(CATS[state.category][0],state.turn);const title=document.createElement('div');title.className='schedule-preview mobilization-selection-title';title.innerHTML=`<strong>${CATS[state.category][1]} — turno de ${TURNS[state.turn]}</strong>`;h.insertBefore(title,h.firstChild);categoryButtons(h);const a=document.createElement('div');a.id='mobilizationSubNavigation';a.className='actions';a.innerHTML='<button type="button" class="secondary" id="selectAnotherMobilizationTurn">Seleccionar otro turno</button>';h.appendChild(a);$('selectAnotherMobilizationTurn').onclick=()=>{capture();state.turn=null;state.category=null;menu();};standardNav(h);}
 function refresh(){if(!isMob())return;if(state.turn===null||state.category===null)menu();else renderSelected();}
 function installRenderHook(){if(typeof window.renderStep!=='function'||window.renderStep.__mapoMobHook)return;const original=window.renderStep;function hooked(){original.apply(this,arguments);if(isMob())setTimeout(refresh,0);}hooked.__mapoMobHook=true;window.renderStep=hooked;}
 function init(){installStudySelection();installRenderHook();setTimeout(refresh,0);}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
 window.MAPOModuleNavigator={refresh,renderMobilizationSelector:menu,openStudySetup};
})();