(function(){
  const previousRenderStep=renderStep, previousSaveStep=saveStep;
  const PATIENT_TYPES=[
    {id:'autonomo',title:'Autónomo',text:'Realiza por sí mismo las movilizaciones necesarias y no requiere ayuda del personal para las tareas consideradas en esta evaluación.'},
    {id:'colaborador',title:'Colaborador',text:'Puede colaborar activamente en la movilización cuando se le solicita, aunque pueda necesitar ayuda del personal.'},
    {id:'noColaborador',title:'No colaborador',text:'No puede colaborar activamente en la movilización y requiere que el personal realice la movilización o la transferencia.'},
    {id:'encamado',title:'Encamado',text:'Permanece encamado y, para esta evaluación, se contabiliza además dentro de los pacientes no colaboradores.'}
  ];
  function patientData(){return formData.patientTypes||{autonomo:'',colaborador:'',noColaborador:'',encamado:''};}
  function renderPatients(){const p=patientData();return `<div class="patient-intro"><p><strong>Indique cuántos pacientes de la unidad pertenecen a cada categoría.</strong></p><p>Utilizamos únicamente estas cuatro categorías funcionales. No es necesario clasificarlos por diagnóstico, edad, hemiplejia, pluripatología u otras características clínicas.</p><button type="button" class="help-trigger" data-patient-general>?</button><div class="help-popover" id="patientGeneralHelp" hidden><strong>Cómo utilizar esta clasificación</strong><p>Seleccione la categoría por las características relevantes para la movilización. Un paciente encamado se registra únicamente en «Encamado»; el programa lo suma automáticamente a «No colaborador» para obtener NC.</p></div></div><div class="patient-list">${PATIENT_TYPES.map(x=>`<div class="patient-card"><div class="patient-card-head"><h4>${x.title}</h4><button type="button" class="help-trigger" data-patient-help="${x.id}">?</button></div><p>${x.text}</p><label>Número de pacientes<input class="patient-count" data-patient="${x.id}" type="number" min="0" step="1" value="${p[x.id]??''}"></label><div class="question-help-popover" id="patientHelp_${x.id}" hidden>${x.text}</div></div>`).join('')}</div><div id="patientTotals" class="schedule-preview"></div>`;}
  function readPatients(){const p={autonomo:'',colaborador:'',noColaborador:'',encamado:''};document.querySelectorAll('.patient-count').forEach(i=>p[i.dataset.patient]=i.value);formData.patientTypes=p;formData.nc=Number(p.noColaborador||0)+Number(p.encamado||0);formData.pc=Number(p.colaborador||0);formData.na=formData.nc+formData.pc;renderPatientTotals();}
  function renderPatientTotals(){const e=$('patientTotals');if(!e)return;const p=patientData(),a=Number(p.autonomo||0),c=Number(p.colaborador||0),n=Number(p.noColaborador||0),b=Number(p.encamado||0),nc=n+b,na=nc+c;e.innerHTML=`<h4>Resumen calculado</h4><div class="patient-summary-grid"><div><b>Autónomos</b><br>${a}</div><div><b>Colaboradores (PC)</b><br>${c}</div><div><b>No colaboradores</b><br>${n}</div><div><b>Encamados</b><br>${b}</div><div><b>NC para MAPO</b><br>${nc}</div><div><b>NA para MAPO</b><br>${na}</div></div><p class="small">Los encamados ya están incluidos en NC y no se vuelven a sumar como una categoría independiente.</p>`;}
  function bindPatientHelp(){document.querySelectorAll('[data-patient-help],[data-patient-general]').forEach(b=>b.onclick=()=>{const box=b.dataset.patientHelp?$(`patientHelp_${b.dataset.patientHelp}`):$('patientGeneralHelp');if(!box)return;const was=box.hidden;document.querySelectorAll('.help-popover,.question-help-popover').forEach(x=>x.hidden=true);box.hidden=!was;});document.querySelectorAll('.patient-count').forEach(i=>i.addEventListener('input',readPatients));}
  window.renderStep=function(){const study=MAPO_STUDIES[selectedStudy],step=study.steps[currentStep];if(step.title==='Pacientes'||step.custom==='patients'){$('studyTitle').textContent=study.title;$('studyDescription').textContent=`${study.description} · Paso ${currentStep+1} de ${study.steps.length}: Tipología de pacientes`;$('formContainer').innerHTML=renderPatients();bindPatientHelp();renderPatientTotals();$('previousStep').hidden=currentStep===0;$('nextStep').hidden=currentStep===study.steps.length-1;$('calculate').hidden=currentStep!==study.steps.length-1;$('progressBar').style.width=`${(currentStep+1)/study.steps.length*100}%`;return;}previousRenderStep();};
  window.saveStep=function(){const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(step.title==='Pacientes'||step.custom==='patients'){readPatients();return;}previousSaveStep();};
})();
