/* Corrección exclusiva de presentación de la tabla de personal. No modifica MAPO ni OP interno. */
(function(){'use strict';
 const n=v=>Number(v||0), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shifts=[['Mañana','morning'],['Tarde','afternoon'],['Noche','night']];
 function dayFactor(r){const d=r?.daysWorked;if(!d)return 5/7;if(d.type==='longshort')return 1;return Array.isArray(d.selected)?d.selected.length/7:5/7;}
 function mins(v){const m=String(v||'').match(/^(\d{1,2})(?::(\d{2}))?/);return m?Number(m[1])*60+Number(m[2]||0):NaN;}
 function overlap(a,b,c,d){let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(![s,e,p,q].every(Number.isFinite))return 0;if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best/60;}
 function build(f){const s=f.workerSchedule||{},full=Array.isArray(s.full)?s.full:[],partial=Array.isArray(s.partial)?s.partial:[],sh=s.shifts||{morning:{start:'07:00',end:'15:00'},afternoon:{start:'15:00',end:'23:00'},night:{start:'23:00',end:'07:00'}};
  let html='<div class="personnel-report"><h3>1. ENTREVISTA</h3><h4>1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP:</h4><p class="report-note"><strong>Número total de personas trabajadoras de planta.</strong></p><div class="report-table-block"><h4>Personal de planta</h4><table class="mapo-report-table"><tbody><tr><th>Número total de personas trabajadoras de planta</th><td>'+full.reduce((z,r)=>z+n(r.people),0)+'</td></tr><tr><th>Aux. enfermería</th><td>'+esc(f.auxEnfermeria??f.aux_enfermeria??'')+'</td></tr><tr><th>Aux. geriatría</th><td>'+esc(f.auxGeriatria??f.aux_geriatria??'')+'</td></tr><tr><th>Personal con limitación para MMP</th><td>'+esc(f.personalLimitacionMMP??f.personal_limitacion_mmp??f.limitacionMMP??'')+'</td></tr></tbody></table></div>';
  html+='<h4>1.1.1. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP DURANTE LOS 3 TURNOS:</h4><p class="report-note"><strong>Número de personas trabajadoras presentes en toda la duración de cada turno.</strong></p><div class="report-table-block"><h4>Personal por turnos</h4><table class="mapo-report-table"><thead><tr><th>TURNO</th><th>Nº de personas trabajadoras/Turno (A)</th><th>Horario del turno</th></tr></thead><tbody>';
  full.slice(0,3).forEach((r,i)=>{html+='<tr><td><strong>'+shifts[i][0]+'</strong></td><td>'+n(r.people)+'</td><td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td></tr>';});for(let i=full.length;i<3;i++)html+='<tr><td><strong>'+shifts[i][0]+'</strong></td><td>0</td><td></td></tr>';html+='</tbody></table></div>';
  html+='<h4>1.1.2. Nº DE PERSONAS TRABAJADORAS QUE REALIZAN MMP A TIEMPO PARCIAL:</h4><p class="report-note"><strong>Turno y horario de presencia.</strong></p><div class="report-table-block"><h4>Personal a tiempo parcial</h4><table class="mapo-report-table"><thead><tr><th>TURNO</th><th>Horario de presencia</th><th>Fracción de unidad (C)</th><th>Nº personas trabajadoras (D)</th><th>Fracción de unidad por persona trabajadora (C×D)</th></tr></thead><tbody>';
  let any=false;for(let i=0;i<3;i++){const arr=Array.isArray(partial[i])?partial[i]:(partial[i]?.entries||[]);let rows=arr.filter(r=>r&&(r.people!==''||r.start||r.end||r.fraction!=null));if(!rows.length){html+='<tr><td><strong>'+shifts[i][0]+'</strong></td><td></td><td>0.00</td><td>0</td><td>0.00</td></tr>';continue;}rows.forEach(r=>{any=true;const h=overlap(r.start,r.end,sh[shifts[i][1]]?.start,sh[shifts[i][1]]?.end),c=h/8*dayFactor(r),d=n(r.people),cd=c*d;html+='<tr><td><strong>'+shifts[i][0]+'</strong></td><td>'+esc(r.start&&r.end?r.start+'-'+r.end:'')+'</td><td>'+c.toFixed(2)+'</td><td>'+d+'</td><td>'+cd.toFixed(2)+'</td></tr>';});}html+='</tbody></table></div>';
  let op=0;try{op=window.WorkersScheduleV3?.calculate?.().OP||0;}catch(_){}if(!op)op=n(f.op);html+='<div class="report-table-block personnel-op"><table class="mapo-report-table"><tbody><tr><th>Nº TOTAL DE PERSONAS TRABAJADORAS EN 24 HORAS (Op)</th><td>'+op.toFixed(2)+'</td></tr><tr><td colspan="2">Total de personas trabajadoras/turno de todos los turnos (A) + Fracción de unidad por persona trabajadora (D), ponderadas según horas y días trabajados.</td></tr></tbody></table></div></div>';return html;}
 const original=window.MAPOReportTables?.build;if(typeof original==='function')window.MAPOReportTables.build=function(key){if(key==='workers'){const st=typeof window.MAPOReportState==='function'?window.MAPOReportState():{form:{}};return build(st.form||{});}return original(key);};
})();