/* MAPO Analyzer — navegación libre y guardado/carga local.
   El usuario puede guardar o recuperar el estudio en JSON o Excel (.xlsx).
   No usa localStorage ni servidor. No calcula MAPO ni modifica sus fórmulas. */
(function(){
  const VERSION='1.1';
  const $=id=>document.getElementById(id);
  function clearError(){const box=$('error');if(box){box.textContent='';box.hidden=true;}}
  function captureWorkerSchedule(){const s=formData.workerSchedule=formData.workerSchedule||{};s.mode=document.querySelector('input[name="workerModeV3"]:checked')?.value||s.mode||'auto';s.page=document.querySelector('[data-v3-page].active')?.dataset.v3Page||s.page||'full';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];document.querySelectorAll('[data-v3-t]').forEach(e=>{const page=e.dataset.v3T,i=Number(e.dataset.v3I),field=e.dataset.v3F,arr=page==='partial'?s.partial:s.full;arr[i]=arr[i]||{};arr[i][field]=e.value;if(field==='people'&&e.value!=='')arr[i][field]=Number(e.value);if(field==='reference'&&e.value!=='')arr[i][field]=Number(e.value);});document.querySelectorAll('[data-shift]').forEach(e=>{s.shifts=s.shifts||{};s.shifts[e.dataset.shift]=s.shifts[e.dataset.shift]||{};s.shifts[e.dataset.shift][e.dataset.f]=e.value;});}
  function captureCurrentStep(){if(!selectedStudy)return;const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(!step)return;if(step.shiftSchedule){captureWorkerSchedule();return;}if(step.custom==='mobilizations'){if(typeof readTasks==='function')readTasks();return;}if(step.questionGroup){HOSPITALIZACION_QUESTIONS[step.questionGroup].forEach(q=>{if(q.type==='yesno'){const checked=document.querySelector(`input[name="${q.id}"]:checked`);if(checked)formData[q.id]=checked.value==='true'||checked.value==='yes';else delete formData[q.id];}else{const input=$(`field_${q.id}`);if(input&&input.value.trim()!=='')formData[q.id]=Number(input.value);else delete formData[q.id];}});return;}(step.fields||[]).forEach(([id,label,type])=>{const input=$(`field_${id}`);if(!input)return;const raw=input.value.trim();if(raw==='')delete formData[id];else formData[id]=type==='number'?Number(raw):raw;});}
  function goStep(delta){try{captureCurrentStep();const total=MAPO_STUDIES[selectedStudy].steps.length;currentStep=Math.max(0,Math.min(total-1,currentStep+delta));lastResult=null;$('result').hidden=true;clearError();if(typeof renderStep==='function')renderStep();clearError();}catch(e){lastResult=null;$('result').hidden=true;clearError();if(typeof renderStep==='function')renderStep();clearError();}}
  function studySnapshot(){captureCurrentStep();return{format:'MAPO Analyzer Study',formatVersion:VERSION,savedAt:new Date().toISOString(),study:selectedStudy,currentStep,formData:JSON.parse(JSON.stringify(formData||{})),lastResult:lastResult?JSON.parse(JSON.stringify(lastResult)):null};}
  function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function safeBase(value,fallback){return(value||fallback).toString().trim().replace(/[^\wáéíóúüñÁÉÍÓÚÜÑ-]+/g,'_').slice(0,60)||fallback;}
  function studyFileBase(snapshot,fallback){const d=snapshot.formData||{};const hospital=safeBase(d.empresa,'Hospital');const sala=safeBase(d.unidad||d.sala,'Sala');const fecha=safeBase(d.fecha,'Sin_fecha');return `${hospital}_${sala}_${fecha}`.slice(0,150)||fallback;}
  function chooseFormat(title){return new Promise(resolve=>{const old=document.getElementById('mapoFormatDialog');if(old)old.remove();const box=document.createElement('div');box.id='mapoFormatDialog';box.style.cssText='position:fixed;inset:0;background:rgba(0,0,0,.42);display:flex;align-items:center;justify-content:center;z-index:99999;padding:20px;';const card=document.createElement('div');card.style.cssText='background:#fff;border-radius:12px;padding:24px;max-width:420px;width:100%;box-shadow:0 12px 40px rgba(0,0,0,.25);text-align:center;';card.innerHTML=`<h3 style="margin:0 0 10px">${title}</h3><p style="margin:0 0 18px">Seleccione el formato que desea utilizar.</p><div style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button type="button" data-format="json">JSON</button><button type="button" data-format="xlsx">Excel</button><button type="button" data-format="cancel" class="secondary">Cancelar</button></div>`;box.appendChild(card);document.body.appendChild(box);card.querySelectorAll('button').forEach(b=>b.onclick=()=>{const v=b.dataset.format;box.remove();resolve(v==='cancel'?null:v);});box.addEventListener('click',e=>{if(e.target===box){box.remove();resolve(null);}});});}
  function makeWorkbook(snapshot){if(typeof XLSX==='undefined')throw Error('La función Excel no está disponible.');const rows=[['MAPO Analyzer — estudio'],['Guardado',snapshot.savedAt],['Estudio',snapshot.study],['Paso actual',Number(snapshot.currentStep)+1],[],['DATOS DEL ESTUDIO','VALOR']];flatten(snapshot.formData).forEach(r=>rows.push(r));if(snapshot.lastResult){rows.push([],['RESULTADO','VALOR']);flatten(snapshot.lastResult).forEach(r=>rows.push(r));}const ws=XLSX.utils.aoa_to_sheet(rows);ws['!cols']=[{wch:42},{wch:80}];const json=XLSX.utils.aoa_to_sheet([[JSON.stringify(snapshot)]]);const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'Estudio');XLSX.utils.book_append_sheet(wb,json,'_MAPO_JSON');if(wb.Workbook&&Array.isArray(wb.Workbook.Sheets)){wb.Workbook.Sheets[1].Hidden=1;}return wb;}
  function saveStudy(){chooseFormat('Guardar estudio').then(format=>{if(!format)return;try{const snapshot=studySnapshot();const base=studyFileBase(snapshot,'MAPO_estudio');if(format==='json'){downloadBlob(new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json;charset=utf-8'}),`${base}.mapo.json`);}else{const wb=makeWorkbook(snapshot);XLSX.writeFile(wb,`${base}.xlsx`);}clearError();}catch(e){const box=$('error');if(box){box.textContent='No se pudo guardar el estudio: '+e.message;box.hidden=false;}}});}
  function snapshotFromWorkbook(file){if(typeof XLSX==='undefined')throw Error('La función Excel no está disponible.');return file.arrayBuffer().then(buffer=>{const wb=XLSX.read(buffer,{type:'array'});const ws=wb.Sheets['_MAPO_JSON'];if(!ws)throw Error('El Excel no contiene un estudio MAPO recuperable.');const cell=ws.A1?.v;if(!cell)throw Error('El Excel no contiene los datos internos del estudio.');return JSON.parse(String(cell));});}
  function applySnapshot(data){if(!data||data.format!=='MAPO Analyzer Study'||!data.study||!MAPO_STUDIES[data.study])throw Error('El archivo no es un estudio MAPO válido.');selectedStudy=data.study;currentStep=Math.max(0,Math.min(MAPO_STUDIES[selectedStudy].steps.length-1,Number(data.currentStep)||0));formData=data.formData&&typeof data.formData==='object'?data.formData:{};lastResult=data.lastResult||null;$('studySelection').hidden=true;$('studyPanel').hidden=false;clearError();renderStep();clearError();if(lastResult&&typeof lastResult.mapo==='number')renderLoadedResult();}
  function loadStudyFile(file){if(!file)return;const isExcel=/\.xlsx$/i.test(file.name)||file.type==='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';if(isExcel){snapshotFromWorkbook(file).then(applySnapshot).catch(e=>{const box=$('error');if(box){box.textContent='No se pudo cargar el estudio: '+e.message;box.hidden=false;}});return;}const reader=new FileReader();reader.onload=()=>{try{applySnapshot(JSON.parse(reader.result));}catch(e){const box=$('error');if(box){box.textContent='No se pudo cargar el estudio: '+e.message;box.hidden=false;}}};reader.onerror=()=>{const box=$('error');if(box){box.textContent='No se pudo leer el archivo del estudio.';box.hidden=false;}};reader.readAsText(file,'utf-8');}
  function renderLoadedResult(){if(!lastResult||typeof lastResult.mapo!=='number')return;const r=lastResult,tt=r.taskTotals||{};$('mapoValue').textContent=`MAPO = ${Number(r.mapo).toFixed(2)}`;$('classification').textContent=`Nivel de exposición: ${r.nivel||''}`;$('breakdown').innerHTML=`<p><strong>OP:</strong> ${Number(formData.op||0).toFixed(3)}</p><p><strong>ST:</strong> ${tt.st??0} · <strong>LTA:</strong> ${tt.lta??0} · <strong>SP:</strong> ${tt.sp??0} · <strong>LPA:</strong> ${tt.lpa??0}</p><p><strong>FS:</strong> ${Number(r.fs||0).toFixed(2)} · <strong>FA:</strong> ${Number(r.fa||0).toFixed(2)} · <strong>FC:</strong> ${Number(r.fc||0).toFixed(2)} · <strong>Famb:</strong> ${Number(r.famb||0).toFixed(2)} · <strong>FF:</strong> ${Number(r.ff||0).toFixed(2)}</p>`;$('result').hidden=false;}
  function flatten(obj,prefix='',out=[]){if(obj===null||obj===undefined){out.push([prefix,'']);return out;}if(typeof obj!=='object'){out.push([prefix,obj]);return out;}if(Array.isArray(obj)){obj.forEach((v,i)=>flatten(v,`${prefix}[${i}]`,out));return out;}Object.keys(obj).forEach(k=>flatten(obj[k],prefix?`${prefix}.${k}`:k,out));return out;}
  function addIOControls(){const heading=document.querySelector('#studyPanel .section-heading');if(!heading||document.getElementById('studyIO'))return;const wrap=document.createElement('div');wrap.id='studyIO';wrap.className='study-io-controls';wrap.innerHTML='<button type="button" id="saveStudy" class="secondary">Guardar estudio</button><button type="button" id="loadStudy" class="secondary">Cargar estudio</button><input id="loadStudyFile" type="file" accept=".json,.mapo.json,.xlsx,application/json,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" hidden>';heading.appendChild(wrap);$('saveStudy').onclick=saveStudy;$('loadStudy').onclick=()=>$('loadStudyFile').click();$('loadStudyFile').onchange=e=>{const f=e.target.files?.[0];if(f)loadStudyFile(f);e.target.value='';};}
  function init(){addIOControls();const next=$('nextStep'),prev=$('previousStep');if(next)next.onclick=()=>goStep(1);if(prev)prev.onclick=()=>goStep(-1);const change=$('changeStudy');if(change){const old=change.onclick;change.onclick=()=>{clearError();if(typeof old==='function')old();addIOControls();clearError();};}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.MAPOStudyIO={saveStudy,loadStudyFile,captureCurrentStep,chooseFormat};
})();
