/* MAPO Analyzer — única fuente de Guardar/Cargar estudio.
   NO registra eventos de Anterior/Siguiente: esos botones pertenecen exclusivamente a app.js. */
(function(){'use strict';
 const $=id=>document.getElementById(id);
 function clearError(){const e=$('error');if(e){e.textContent='';e.hidden=true;}}
 function captureWorkerSchedule(){const s=formData.workerSchedule=formData.workerSchedule||{};s.mode=document.querySelector('input[name="workerModeV3"]:checked')?.value||s.mode||'auto';s.page=document.querySelector('[data-v3-page].active')?.dataset.v3Page||s.page||'full';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];document.querySelectorAll('[data-v3-t]').forEach(e=>{const page=e.dataset.v3T,i=Number(e.dataset.v3I),field=e.dataset.v3F,arr=page==='partial'?s.partial:s.full;arr[i]=arr[i]||{};arr[i][field]=e.value;if((field==='people'||field==='reference')&&e.value!=='')arr[i][field]=Number(e.value);});document.querySelectorAll('[data-shift]').forEach(e=>{s.shifts=s.shifts||{};s.shifts[e.dataset.shift]=s.shifts[e.dataset.shift]||{};s.shifts[e.dataset.shift][e.dataset.f]=e.value;});}
 function captureCurrentStep(){if(!selectedStudy)return;const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(!step)return;if(step.shiftSchedule){captureWorkerSchedule();return;}if(step.custom==='mobilizations'){if(window.captureMobilizations&&window.MAPOMobilizationSelection?.turn!==null)window.captureMobilizations();else if(typeof readTasks==='function')readTasks();return;}if(step.questionGroup){HOSPITALIZACION_QUESTIONS[step.questionGroup].forEach(q=>{if(q.type==='yesno'){const c=document.querySelector(`input[name="${q.id}"]:checked`);if(c)formData[q.id]=c.value==='true'||c.value==='yes';}else{const i=$(`field_${q.id}`);if(i&&i.value.trim()!=='')formData[q.id]=Number(i.value);}});return;}(step.fields||[]).forEach(([id,,type])=>{const i=$(`field_${id}`);if(!i)return;const raw=i.value.trim();if(raw==='')return;formData[id]=type==='number'?Number(raw):raw;});}
 function snapshot(){captureCurrentStep();return{format:'MAPO Analyzer Study',savedAt:new Date().toISOString(),study:selectedStudy,currentStep,formData:JSON.parse(JSON.stringify(formData||{})),lastResult:lastResult?JSON.parse(JSON.stringify(lastResult)):null};}
 async function saveJson(data,suggestedName='MAPO_estudio.json'){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});if('showSaveFilePicker' in window){const handle=await window.showSaveFilePicker({suggestedName,types:[{description:'Estudio MAPO (JSON)',accept:{'application/json':['.json']}}]});const w=await handle.createWritable();await w.write(blob);await w.close();return;}const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=suggestedName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function loadStudyFile(file){if(!file)return;try{if(window.MAPOMultiRoom?.loadMultiStudyFile){await window.MAPOMultiRoom.loadMultiStudyFile(file);return;}const data=JSON.parse(await file.text());if(!data||data.format!=='MAPO Analyzer Study'||!data.study||!MAPO_STUDIES[data.study])throw Error('El archivo no es un estudio MAPO válido.');selectedStudy=data.study;currentStep=Math.max(0,Math.min(MAPO_STUDIES[selectedStudy].steps.length-1,Number(data.currentStep)||0));formData=data.formData&&typeof data.formData==='object'?data.formData:{};lastResult=data.lastResult||null;$('studySelection').hidden=true;$('studyPanel').hidden=false;clearError();renderStep();}catch(e){const b=$('error');if(b){b.textContent='No se pudo cargar el estudio: '+e.message;b.hidden=false;}}}
 function normalizeFileInputs(){['loadStudyFile','loadMultiStudyFile'].forEach(id=>{const e=$(id);if(e)e.accept='.json,application/json';});}
 function addIOControls(){
   const bar=$('legacyStepActions');if(!bar||$('studyIO'))return;
   const w=document.createElement('span');w.id='studyIO';w.className='study-io-controls';
   w.innerHTML='<button type="button" id="saveStudy" class="secondary">Guardar estudio</button><button type="button" id="loadStudy" class="secondary">Cargar estudio</button><input id="loadStudyFile" type="file" accept=".json,application/json" hidden>';
   bar.insertBefore(w,bar.firstChild);
   $('saveStudy').onclick=async()=>{try{if(window.MAPOMultiRoom?.saveMultiStudy){await window.MAPOMultiRoom.saveMultiStudy();return;}await saveJson(snapshot(),'MAPO_estudio.json');}catch(e){if(e?.name==='AbortError')return;const b=$('error');if(b){b.textContent='No se pudo guardar el estudio: '+e.message;b.hidden=false;}}};
   $('loadStudy').onclick=()=>$('loadStudyFile').click();
   $('loadStudyFile').onchange=e=>{const f=e.target.files?.[0];if(f)loadStudyFile(f);e.target.value='';};
 }
 function init(){normalizeFileInputs();addIOControls();}
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
 window.MAPOStudyIO={saveJson,loadStudyFile,captureCurrentStep,chooseFormat:()=>Promise.resolve('json')};
})();