/* Definición de los tres estudios MAPO. Los modelos documentales son independientes. */
const MAPO_HELP={fs:{title:'¿Cómo se determina FS?',html:'<p>El programa comprueba la suficiencia del equipamiento y su adecuación. Para adecuación, el criterio es que al menos el 90% de las tareas de levantamiento total se realicen con equipamiento de ayuda.</p>'},fa:{title:'¿Cómo se determina FA?',html:'<p>El programa comprueba la suficiencia de las ayudas menores y su adecuación. Para adecuación, el criterio es que al menos el 90% de las tareas de levantamiento parcial se realicen con ayudas.</p>'},fc:{title:'¿Cómo se determina FC?',html:'<p>El programa obtiene la PMSR a partir de las características puntuables de las sillas y comprueba la suficiencia numérica.</p>'},famb:{title:'¿Cómo se determina Famb?',html:'<p>El programa obtiene PMB, PMWC y PMH y calcula PMamb = PMB + PMWC + PMH.</p>'},ff:{title:'¿Cómo se determina FF?',html:'<p>El programa determina FF a partir de las características del curso, duración, práctica, organización, cobertura, antigüedad y eficacia cuando corresponda.</p>'}};
const MAPO_STUDIES={
 hospitalizacion:{title:'Salas de hospitalización',description:'Evaluación de riesgo MAPO en unidades de hospitalización.',templateKey:'hospitalizacion',steps:[
  {title:'Identificación de la unidad',fields:[['empresa','Hospital / empresa','text'],['unidad','Sala / unidad','text'],['fecha','Fecha de evaluación','date'],['codigo','Código de sala','text'],['camas','Número de camas','number']]},
  {title:'Personas trabajadoras que realizan MMP',shiftSchedule:true},
  {title:'Pacientes',fields:[['nc','Número de pacientes no colaboradores (NC)','number'],['pc','Número de pacientes parcialmente colaboradores (PC)','number']]},
  {title:'Factor de elevación (FS)',helpKey:'fs',questionGroup:'fs'},
  {title:'Factor de ayudas menores (FA)',helpKey:'fa',questionGroup:'fa'},
  {title:'Factor de sillas de ruedas (FC)',helpKey:'fc',questionGroup:'fc'},
  {title:'Factor ambiente — baños',helpKey:'famb',fields:[['famb_pmb','Puntuación media de baños para higiene (PMB)','number'],['famb_pmwc','Puntuación media de baños con WC (PMWC)','number']]},
  {title:'Habitaciones — cálculo de PMH',custom:'pmh'},
  {title:'Factor formación (FF)',helpKey:'ff',questionGroup:'ff'}
 ]},
 ambulatorio:{title:'Servicios ambulatorios',description:'Evaluación MAPO específica para servicios ambulatorios.',templateKey:'ambulatorio',steps:[{title:'Identificación',fields:[['empresa','Hospital / empresa','text'],['servicio','Servicio ambulatorio','text'],['fecha','Fecha de evaluación','date'],['codigo','Código','text']]},{title:'Evaluación del servicio',fields:[['op','Personas trabajadoras que realizan MMP','number'],['nc','Pacientes no colaboradores','number'],['pc','Pacientes parcialmente colaboradores','number']]},{title:'Factores del modelo',fields:[['nota','Los factores específicos del modelo ambulatorio se determinarán a partir de las condiciones observables de su ficha.','text']]}]},
 quirurgica:{title:'Área quirúrgica',description:'Evaluación MAPO específica del área quirúrgica.',templateKey:'quirurgica',steps:[{title:'Identificación',fields:[['empresa','Hospital / empresa','text'],['area','Área quirúrgica','text'],['fecha','Fecha de evaluación','date'],['codigo','Código','text']]},{title:'Organización e intervenciones',fields:[['op','Personas trabajadoras que realizan MMP','number'],['intervencionesDia','Intervenciones por día','number'],['intervencionesMovilizacion','Intervenciones por día que requieren movilización','number']]},{title:'Factores del modelo',fields:[['nota','Los factores específicos del modelo quirúrgico se determinarán a partir de las condiciones observables de su ficha.','text']]}]}
};

const HOSPITALIZACION_QUESTIONS={fs:[
{id:'fs_elevadores',label:'¿Hay al menos 1 elevador utilizable por cada 8 pacientes no colaboradores (NC)?',help:'Cuente únicamente los elevadores utilizables para la elevación total y compare su número con NC/8.',type:'yesno'},
{id:'fs_camillas',label:'¿Hay al menos 1 camilla regulable por cada 8 pacientes NC y, cuando se utiliza para la transferencia cama-camilla, se acompaña de tabla, sábana deslizante, rollboard o equivalente?',help:'Solo marque Sí si se cumplen las dos condiciones simultáneamente.',type:'yesno'},
{id:'fs_camas3',label:'¿Las camas regulables en altura con 3 nodos están disponibles para el 100% de los pacientes de la unidad?',help:'La suficiencia se cumple si esta condición es cierta para toda la unidad.',type:'yesno'},
{id:'fs_lta_total',label:'Número de levantamientos totales realizados con equipamiento de ayuda',help:'Incluya las tareas de levantamiento total realizadas con equipamiento de ayuda.',type:'number'},
{id:'fs_st_total',label:'Número total de levantamientos totales evaluados',help:'Incluya todas las tareas de levantamiento total consideradas en la evaluación.',type:'number'}],
fa:[
{id:'fa_sabana',label:'¿Hay sábana o tabla deslizante disponible?',help:'La presencia de sábana o tabla deslizante es una condición de suficiencia.',type:'yesno'},
{id:'fa_dos',label:'¿Hay además al menos dos de las otras ayudas menores indicadas en la ficha?',help:'Considere las ayudas menores indicadas en la ficha. La grúa de bipedestación/elevador de banda torácica se considera equivalente al cinturón ergonómico.',type:'yesno'},
{id:'fa_camas3',label:'¿Todas las camas de la unidad son regulables en altura y tienen 3 nodos de articulación?',help:'Es la segunda vía de suficiencia junto con la sábana/tabla deslizante.',type:'yesno'},
{id:'fa_lpa_total',label:'Número de levantamientos parciales realizados con equipamiento de ayuda',help:'Cuente los levantamientos parciales realizados con ayudas menores.',type:'number'},
{id:'fa_sp_total',label:'Número total de levantamientos parciales evaluados',help:'Incluya todas las tareas de levantamiento parcial consideradas.',type:'number'}],
fc:[
{id:'fc_sillas',label:'Número total de sillas de ruedas disponibles y utilizables',help:'Cuente las sillas disponibles para las movilizaciones.',type:'number'},
{id:'fc_na',label:'Número de pacientes no autónomos (NA)',help:'NA corresponde a NC + PC para esta evaluación.',type:'number'},
{id:'fc_pmsr',label:'Puntuación media de inadecuación de las sillas (PMSR)',help:'Este dato seguirá siendo provisional hasta completar el registro detallado de características de cada tipo de silla.',type:'number'}],
ff:[
{id:'ff_curso',label:'¿La formación fue un curso teórico-práctico de al menos 6 horas, organizado por el propio centro y con práctica específica en el uso de equipos de ayuda?',help:'Estas son las características del curso adecuado.',type:'yesno'},
{id:'ff_cobertura',label:'¿Qué porcentaje de las personas trabajadoras que realizan manipulación de pacientes recibió el curso adecuado?',help:'Introduzca el porcentaje de plantilla cubierta.',type:'number'},
{id:'ff_antiguedad',label:'¿La formación se realizó hace menos de 2 años respecto a esta evaluación?',help:'Si fue hace más de dos años, se contempla valorar la verificación de eficacia.',type:'yesno'},
{id:'ff_eficacia',label:'Si la formación tiene más de 2 años, ¿se ha verificado su eficacia?',help:'Solo se utiliza cuando la formación tiene más de dos años.',type:'yesno'},
{id:'ff_informacion',label:'Si no existe curso adecuado, ¿se realizó información/adiestramiento o se distribuyó material informativo al 90% de la plantilla y se verificó su eficacia?',help:'Condición específica que puede dar FF=1.',type:'yesno'}]};
function _yes(d,id){return d[id]===true||d[id]==='yes';}function _num(d,id){return Number(d[id]||0);}
function calculateHospitalizacionFactors(d){const fsS=_yes(d,'fs_elevadores')||_yes(d,'fs_camillas')||_yes(d,'fs_camas3'),st=_num(d,'fs_st_total'),lta=_num(d,'fs_lta_total');if(lta>st)throw Error('Los levantamientos totales con ayuda no pueden superar el total.');const fsA=st>0&&lta/st>=.9,fs=!fsS&&!fsA?4:fsS&&fsA?.5:2;const faS=(_yes(d,'fa_sabana')&&_yes(d,'fa_dos'))||(_yes(d,'fa_sabana')&&_yes(d,'fa_camas3')),sp=_num(d,'fa_sp_total'),lpa=_num(d,'fa_lpa_total');if(lpa>sp)throw Error('Los levantamientos parciales con ayuda no pueden superar el total.');const faA=sp>0&&lpa/sp>=.9,fa=faS&&faA?.5:1;const na=_num(d,'fc_na'),chairs=_num(d,'fc_sillas'),pmsr=_num(d,'fc_pmsr'),fcS=chairs>=na*.5;let fc;if(pmsr<=1.33)fc=fcS?.75:1;else if(pmsr<=2.66)fc=fcS?1.12:1.5;else fc=fcS?1.5:2;const pmb=_num(d,'famb_pmb'),pmwc=_num(d,'famb_pmwc'),pmh=_num(d,'famb_pmh'),pmamb=pmb+pmwc+pmh,famb=pmamb<=5.8?.75:pmamb<=11.6?1.25:1.5;const course=_yes(d,'ff_curso'),cov=_num(d,'ff_cobertura'),recent=_yes(d,'ff_antiguedad'),eff=_yes(d,'ff_eficacia'),info=_yes(d,'ff_informacion');const ff=(course&&cov>=75&&(recent||eff))?.75:(course&&cov>=50&&cov<75&&recent)||info?1:2;return{fs,fa,fc,famb,ff,details:{fsSufficient:fsS,fsAdequate:fsA,faSufficient:faS,faAdequate:faA,fcSufficient:fcS,pmsr,pmamb,ff}};}
