/* Definición de los tres estudios MAPO. Los modelos documentales son independientes. */
const MAPO_HELP={fs:{title:'¿Cómo se determina FS?',html:'<p>El programa comprueba la suficiencia del equipamiento y su adecuación. Para adecuación, el criterio es que al menos el 90% de las tareas de levantamiento total se realicen con equipamiento de ayuda.</p>'},fa:{title:'¿Cómo se determina FA?',html:'<p>El programa comprueba la suficiencia de las ayudas menores y su adecuación. Para adecuación, el criterio es que al menos el 90% de las tareas de levantamiento parcial se realicen con ayudas.</p>'},fc:{title:'¿Cómo se determina FC?',html:'<p>El programa obtiene la PMSR a partir de las características puntuables de las sillas y comprueba la suficiencia numérica.</p>'},famb:{title:'¿Cómo se determina Famb?',html:'<p>El programa obtiene PMB, PMWC y PMH y calcula PMamb = PMB + PMWC + PMH.</p>'},ff:{title:'¿Cómo se determina FF?',html:'<p>El programa determina FF a partir de las características del curso, duración, práctica, organización, cobertura, antigüedad y eficacia cuando corresponda.</p>'}};
const MAPO_STUDIES={
 hospitalizacion:{title:'Salas de hospitalización',description:'Evaluación de riesgo MAPO en unidades de hospitalización.',templateKey:'hospitalizacion',steps:[
  {title:'Identificación de la unidad',fields:[['empresa','Hospital / empresa','text'],['unidad','Sala / unidad','text'],['fecha','Fecha de evaluación','date'],['codigo','Código de sala','text'],['camas','Número de camas','number']]},
  {title:'Personas trabajadoras que realizan MMP',shiftSchedule:true},
  {title:'Pacientes',fields:[['nc','Número de pacientes no colaboradores (NC)','number'],['pc','Número de pacientes parcialmente colaboradores (PC)','number']]},
  {title:'Factor de elevación (FS)',helpKey:'fs',questionGroup:'fs'},
  {title:'Factor de ayudas menores (FA)',helpKey:'fa',questionGroup:'fa'},
  {title:'Factor de sillas de ruedas (FC)',helpKey:'fc',questionGroup:'fc'},
  {title:'Factor ambiente — baños',helpKey:'famb',fields:[['famb_pmb','Puntuación media de baños para higiene (PMB)','number'],['famb_pmwc','Puntuación media de baños con WC (PMWC)','number']]},
  {title:'Habitaciones — cálculo de PMH',custom:'pmh'},
  {title:'Factor formación (FF)',helpKey:'ff',questionGroup:'ff'}
 ]},
 ambulatorio:{title:'Servicios ambulatorios',description:'Evaluación MAPO específica para servicios ambulatorios.',templateKey:'ambulatorio',steps:[{title:'Identificación',fields:[['empresa','Hospital / empresa','text'],['servicio','Servicio ambulatorio','text'],['fecha','Fecha de evaluación','date'],['codigo','Código','text']]},{title:'Evaluación del servicio',fields:[['op','Personas trabajadoras que realizan MMP','number'],['nc','Pacientes no colaboradores','number'],['pc','Pacientes parcialmente colaboradores','number']]},{title:'Factores del modelo',fields:[['nota','Los factores específicos del modelo ambulatorio se determinarán a partir de las condiciones observables de su ficha.','text']]}]},
 quirurgica:{title:'Área quirúrgica',description:'Evaluación MAPO específica del área quirúrgica.',templateKey:'quirurgica',steps:[{title:'Identificación',fields:[['empresa','Hospital / empresa','text'],['area','Área quirúrgica','text'],['fecha','Fecha de evaluación','date'],['codigo','Código','text']]},{title:'Organización e intervenciones',fields:[['op','Personas trabajadoras que realizan MMP','number'],['intervencionesDia','Intervenciones por día','number'],['intervencionesMovilizacion','Intervenciones por día que requieren movilización','number']]},{title:'Factores del modelo',fields:[['nota','Los factores específicos del modelo quirúrgico se determinarán a partir de las condiciones observables de su ficha.','text']]}]}
};
