/* MAPO Analyzer — guardado y recuperación local en JSON. */
(function(){
  const $=id=>document.getElementById(id);
  function clearError(){const e=$('error');if(e){e.textContent='';e.hidden=true;}}
  function captureWorkerSchedule(){const s=formData.workerSchedule=formData.workerSchedule||{};s.mode=document.querySelector('input[name="workerModeV3"]:checked')?.value||s.mode||'auto';s.page=document.querySelector('[data-v3-page].active')?.dataset.v3Page||s.page||'full';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];document.querySelectorAll('[data-v3-t]').forEach(e=>{const page=e.dataset.v3T,i=Number(e.dataset.v3I),field=e.dataset.v3F,arr=page==='partial'?s.partial:s.full;arr[i]=arr[i]||{};arr[i][field]=e.value;if(field==='people'&&e.value!=='')arr[i][field]=Number(e.value);if(field==='reference'&&e.value!=='')arr[i][field]=Number(e.value);});document.querySelectorAll('[data-shift]').forEach(e=>{s.shifts=s.shifts||{};s.shifts[e.dataset.shift]=s.shifts[e.dataset.shift]||{};s.shifts[e.dataset.shift][e.dataset.f]=e.value;});}
  function captureCurrentStep(){if(!selectedStudy)return;const step=MAPO_STUDIES[selectedStudy].steps[currentStep];if(!step)return;if(step.shiftSchedule){captureWorkerSchedule();return;}if(step.custom==='mobilizations'){if(typeof readTasks==='function')readTasks();return;}if(step.questionGroup){HOSPITALIZACION_QUESTIONS[step.questionGroup].forEach(q=>{if(q.type==='yesno'){const c=document.querySelector(`input[name="${q.id}"]:checked`);if(c)formData[q.id]=c.value==='true'||c.value==='yes';else delete formData[q.id];}else{const i=$(`field_${q.id}`);if(i&&i.value.trim()!=='')formData[q.id]=Number(i.value);else delete formData[q.id];}});return;}(step.fields||[]).forEach(([id,,type])=>{const i=$(`field_${id}`);if(!i)return;const raw=i.value.trim();if(raw==='')delete formData[id];else formData[id]=type==='number'?Number(raw):raw;});}
  function snapshot(){captureCurrentStep();return{format:'MAPO Analyzer Study',savedAt:new Date().toISOString(),study:selectedStudy,currentStep,formData:JSON.parse(JSON.stringify(formData||{})),lastResult:lastResult?JSON.parse(JSON.stringify(lastResult)):null};}
  async function saveJson(data,suggestedName){const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'});if('showSaveFilePicker' in window){const handle=await window.showSaveFilePicker({suggestedName,types:[{description:'Estudio MAPO (JSON)',accept:{'application/json':['.json']}}]});const writable=await handle.createWritable();await writable.write(blob);await writable.close();return;}const a=document.createElement('a');const url=URL.createObjectURL(blob);a.href=url;a.download=suggestedName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function applySnapshot(data){if(!data||data.format!=='MAPO Analyzer Study'||!data.study||!MAPO_STUDIES[data.study])throw Error('El archivo no es un estudio MAPO válido.');selectedStudy=data.study;currentStep=Math.max(0,Math.min(MAPO_STUDIES[selectedStudy].steps.length-1,Number(data.currentStep)||0));formData=data.formData&&typeof data.formData==='object'?data.formData:{};lastResult=data.lastResult||null;$('studySelection').hidden=true;$('studyPanel').hidden=false;clearError();renderStep();if(lastResult&&typeof lastResult.mapo==='number')renderLoadedResult();}
  async function loadStudyFile(file){if(!file)return;try{if(window.MAPOMultiRoom?.loadMultiStudyFile){await window.MAPOMultiRoom.loadMultiStudyFile(file);return;}applySnapshot(JSON.parse(await file.text()));}catch(e){const b=$('error');if(b){b.textContent='No se pudo cargar el estudio: '+e.message;b.hidden=false;}}}
  function chooseFormat(){return Promise.resolve('json');}
  function normalizeFileInputs(){['loadStudyFile','loadMultiStudyFile'].forEach(id=>{const e=$(id);if(e)e.accept='.json,application/json';});}
  function addIOControls(){const h=document.querySelector('#studyPanel .section-heading');if(!h||document.getElementById('studyIO'))return;const w=document.createElement('div');w.id='studyIO';w.className='study-io-controls';w.innerHTML='<button type="button" id="saveStudy" class="secondary">Guardar estudio</button><button type="button" id="loadStudy" class="secondary">Cargar estudio</button><input id="loadStudyFile" type="file" accept=".json,application/json" hidden>';h.appendChild(w);$('saveStudy').onclick=async()=>{try{if(window.MAPOMultiRoom?.saveMultiStudy){await window.MAPOMultiRoom.saveMultiStudy();return;}await saveJson(snapshot(),'MAPO_estudio.json');}catch(e){const b=$('error');if(b){b.textContent='No se pudo guardar el estudio: '+e.message;b.hidden=false;}}};$('loadStudy').onclick=()=>$('loadStudyFile').click();$('loadStudyFile').onchange=e=>{const f=e.target.files?.[0];if(f)loadStudyFile(f);e.target.value='';};}
  function goStep(d){try{captureCurrentStep();const total=MAPO_STUDIES[selectedStudy].steps.length;currentStep=Math.max(0,Math.min(total-1,currentStep+d));lastResult=null;$('result').hidden=true;clearError();renderStep();}catch(e){clearError();renderStep();}}
  function init(){normalizeFileInputs();addIOControls();$('nextStep')?.addEventListener('click',()=>goStep(1));$('previousStep')?.addEventListener('click',()=>goStep(-1));}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
  window.MAPOStudyIO={saveJson,loadStudyFile,captureCurrentStep,chooseFormat};
})();
