/* Registro de sillas de ruedas para FC/PMSR en Hospitalización. */
const WHEELCHAIR_PREDEFINED = [
  {id:'large_wheel', name:'Rueda grande', source:'Predefinida'},
  {id:'small_wheel', name:'Rueda pequeña', source:'Predefinida'},
  {id:'shower_bath', name:'Silla de ducha/baño', source:'Predefinida'},
  {id:'electric', name:'Silla eléctrica', source:'Predefinida'},
  {id:'tilt', name:'Silla basculante', source:'Predefinida'}
];
const WHEELCHAIR_COMMON = [
  {id:'manual_transit', name:'Manual no autopropulsable / de tránsito', source:'Común'},
  {id:'manual_self', name:'Manual autopropulsable', source:'Común'},
  {id:'manual_light', name:'Manual ligera', source:'Común'},
  {id:'manual_bariatric', name:'Manual bariátrica', source:'Común'},
  {id:'manual_reclining', name:'Manual con respaldo reclinable', source:'Común'},
  {id:'pediatric', name:'Silla pediátrica', source:'Común'}
];
const WHEELCHAIR_MAX_CUSTOM = 20;
function emptyWheelchair(){return {count:0,brakes:false,arms:false,back:false,width:false};}
function wheelchairData(){if(!formData.wheelchairs)formData.wheelchairs={entries:{},custom:[]};return formData.wheelchairs;}
function wheelchairAllTypes(){const d=wheelchairData();return [...WHEELCHAIR_PREDEFINED,...WHEELCHAIR_COMMON,...d.custom.map((x,i)=>({...x,id:x.id||`wc_custom_${i}`,source:'Personalizada'}))];}
function wheelchairRow(t){const d=wheelchairData(),e=d.entries[t.id]||emptyWheelchair();return `<tr data-wc-id="${t.id}"><td><strong>${t.name}</strong><small class="mob-source">${t.source}</small></td><td><input class="wc-count" type="number" min="0" step="1" value="${e.count||0}"></td><td><label><input class="wc-criterion" data-c="brakes" type="checkbox" ${e.brakes?'checked':''}> Adecuados</label></td><td><label><input class="wc-criterion" data-c="arms" type="checkbox" ${e.arms?'checked':''}> Adecuados</label></td><td><label><input class="wc-criterion" data-c="back" type="checkbox" ${e.back?'checked':''}> Adecuado</label></td><td><label><input class="wc-criterion" data-c="width" type="checkbox" ${e.width?'checked':''}> Adecuada</label></td><td class="wc-score">0</td></tr>`;}
function wheelchairCustomRow(t,i){const d=wheelchairData(),e=d.entries[t.id]||emptyWheelchair();return `<tr data-wc-id="${t.id}" data-custom="true"><td><input class="wc-custom-name" data-custom-index="${i}" value="${t.name||''}" placeholder="Describa el tipo de silla"><small class="mob-source">Personalizada</small></td><td><input class="wc-count" type="number" min="0" step="1" value="${e.count||0}"></td><td><label><input class="wc-criterion" data-c="brakes" type="checkbox" ${e.brakes?'checked':''}> Adecuados</label></td><td><label><input class="wc-criterion" data-c="arms" type="checkbox" ${e.arms?'checked':''}> Adecuados</label></td><td><label><input class="wc-criterion" data-c="back" type="checkbox" ${e.back?'checked':''}> Adecuado</label></td><td><label><input class="wc-criterion" data-c="width" type="checkbox" ${e.width?'checked':''}> Adecuada</label></td><td><button type="button" class="secondary wc-remove" data-index="${i}">Eliminar</button></td></tr>`;}
function captureWheelchairs(){const d=wheelchairData();document.querySelectorAll('[data-wc-id]').forEach(r=>{const id=r.dataset.wcId;d.entries[id]??=emptyWheelchair();const e=d.entries[id];e.count=Math.max(0,Math.floor(Number(r.querySelector('.wc-count')?.value||0)));r.querySelectorAll('.wc-criterion').forEach(c=>e[c.dataset.c]=c.checked);if(r.dataset.custom==='true'){const i=Number(r.querySelector('.wc-custom-name')?.dataset.customIndex);if(Number.isInteger(i)&&d.custom[i])d.custom[i].name=r.querySelector('.wc-custom-name').value.trim();}});return d;}
function renderWheelchairs(){const d=wheelchairData();const all=[...WHEELCHAIR_PREDEFINED,...WHEELCHAIR_COMMON];$('formContainer').innerHTML=`<div class="step-title-row"><h3>Tipos de sillas de ruedas</h3><button type="button" class="help-trigger" id="wcHelpBtn">?</button><div class="help-popover" id="wcHelp" hidden><strong>Cómo registrar las sillas</strong><p>Seleccione todos los tipos que existan en la unidad e indique cuántas unidades utilizables hay de cada uno. Los tipos predefinidos y los tipos adicionales sirven para describir la flota real.</p><p>Para cada tipo indique si los frenos, reposabrazos, respaldo y anchura cumplen las condiciones de adecuación de la ficha MAPO. El programa asigna 1 punto por cada característica inadecuada y calcula PMSR como media ponderada por el número de sillas.</p><p>Los tipos predefinidos, los tipos comunes y los tipos personalizados <strong>se incluyen todos en el cálculo</strong>. No se excluye una categoría por no ser una categoría nominal de la ficha.</p></div></div><p>Puede registrar varios tipos de silla. No introduzca PMSR manualmente.</p><div class="wheelchair-table-wrap"><table class="wheelchair-table"><thead><tr><th>Tipo</th><th>Nº unidades</th><th>Frenos</th><th>Reposabrazos</th><th>Respaldo</th><th>Anchura</th><th>Puntuación</th></tr></thead><tbody><tr class="mob-section"><td colspan="7">Tipos predefinidos</td></tr>${WHEELCHAIR_PREDEFINED.map(wheelchairRow).join('')}<tr class="mob-section"><td colspan="7">Tipos comunes adicionales</td></tr>${WHEELCHAIR_COMMON.map(wheelchairRow).join('')}<tr class="mob-section"><td colspan="7">Otros tipos definidos por el usuario</td></tr>${d.custom.length?d.custom.map(wheelchairCustomRow).join(''):'<tr><td colspan="7" class="small">Ninguno.</td></tr>'}</tbody></table></div><div class="actions"><button type="button" id="addCustomWheelchair">+ Añadir otro tipo de silla</button></div><div id="wcSummary" class="schedule-preview"></div>`;bindWheelchairs();updateWheelchairSummary();}
function bindWheelchairs(){document.querySelectorAll('.wc-count,.wc-criterion,.wc-custom-name').forEach(i=>i.addEventListener('input',()=>{captureWheelchairs();updateWheelchairSummary();}));$('wcHelpBtn').onclick=()=>{$('wcHelp').hidden=!$('wcHelp').hidden;};document.querySelectorAll('.wc-remove').forEach(b=>b.onclick=()=>{captureWheelchairs();wheelchairData().custom.splice(Number(b.dataset.index),1);renderWheelchairs();});$('addCustomWheelchair').onclick=()=>{captureWheelchairs();const d=wheelchairData();if(d.custom.length>=WHEELCHAIR_MAX_CUSTOM){$('error').textContent=`Máximo de ${WHEELCHAIR_MAX_CUSTOM} tipos personalizados.`;$('error').hidden=false;return;}const id=`wc_custom_${Date.now()}_${d.custom.length}`;d.custom.push({id,name:''});d.entries[id]=emptyWheelchair();renderWheelchairs();};}
function wheelchairTotals(){const d=captureWheelchairs(),types=wheelchairAllTypes();let total=0,points=0;types.forEach(t=>{const e=d.entries[t.id]||emptyWheelchair(),score=(e.brakes?0:1)+(e.arms?0:1)+(e.back?0:1)+(e.width?0:1);if(e.count>0){total+=e.count;points+=e.count*score;const row=document.querySelector(`[data-wc-id="${CSS.escape(t.id)}"]`);if(row)row.querySelector('.wc-score').textContent=score;}});return{total,points,pmsr:total?points/total:0};}
function updateWheelchairSummary(){const r=wheelchairTotals(),na=num(formData.nc)+num(formData.pc),sufficient=r.total>=na*.5;const e=$('wcSummary');if(e)e.innerHTML=`<strong>Resultados automáticos</strong> · Sillas utilizables = <b>${r.total}</b> · PMSR = <b>${r.pmsr.toFixed(2)}</b> · Suficiencia frente a NA = <b>${sufficient?'Sí':'No'}</b> (criterio: ≥50% de NA = ${Math.ceil(na*.5)})`;}
function validateWheelchairs(){const r=wheelchairTotals();if(r.total<=0)throw Error('Debe registrar al menos una silla de ruedas utilizable.');return r;}
window.renderWheelchairs=renderWheelchairs;window.validateWheelchairs=validateWheelchairs;window.wheelchairTotals=wheelchairTotals;
/* Exportación del catálogo para módulos de informe. No modifica la pantalla ni el cálculo. */
window.WHEELCHAIR_PREDEFINED=WHEELCHAIR_PREDEFINED;
window.WHEELCHAIR_COMMON=WHEELCHAIR_COMMON;
