/* MAPO Hospitalización — motor canónico de horarios y personas trabajadoras MMP.
 * Este es el ÚNICO punto de verdad del módulo de trabajadores/horarios.
 */
(function(){
'use strict';
const MAX=50, INITIAL=5, MAX_CUSTOM_DAYS=7;
const ALL_DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const DAY_OPTIONS={weekdays:{label:'Lunes a viernes',days:['Lunes','Martes','Miércoles','Jueves','Viernes']},weekend:{label:'Sábado y domingo',days:['Sábado','Domingo']},longshort:{label:'Semana larga/semana corta',days:[...ALL_DAYS]}};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const defaultDays=()=>({type:'weekdays',selected:[...DAY_OPTIONS.weekdays.days]});
const normalizeDays=r=>{if(!r.daysWorked)r.daysWorked=defaultDays();if(!Array.isArray(r.daysWorked.selected))r.daysWorked.selected=[...DAY_OPTIONS.weekdays.days];if(r.daysWorked.type==='longweek'||r.daysWorked.type==='shortweek')r.daysWorked={type:'longshort',selected:[...ALL_DAYS]};if(r.daysWorked.type!=='custom'&&!DAY_OPTIONS[r.daysWorked.type])r.daysWorked.type='weekdays';if(r.daysWorked.type==='custom')r.daysWorked.selected=r.daysWorked.selected.slice(0,MAX_CUSTOM_DAYS);return r.daysWorked;};
const dayFactor=r=>Math.max(0,Math.min(1,(normalizeDays(r).selected||[]).length/7));
const dayLabel=r=>{const d=normalizeDays(r);if(d.type==='custom')return d.selected.length?d.selected.join(', '):'Sin días seleccionados';return DAY_OPTIONS[d.type]?.label||'Lunes a viernes';};
const state=()=>{window.formData=window.formData||{};const s=window.formData.workerSchedule=window.formData.workerSchedule||{};s.page=s.page||'full';s.mode=s.mode||'manual';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];s.shifts=s.shifts||{morning:{start:'06:00',end:'14:00'},afternoon:{start:'14:00',end:'22:00'},night:{start:'22:00',end:'06:00'}};if(!Object.prototype.hasOwnProperty.call(s,'fullInitialized')){s.fullInitialized=true;if(!s.full.length)for(let i=0;i<INITIAL;i++)s.full.push({start:'',end:'',people:'',label:'',daysWorked:defaultDays()});}if(!Object.prototype.hasOwnProperty.call(s,'partialInitialized')){s.partialInitialized=true;if(!s.partial.length)for(let i=0;i<INITIAL;i++)s.partial.push({start:'',end:'',people:'',reference:0,label:'',daysWorked:defaultDays()});}s.full.forEach(normalizeDays);s.partial.forEach(normalizeDays);return s;};
const mins=t=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t||''))throw Error('Hora no válida. Use formato 24 h (HH:MM).');const [h,m]=t.split(':').map(Number);return h*60+m;};
const dur=(a,b)=>{let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x;};
const overlap=(a,b,c,d)=>{let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best;};
function saveInputs(){const s=state();document.querySelectorAll('[data-v3-t]').forEach(e=>{const a=s[e.dataset.v3T],i=Number(e.dataset.v3I),f=e.dataset.v3F;if(!a[i])a[i]={};a[i][f]=e.type==='number'?(e.value===''?'':Number(e.value)):e.value;});document.querySelectorAll('[data-shift]').forEach(e=>{s.shifts[e.dataset.shift][e.dataset.f]=e.value;});}
function reference(full){let best=-1;full.forEach((r,i)=>{if(best<0){best=i;return;}const b=full[best],h=dur(r.start,r.end),bh=dur(b.start,b.end);if(h>bh||(h===bh&&Number(r.people||0)>Number(b.people||0)))best=i;});return best;}
function calculate(){const s=state(),full=s.full.filter(r=>r.start&&r.end&&Number(r.people||0)>0),partial=s.partial.filter(r=>r.start&&r.end&&Number(r.people||0)>0);const A=full.reduce((x,r)=>x+Number(r.people||0)*dayFactor(r),0);const ref=full.length?reference(full):-1;const rw=ref>=0?full[ref]:null;const rh=rw?dur(rw.start,rw.end):0;const D=partial.reduce((x,r)=>x+(rh?Number(r.people||0)*(dur(r.start,r.end)/rh)*dayFactor(r):0),0);const rows=[['Mañana','morning'],['Tarde','afternoon'],['Noche','night']].map(([name,key])=>{const sh=s.shifts[key]||{};const fp=full.reduce((x,r)=>{const h=dur(r.start,r.end);return x+Number(r.people||0)*dayFactor(r)*overlap(r.start,r.end,sh.start,sh.end)/h;},0);const pp=partial.reduce((x,r)=>{const h=dur(r.start,r.end);return x+Number(r.people||0)*dayFactor(r)*overlap(r.start,r.end,sh.start,sh.end)/h;},0);return{name,key,fullPresent:fp,partialPresent:pp,totalPresent:fp+pp,op:fp+pp};});return{A,D,OP:A+D,rows,reference:ref};}
function openDaysDialog(index){saveInputs();const s=state(),arr=s.page==='partial'?s.partial:s.full,r=arr[index];if(!r)return;normalizeDays(r);const host=document.getElementById('daysDialog');host.innerHTML=`<div class="days-dialog-backdrop"><div class="days-dialog" role="dialog" aria-modal="true" aria-labelledby="daysDialogTitle"><div class="section-heading"><h3 id="daysDialogTitle">Días trabajados</h3><button type="button" class="secondary" data-days-close>Cancelar</button></div><p>Seleccione los días en los que se realiza este horario.</p><div class="choice-list">${Object.entries(DAY_OPTIONS).map(([key,opt])=>`<label><input type="radio" name="daysType" value="${key}" ${r.daysWorked.type===key?'checked':''}> ${opt.label}</label>`).join('')}<label><input type="radio" name="daysType" value="custom" ${r.daysWorked.type==='custom'?'checked':''}> Días personalizados</label></div><div id="customDaysBox" class="days-checkboxes"></div><div class="actions"><button type="button" data-days-cancel class="secondary">Cancelar</button><button type="button" data-days-save>Guardar días</button></div></div></div>`;const box=host.querySelector('#customDaysBox');const renderCustom=()=>{const custom=host.querySelector('input[name="daysType"]:checked')?.value==='custom';box.innerHTML=custom?ALL_DAYS.map(d=>`<label><input type="checkbox" value="${esc(d)}" ${r.daysWorked.selected.includes(d)?'checked':''}> ${d}</label>`).join(''):'';};host.querySelectorAll('input[name="daysType"]').forEach(x=>x.addEventListener('change',renderCustom));renderCustom();const close=()=>{host.hidden=true;host.innerHTML='';};host.querySelector('[data-days-close]').onclick=close;host.querySelector('[data-days-cancel]').onclick=close;host.querySelector('[data-days-save]').onclick=()=>{const type=host.querySelector('input[name="daysType"]:checked')?.value||'weekdays';r.daysWorked=type==='custom'?{type,selected:[...host.querySelectorAll('#customDaysBox input:checked')].map(x=>x.value)}:{type,selected:[...DAY_OPTIONS[type].days]};normalizeDays(r);close();render();};host.hidden=false;}
function render(){const s=state(),host=document.getElementById('formContainer');if(!host)return;host.innerHTML=`<div class="step-title-row"><h3>Personas trabajadoras que realizan MMP</h3></div><div class="subnav"><button type="button" class="subnav-btn ${s.page==='full'?'active':''}" data-v3-page="full">Jornada completa</button><button type="button" class="subnav-btn ${s.page==='partial'?'active':''}" data-v3-page="partial">Horario parcial</button></div><div id="workerV3Page"></div><div id="workerV3Results"></div><div id="daysDialog" hidden></div>`;renderPage();bind();renderResults();}
function renderPage(){const s=state(),h=document.getElementById('workerV3Page'),arr=s.page==='partial'?s.partial:s.full;h.innerHTML=`<div class="worker-subpage"><h3>${s.page==='partial'?'Horarios parciales':'Horarios de jornada completa'}</h3><p>Introduzca entrada, salida, personas y días trabajados.</p>${arr.map((r,i)=>{normalizeDays(r);return `<div class="registry-card worker-row"><div class="grid"><label>Hora de entrada<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="start" type="time" value="${esc(r.start)}"></label><label>Hora de salida<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="end" type="time" value="${esc(r.end)}"></label><label>Personas<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="people" type="number" min="0" step="1" value="${esc(r.people)}"></label><label>Días trabajados<button type="button" class="secondary" data-days-index="${i}">${esc(dayLabel(r))}</button></label></div></div>`;}).join('')}</div>`;}
function renderResults(){const b=document.getElementById('workerV3Results');if(!b)return;const r=calculate();b.innerHTML=`<table><thead><tr><th>Turno</th><th>Entrada</th><th>Salida</th><th>Jornada completa</th><th>Horario parcial</th><th>Personas presentes</th><th>OP</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${x.name}</td><td>${esc(state().shifts[x.key].start)}</td><td>${esc(state().shifts[x.key].end)}</td><td>${x.fullPresent.toFixed(3)}</td><td>${x.partialPresent.toFixed(3)}</td><td><strong>${x.totalPresent.toFixed(3)}</strong></td><td>${x.op.toFixed(3)}</td></tr>`).join('')}</tbody></table><p><strong>A:</strong> ${r.A.toFixed(3)} · <strong>D:</strong> ${r.D.toFixed(3)} · <strong>OP:</strong> ${r.OP.toFixed(3)}</p>`;window.formData.op=r.OP;window.formData.opByShift={};window.formData.presenceByShift={};r.rows.forEach(x=>{window.formData.opByShift[x.key]=x.op;window.formData.presenceByShift[x.key]=x.totalPresent;});}
function bind(){document.querySelectorAll('[data-v3-page]').forEach(b=>b.onclick=()=>{saveInputs();state().page=b.dataset.v3Page;render();});document.querySelectorAll('[data-v3-t]').forEach(e=>e.addEventListener('input',()=>{saveInputs();renderResults();}));document.querySelectorAll('[data-days-index]').forEach(b=>b.onclick=()=>openDaysDialog(Number(b.dataset.daysIndex)));}
window.renderWorkerScheduleV3=render;window.saveWorkerScheduleV3=function(){saveInputs();return calculate();};window.mapoScheduleCanonical={calculate,render,version:null};
})();
