/* Hospitalización — trabajadores MMP: horarios múltiples y subpáginas. */
(function(){
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const num=v=>Number(v||0);
  const mins=t=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t)) throw new Error(`Hora no válida: ${t}. Use formato 24 h (HH:MM).`); const [h,m]=t.split(':').map(Number); return h*60+m;};
  const dur=(a,b)=>{let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x;};
  const overlap=(a,b,c,d)=>{let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const o of [0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+o)-Math.max(s,p+o)));return best;};
  const state=()=>{formData.workerSchedule=formData.workerSchedule||{mode:'auto',page:'full',full:[],partial:[]};return formData.workerSchedule;};
  const classify=start=>{const h=mins(start)/60; if(h>=6&&h<14)return 'Mañana'; if(h>=14&&h<22)return 'Tarde'; return 'Noche';};
  function calculate(){const s=state(), full=s.full||[], partial=s.partial||[];let A=0,B=0,D=0;
    const fullDetails=full.map((r,i)=>{const people=num(r.people);if(!r.start||!r.end)throw new Error(`Complete inicio y salida del horario de turno completo ${i+1}.`);if(!Number.isInteger(people)||people<0)throw new Error(`Las personas del horario completo ${i+1} deben ser un número entero ≥ 0.`);const hours=dur(r.start,r.end)/60;const label=s.mode==='manual'?(r.label||'Sin clasificar'):classify(r.start);A+=people;return{...r,index:i,hours,label,people};});
    const partialDetails=partial.map((r,i)=>{const people=num(r.people);if(!r.start||!r.end)throw new Error(`Complete inicio y salida del horario de turno parcial ${i+1}.`);if(!Number.isInteger(people)||people<0)throw new Error(`Las personas del horario parcial ${i+1} deben ser un número entero ≥ 0.`);if(!fullDetails.length)throw new Error('Debe existir al menos un horario de turno completo antes de registrar personas a turno parcial.');const ref=Number.isInteger(Number(r.reference))?Number(r.reference):0;if(!fullDetails[ref])throw new Error(`Seleccione un horario de referencia para el horario parcial ${i+1}.`);const refHours=fullDetails[ref].hours;const ph=overlap(r.start,r.end,fullDetails[ref].start,fullDetails[ref].end)/60;if(ph<=0)throw new Error(`El horario parcial ${i+1} no coincide con su horario de referencia.`);if(ph>refHours+1e-9)throw new Error(`La presencia del horario parcial ${i+1} no puede superar la duración del horario de referencia.`);const C=ph/refHours,Drow=people*C;B+=people;D+=Drow;return{...r,index:i,reference:ref,referenceLabel:fullDetails[ref].label,partialHours:ph,C,D:Drow,people};});
    return {A,B,D,OP:A+D,fullDetails,partialDetails};
  }
  function renderFull(){const s=state();return `<div class="worker-subpage"><div class="step-title-row"><h3>Turno completo</h3><button type="button" class="help-trigger" data-whelp="full">?</button><div class="help-popover" id="whelp_full" hidden><strong>Personas a turno completo</strong><p>Registre cada horario distinto en el que una persona realiza MMP durante todo el horario indicado. Puede añadir tantos horarios como existan en el centro.</p></div></div><p>Introduzca <strong>cada horario diferente</strong> y el número de personas que lo realizan.</p><div class="worker-list">${(s.full||[]).map((r,i)=>`<div class="registry-card worker-row"><div class="registry-card-head"><h4>Horario completo ${i+1}</h4><button type="button" class="secondary" data-wremove="full" data-wi="${i}">Eliminar</button></div><div class="grid"><label>Hora de inicio<input data-wtype="full" data-wi="${i}" data-wf="start" type="time" value="${esc(r.start)}"></label><label>Hora de salida<input data-wtype="full" data-wi="${i}" data-wf="end" type="time" value="${esc(r.end)}"></label><label>Personas a turno completo<input data-wtype="full" data-wi="${i}" data-wf="people" type="number" min="0" step="1" value="${esc(r.people)}"></label>${s.mode==='manual'?`<label>Clasificación<input data-wtype="full" data-wi="${i}" data-wf="label" type="text" placeholder="Mañana / Tarde / Noche" value="${esc(r.label)}"></label>`:`<label>Clasificación calculada<input type="text" value="${r.start?classify(r.start):''}" readonly></label>`}</div></div>`).join('')}</div><button type="button" class="secondary" id="addFullSchedule">+ Añadir otro horario de turno completo</button></div>`;}
  function renderPartial(){const s=state();return `<div class="worker-subpage"><div class="step-title-row"><h3>Turno parcial</h3><button type="button" class="help-trigger" data-whelp="partial">?</button><div class="help-popover" id="whelp_partial" hidden><strong>Personas a turno parcial</strong><p>Registre cada horario diferente de las personas que realizan MMP solo durante una parte del horario de referencia. C se calcula como las horas de presencia parcial divididas por la duración del horario de referencia seleccionado.</p></div></div><p>Puede registrar tantos horarios parciales diferentes como sean necesarios.</p>${(s.full||[]).length?`<div class="notice"><strong>Importante:</strong> primero se registran los horarios completos. Cada horario parcial se relaciona con uno de ellos para calcular C.</div>`:'<div class="notice">Añada primero al menos un horario de turno completo.</div>'}<div class="worker-list">${(s.partial||[]).map((r,i)=>`<div class="registry-card worker-row"><div class="registry-card-head"><h4>Horario parcial ${i+1}</h4><button type="button" class="secondary" data-wremove="partial" data-wi="${i}">Eliminar</button></div><div class="grid"><label>Hora de inicio<input data-wtype="partial" data-wi="${i}" data-wf="start" type="time" value="${esc(r.start)}"></label><label>Hora de salida<input data-wtype="partial" data-wi="${i}" data-wf="end" type="time" value="${esc(r.end)}"></label><label>Personas a turno parcial<input data-wtype="partial" data-wi="${i}" data-wf="people" type="number" min="0" step="1" value="${esc(r.people)}"></label><label>Horario de referencia<select data-wtype="partial" data-wi="${i}" data-wf="reference">${(s.full||[]).map((f,j)=>`<option value="${j}" ${Number(r.reference||0)===j?'selected':''}>${j+1}. ${esc(f.start)}–${esc(f.end)} (${s.mode==='manual'?esc(f.label||'Sin clasificar'):(f.start?classify(f.start):'')})</option>`).join('')}</select></label></div></div>`).join('')}</div><button type="button" class="secondary" id="addPartialSchedule" ${(s.full||[]).length?'':'disabled'}>+ Añadir otro horario de turno parcial</button></div>`;}
  function renderResults(){const e=$('workerSchedulePreview');if(!e)return;try{const r=calculate();e.innerHTML=`<div class="schedule-preview"><h3>Resultados calculados</h3><p><strong>Personas a turno completo (A):</strong> ${r.A} · <strong>Personas a turno parcial (B):</strong> ${r.B} · <strong>D total:</strong> ${r.D.toFixed(3)} · <strong>OP:</strong> ${r.OP.toFixed(3)}</p><h4>Horarios completos</h4>${r.fullDetails.map(x=>`<p>${x.label}: ${x.start}–${x.end} · ${x.people} personas</p>`).join('')||'<p>No hay horarios completos.</p>'}<h4>Horarios parciales</h4>${r.partialDetails.map(x=>`<p>${x.start}–${x.end} · ${x.people} personas · referencia ${x.referenceLabel} · C=${x.C.toFixed(3)} · D=${x.D.toFixed(3)}</p>`).join('')||'<p>No hay horarios parciales.</p>'}</div>`;formData.op=r.OP;}catch(e2){e.innerHTML=`<div class="error">${esc(e2.message)}</div>`;}}
  function saveInputs(){document.querySelectorAll('[data-wtype]').forEach(el=>{const t=el.dataset.wtype,i=Number(el.dataset.wi),f=el.dataset.wf;const a=state()[t];a[i]??={};a[i][f]=el.type==='number'?(el.value===''?'':Number(el.value)):el.value;});}
  function renderWorker(){const s=state();const host=$('formContainer');host.innerHTML=`<div class="step-title-row"><h3>Personas trabajadoras que realizan MMP</h3><button type="button" class="help-trigger" data-whelp="general">?</button><div class="help-popover" id="whelp_general" hidden><strong>Cómo introducir los trabajadores</strong><p>No se obliga a utilizar solo tres turnos. Registre todos los horarios distintos que existan en el centro. Las personas se separan en dos grupos: <strong>turno completo</strong> y <strong>turno parcial</strong>. El programa calcula A, B, C, D y OP.</p></div></div><div class="shift-mode"><strong>¿Cómo desea clasificar los horarios?</strong><label><input type="radio" name="workerMode" value="auto" ${s.mode==='auto'?'checked':''}> El programa los clasifica a partir de las horas</label><label><input type="radio" name="workerMode" value="manual" ${s.mode==='manual'?'checked':''}> Quiero establecer la clasificación de mañana, tarde y noche</label></div><div class="subnav" role="tablist"><button type="button" class="subnav-btn ${s.page==='full'?'active':''}" data-wpage="full">Turno completo</button><button type="button" class="subnav-btn ${s.page==='partial'?'active':''}" data-wpage="partial">Turno parcial</button></div><div id="workerSubpage">${s.page==='partial'?renderPartial():renderFull()}</div><div id="workerSchedulePreview"></div>`;bind();renderResults();}
  function bind(){document.querySelectorAll('[data-wpage]').forEach(b=>b.onclick=()=>{saveInputs();state().page=b.dataset.wpage;renderWorker();});document.querySelectorAll('input[name="workerMode"]').forEach(r=>r.onchange=()=>{saveInputs();state().mode=r.value;renderWorker();});document.querySelectorAll('[data-wtype]').forEach(el=>el.addEventListener(el.tagName==='SELECT'?'change':'input',()=>{saveInputs();renderResults();}));document.querySelectorAll('[data-wremove]').forEach(b=>b.onclick=()=>{saveInputs();const t=b.dataset.wremove,i=Number(b.dataset.wi);state()[t].splice(i,1);if(t==='full'&&state().full.length){state().partial=(state().partial||[]).map(x=>({...x,reference:Math.min(Number(x.reference||0),state().full.length-1)}));}renderWorker();});$('addFullSchedule')?.addEventListener('click',()=>{saveInputs();state().full.push({start:'',end:'',people:'',label:''});state().page='full';renderWorker();});$('addPartialSchedule')?.addEventListener('click',()=>{saveInputs();if(!state().full.length)return;state().partial.push({start:'',end:'',people:'',reference:0});state().page='partial';renderWorker();});document.querySelectorAll('[data-whelp]').forEach(b=>b.onclick=()=>{const box=$(`whelp_${b.dataset.whelp}`);if(!box)return;const was=box.hidden;document.querySelectorAll('.help-popover,.question-help-popover').forEach(x=>x.hidden=true);box.hidden=!was;});}
  const originalRender=window.renderStep;
  window.renderStep=function(){const step=MAPO_STUDIES[selectedStudy]?.steps?.[currentStep];if(step?.shiftSchedule){renderWorker();$('previousStep').hidden=currentStep===0;$('nextStep').hidden=false;$('calculate').hidden=true;$('progressBar').style.width=`${(currentStep+1)/MAPO_STUDIES[selectedStudy].steps.length*100}%`;return;}originalRender();};
  const originalSave=window.saveStep;
  window.saveStep=function(){const step=MAPO_STUDIES[selectedStudy]?.steps?.[currentStep];if(step?.shiftSchedule){saveInputs();const r=calculate();formData.op=r.OP;return r;}return originalSave();};
  state();
  const style=document.createElement('style');style.textContent='.subnav{display:flex;gap:10px;margin:18px 0;border-bottom:1px solid #dbe3ec;padding-bottom:10px}.subnav-btn{border:1px solid #cbd5e1;background:#fff;border-radius:8px;padding:10px 16px;font-weight:600;cursor:pointer;color:#0b5ea8}.subnav-btn.active{background:#0b74c9;color:#fff;border-color:#0b74c9}.worker-list{display:grid;gap:14px}.worker-row{margin-bottom:0}.worker-row .registry-card-head{display:flex;justify-content:space-between;align-items:center}.notice{background:#f4f8fb;border-left:4px solid #0b74c9;padding:12px 14px;margin:12px 0;border-radius:6px}.worker-subpage{min-height:260px}';document.head.appendChild(style);
})();
