/* MAPO Hospitalización — trabajadores MMP: selección de jornada, horarios y turnos */
(function(){
  const MAX=50, INITIAL=5;
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const state=()=>{const s=formData.workerSchedule=formData.workerSchedule||{};s.page=s.page||'home';s.mode=s.mode||'auto';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];s.shifts=s.shifts||{morning:{start:'06:00',end:'14:00'},afternoon:{start:'14:00',end:'22:00'},night:{start:'22:00',end:'06:00'}};if(!s.full.length)for(let i=0;i<INITIAL;i++)s.full.push({start:'',end:'',people:'',label:''});if(!s.partial.length)for(let i=0;i<INITIAL;i++)s.partial.push({start:'',end:'',people:'',reference:0,label:''});return s;};
  const mins=t=>{if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t||''))throw Error('Hora no válida. Use formato 24 h (HH:MM).');const [h,m]=t.split(':').map(Number);return h*60+m;};
  const dur=(a,b)=>{let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x;};
  const overlap=(a,b,c,d)=>{let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best;};
  const inShift=(t,a,b)=>{const x=mins(t),s=mins(a),e=mins(b);if(e===s)return true;return e>s?x>=s&&x<e:x>=s||x<e;};
  const fmt=n=>String(Math.floor(n/60)%24).padStart(2,'0')+':'+String(n%60).padStart(2,'0');
  function suggested(rows){const valid=rows.filter(r=>r.start&&r.end);if(!valid.length)return {morning:{start:'06:00',end:'14:00'},afternoon:{start:'14:00',end:'22:00'},night:{start:'22:00',end:'06:00'}};const base=valid.map(r=>mins(r.start)).sort((a,b)=>a-b)[0];return {morning:{start:fmt(base),end:fmt((base+480)%1440)},afternoon:{start:fmt((base+480)%1440),end:fmt((base+960)%1440)},night:{start:fmt((base+960)%1440),end:fmt(base)}};}
  const activeShifts=s=>s.mode==='auto'?suggested(s.full):s.shifts;
  const classify=(r,s)=>{if(!r.start)return 'Sin clasificar';const sh=activeShifts(s);for(const [k,v] of Object.entries(sh))if(inShift(r.start,v.start,v.end))return k==='morning'?'Mañana':k==='afternoon'?'Tarde':'Noche';return 'Sin clasificar';};
  function calculate(){const s=state(),full=s.full.filter(r=>r.start||r.end||r.people!==''),partial=s.partial.filter(r=>r.start||r.end||r.people!==''),sh=activeShifts(s);let A=0,B=0,D=0;const fd=full.map((r,i)=>{if(!r.start||!r.end)throw Error('Complete entrada y salida del horario completo '+(i+1)+'.');const p=Number(r.people||0);if(!Number.isInteger(p)||p<0)throw Error('Personas del horario completo '+(i+1)+' debe ser un entero ≥ 0.');A+=p;return {...r,people:p,hours:dur(r.start,r.end)/60,label:classify(r,s),index:i};});const pd=partial.map((r,i)=>{if(!r.start||!r.end)throw Error('Complete entrada y salida del horario parcial '+(i+1)+'.');const p=Number(r.people||0);if(!Number.isInteger(p)||p<0)throw Error('Personas del horario parcial '+(i+1)+' debe ser un entero ≥ 0.');if(!fd.length)throw Error('Introduzca primero al menos un horario de jornada completa.');const ref=Math.min(Number(r.reference||0),fd.length-1),ph=overlap(r.start,r.end,fd[ref].start,fd[ref].end)/60,C=ph/fd[ref].hours,Drow=p*C;B+=p;D+=Drow;return {...r,people:p,reference:ref,C,D:Drow,label:classify(r,s),index:i};});const names=[['Mañana','morning'],['Tarde','afternoon'],['Noche','night']],distribution=names.map(([name,key])=>{const f=fd.filter(x=>x.label===name),p=pd.filter(x=>x.label===name);return{name,key,fullPeople:f.reduce((n,x)=>n+x.people,0),partialPeople:p.reduce((n,x)=>n+x.people,0)});return{A,B,D,OP:A+D,fd,pd,sh,distribution};}
  function renderHome(){const s=state(),h=$('formContainer');h.innerHTML=`<div class="step-title-row"><h3>Personas trabajadoras que realizan MMP</h3></div><p>Seleccione el tipo de jornada que desea introducir. Podrá registrar hasta 50 horarios en cada categoría.</p><div class="worker-choice-grid"><button type="button" class="worker-choice" data-v3-page="full"><strong>Jornada completa</strong><span>Introducir horarios de entrada, salida y número de personas que realizan la jornada completa.</span></button><button type="button" class="worker-choice" data-v3-page="partial"><strong>Horario parcial</strong><span>Introducir horarios de entrada, salida y número de personas que realizan una jornada parcial.</span></button></div><div class="shift-mode"><h4>¿Cómo desea establecer los turnos?</h4><label><input type="radio" name="v3mode" value="auto" ${s.mode==='auto'?'checked':''}> Que el programa sugiera Mañana / Tarde / Noche según los horarios introducidos</label><label><input type="radio" name="v3mode" value="manual" ${s.mode==='manual'?'checked':''}> Establecer yo los turnos</label></div><div id="v3ShiftHome"></div>`;renderShiftHome();bindHome();}
  function renderShiftHome(){const s=state(),e=$('v3ShiftHome');if(!e)return;if(s.mode==='auto'){const q=suggested(s.full);e.innerHTML=`<div class="schedule-preview"><h4>Turnos sugeridos</h4><p>La propuesta se actualizará al introducir los horarios.</p><table><thead><tr><th>Turno</th><th>Entrada</th><th>Salida</th></tr></thead><tbody><tr><td>Mañana</td><td>${q.morning.start}</td><td>${q.morning.end}</td></tr><tr><td>Tarde</td><td>${q.afternoon.start}</td><td>${q.afternoon.end}</td></tr><tr><td>Noche</td><td>${q.night.start}</td><td>${q.night.end}</td></tr></tbody></table></div>`;}else e.innerHTML=`<div class="schedule-preview"><h4>Turnos definidos por el usuario</h4><div class="grid"><label>Mañana — entrada<input type="time" data-v3-shift="morning" data-v3-f="start" value="${esc(s.shifts.morning.start)}"></label><label>Mañana — salida<input type="time" data-v3-shift="morning" data-v3-f="end" value="${esc(s.shifts.morning.end)}"></label><label>Tarde — entrada<input type="time" data-v3-shift="afternoon" data-v3-f="start" value="${esc(s.shifts.afternoon.start)}"></label><label>Tarde — salida<input type="time" data-v3-shift="afternoon" data-v3-f="end" value="${esc(s.shifts.afternoon.end)}"></label><label>Noche — entrada<input type="time" data-v3-shift="night" data-v3-f="start" value="${esc(s.shifts.night.start)}"></label><label>Noche — salida<input type="time" data-v3-shift="night" data-v3-f="end" value="${esc(s.shifts.night.end)}"></label></div></div>`;}
  function renderPage(){const s=state(),arr=s.page==='partial'?s.partial:s.full,title=s.page==='partial'?'Horario parcial':'Jornada completa';$('formContainer').innerHTML=`<div class="step-title-row"><button type="button" class="secondary" id="v3Back">← Volver</button><h3>${title}</h3></div><p>Introduzca hora de entrada, hora de salida y personas. Se muestran 5 horarios inicialmente y puede añadir hasta 50.</p><div class="worker-list">${arr.map((r,i)=>`<div class="registry-card worker-row"><div class="registry-card-head"><h4>${title} ${i+1}</h4>${i>=INITIAL?`<button type="button" class="secondary" data-v3-remove="${s.page}" data-v3-i="${i}">Eliminar</button>`:''}</div><div class="grid"><label>Hora de entrada<input type="time" data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="start" value="${esc(r.start)}"></label><label>Hora de salida<input type="time" data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="end" value="${esc(r.end)}"></label><label>Personas<input type="number" min="0" step="1" data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="people" value="${esc(r.people)}"></label>${s.page==='partial'&&s.full.some(x=>x.start&&x.end)?`<label>Horario completo de referencia<select data-v3-t="partial" data-v3-i="${i}" data-v3-f="reference">${s.full.map((f,j)=>`<option value="${j}" ${Number(r.reference||0)===j?'selected':''}>${j+1}. ${esc(f.start)}–${esc(f.end)}</option>`).join('')}</select></label>`:''}</div></div>`).join('')}</div><button type="button" class="secondary" id="v3Add" ${arr.length>=MAX?'disabled':''}>+ Añadir otro horario</button><div class="shift-mode"><h4>Turnos</h4><p>${s.mode==='auto'?'El programa los clasifica según la propuesta de turnos.':'Los horarios se clasificarán según los turnos definidos por usted.'}</p>${s.mode==='auto'?'<p><strong>Turnos sugeridos:</strong> '+Object.entries(suggested(s.full)).map(([k,v])=>(k==='morning'?'Mañana':k==='afternoon'?'Tarde':'Noche')+' '+v.start+'–'+v.end).join(' · ')+'</p>':'<p><strong>Turnos definidos:</strong> '+Object.entries(s.shifts).map(([k,v])=>(k==='morning'?'Mañana':k==='afternoon'?'Tarde':'Noche')+' '+v.start+'–'+v.end).join(' · ')+'</p>'}</div><div id="v3Results"></div>`;bindPage();renderResults();}
  function saveInputs(){const s=state();document.querySelectorAll('[data-v3-t]').forEach(e=>{const a=s[e.dataset.v3T],i=Number(e.dataset.v3I);a[i]??={};a[i][e.dataset.v3F]=e.type==='number'?(e.value===''?'':Number(e.value)):e.value;});document.querySelectorAll('[data-v3-shift]').forEach(e=>s.shifts[e.dataset.v3-shift][e.dataset.v3-f]=e.value);}
  function bindHome(){document.querySelectorAll('[data-v3-page]').forEach(b=>b.onclick=()=>{state().page=b.dataset.v3Page;renderPage();});document.querySelectorAll('input[name="v3mode"]').forEach(r=>r.onchange=()=>{state().mode=r.value;renderHome();});document.querySelectorAll('[data-v3-shift]').forEach(e=>e.onchange=()=>{saveInputs();renderHome();});}
  function bindPage(){document.getElementById('v3Back')?.addEventListener('click',()=>{saveInputs();state().page='home';renderHome();});document.querySelectorAll('[data-v3-t]').forEach(e=>e.addEventListener(e.tagName==='SELECT'?'change':'input',()=>{saveInputs();renderResults();}));document.querySelectorAll('[data-v3-remove]').forEach(b=>b.onclick=()=>{saveInputs();const a=state()[b.dataset.v3Remove];if(a.length>INITIAL)a.splice(Number(b.dataset.v3I),1);renderPage();});$('v3Add')?.addEventListener('click',()=>{saveInputs();const s=state(),a=s[s.page];if(a.length<MAX){a.push(s.page==='partial'?{start:'',end:'',people:'',reference:0,label:''}:{start:'',end:'',people:'',label:''});renderPage();}});}
  function renderResults(){const e=$('v3Results');if(!e)return;try{const r=calculate();e.innerHTML=`<div class="schedule-preview"><h3>Distribución por turnos</h3><table><thead><tr><th>Turno</th><th>Entrada</th><th>Salida</th><th>Jornada completa</th><th>Horario parcial</th></tr></thead><tbody>${r.distribution.map(x=>`<tr><td>${x.name}</td><td>${r.sh[x.key].start}</td><td>${r.sh[x.key].end}</td><td>${x.fullPeople}</td><td>${x.partialPeople}</td></tr>`).join('')}</tbody></table><p><strong>A:</strong> ${r.A} · <strong>B:</strong> ${r.B} · <strong>D:</strong> ${r.D.toFixed(3)} · <strong>OP:</strong> ${r.OP.toFixed(3)}</p></div>`;formData.op=r.OP;formData.workerSchedule.distribution=r.distribution;}catch(err){e.innerHTML=`<div class="error">${esc(err.message)}</div>`;}}
  function isStep(){return MAPO_STUDIES[selectedStudy]?.steps?.[currentStep]?.shiftSchedule;}
  const oldRender=window.renderStep;window.renderStep=function(){if(isStep()){state();if(state().page==='home')renderHome();else renderPage();$('previousStep').hidden=currentStep===0;$('nextStep').hidden=false;$('calculate').hidden=true;$('progressBar').style.width=`${(currentStep+1)/MAPO_STUDIES[selectedStudy].steps.length*100}%`;return;}return oldRender.apply(this,arguments);};
  const oldSave=window.saveStep;window.saveStep=function(){if(isStep()){saveInputs();const r=calculate();formData.op=r.OP;formData.workerSchedule.distribution=r.distribution;return r;}return oldSave.apply(this,arguments);};
  const style=document.createElement('style');style.textContent='.worker-choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px;margin:20px 0}.worker-choice{display:flex;flex-direction:column;gap:8px;text-align:left;padding:22px;border:2px solid #cbd5e1;border-radius:10px;background:#fff;cursor:pointer;color:#0b5ea8}.worker-choice:hover{border-color:#0b74c9;background:#f5faff}.worker-choice strong{font-size:1.15rem}.worker-choice span{color:#475569;font-weight:400}.worker-row .registry-card-head{display:flex;justify-content:space-between;align-items:center}.worker-list{display:grid;gap:14px}.shift-mode{margin:18px 0;padding:16px;border:1px solid #dbe3ec;border-radius:8px;background:#f8fafc}.shift-mode label{display:block;margin:10px 0}.schedule-preview{margin-top:18px}.schedule-preview table{width:100%;border-collapse:collapse;margin:12px 0}.schedule-preview th,.schedule-preview td{border:1px solid #dbe3ec;padding:8px;text-align:left}@media(max-width:700px){.worker-choice-grid{grid-template-columns:1fr}}';document.head.appendChild(style);
})();