/* MAPO Hospitalización — horarios completos/parciales, turnos y cálculo */
(function(){
  const MAX=50, INITIAL=5;
  function st(){const s=formData.workerSchedule=formData.workerSchedule||{};s.mode=s.mode||'auto';s.page=s.page||'full';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];s.shifts=s.shifts||{morning:{start:'06:00',end:'14:00'},afternoon:{start:'14:00',end:'22:00'},night:{start:'22:00',end:'06:00'}};if(!s.full.length)for(let i=0;i<INITIAL;i++)s.full.push({start:'',end:'',people:'',label:''});if(!s.partial.length)for(let i=0;i<INITIAL;i++)s.partial.push({start:'',end:'',people:'',reference:0});return s;}
  function mins(t){const m(/^(\d\d):(\d\d)$/.exec(t||''));if(!m||+m[1]>23||+m[2]>59)throw Error('Hora no válida. Use formato 24 h (HH:MM).');return +m[1]*60 + +m[2];}
  function dur(a,b){let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x;}
  function overlap(a,b,c,d){let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best;}
  function inShift(t,a,b){let x=mins(t),s=mins(a),e=mins(b);if(e===s)return true;if(e>s)return x>=s&&x<e;return x>=s||x<e;}
  function autoSuggestion(rows){const valid=rows.filter(r=>r.start&&r.end).map(r=>({s:mins(r.start),e:mins(r.end)}));if(!valid.length)return {morning:{start:'06:00',end:'14:00'},afternoon:{start:'14:00',end:'22:00'},night:{start:'22:00',end:'06:00'}};let points=[];valid.forEach(r=>{points.push(r.s);points.push(r.e%1440);});points.sort((a,b)=>a-b);const gaps=[];for(let i=0;i<points.length;i++){const a=points[i],b=points[(i+1)%points.length]+(i===points.length-1?1440:0);gaps.push({a,b,len:b-a});}gaps.sort((a,b)=>b.len-a.len);const base=gaps[0]?.a??360;const h1=(base%1440+480)%1440,h2=(base%1440+960)%1440;const f=n=>String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0');return {morning:{start:f(h1),end:f(h2)},afternoon:{start:f(h2),end:f((h2+480)%1440)},night:{start:f((h2+480)%1440),end:f(h1)}};}
  function cls(r,s,shifts){if(s.mode==='manual')return r.label||'Sin clasificar';for(const [k,v] of Object.entries(shifts)){if(r.start&&inShift(r.start,v.start,v.end))return k==='morning'?'Mañana':k==='afternoon'?'Tarde':'Noche';}return 'Sin clasificar';}
  function calc(){const s=st(),full=s.full.filter(r=>r.start||r.end||r.people!==''),part=s.partial.filter(r=>r.start||r.end||r.people!==''),shifts=s.mode==='auto'?autoSuggestion(full):s.shifts;let A=0,B=0,D=0;const fd=full.map((r,i)=>{if(!r.start||!r.end)throw Error('Complete entrada y salida del horario completo '+(i+1)+'.');const p=Number(r.people||0);if(!Number.isInteger(p)||p<0)throw Error('Personas debe ser un entero igual o mayor que 0.');const h=dur(r.start,r.end)/60;A+=p;return {...r,people:p,hours:h,label:cls(r,s,shifts),index:i};});const pd=part.map((r,i)=>{if(!r.start||!r.end)throw Error('Complete entrada y salida del horario parcial '+(i+1)+'.');const p=Number(r.people||0);if(!Number.isInteger(p)||p<0)throw Error('Personas debe ser un entero igual o mayor que 0.');if(!fd.length)throw Error('Añada al menos un horario completo antes de calcular horarios parciales.');const ref=Math.min(Number(r.reference||0),fd.length-1),ph=overlap(r.start,r.end,fd[ref].start,fd[ref].end)/60,C=ph/fd[ref].hours,Dx=p*C;B+=p;D+=Dx;return {...r,people:p,reference:ref,C,D:Dx,label:cls(r,s,shifts),index:i};});
    const names=['Mañana','Tarde','Noche'];const distribution=names.map(name=>{const f=fd.filter(x=>x.label===name),p=pd.filter(x=>x.label===name);return{name,fullPeople:f.reduce((n,x)=>n+x.people,0),partialPeople:p.reduce((n,x)=>n+x.people,0),fullSchedules:f.length,partialSchedules:p.length,partialC:p.reduce((n,x)=>n+x.C,0),partialD:p.reduce((n,x)=>n+x.D,0)});});
    return{A,B,D,OP:A+D,fd,pd,shifts,distribution};}
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  function render(){const s=st(),host=$('formContainer');host.innerHTML=`<div class="step-title-row"><h3>Personas trabajadoras que realizan MMP</h3></div><div class="shift-mode"><strong>Clasificación de turnos</strong><label><input type="radio" name="workerModeV3" value="auto" ${s.mode==='auto'?'checked':''}> Sugerir turnos según los horarios introducidos</label><label><input type="radio" name="workerModeV3" value="manual" ${s.mode==='manual'?'checked':''}> Establecer yo los turnos</label></div><div id="shiftConfig"></div><div class="subnav"><button type="button" class="subnav-btn ${s.page==='full'?'active':''}" data-v3-page="full">Jornada completa</button><button type="button" class="subnav-btn ${s.page==='partial'?'active':''}" data-v3-page="partial">Horario parcial</button></div><div id="workerV3Page"></div><div id="workerV3Results"></div>`;renderShiftConfig();bind();renderPage();renderResults();}
  function renderShiftConfig(){const s=st(),e=$('shiftConfig');if(s.mode==='auto'){const q=autoSuggestion(s.full);s.suggested=q;e.innerHTML=`<div class="schedule-preview"><h4>Turnos sugeridos por el programa</h4><p>La propuesta se basa en los horarios introducidos. Puede modificarla eligiendo «Establecer yo los turnos».</p><div class="grid"><label>Mañana — entrada<input type="time" value="${q.morning.start}" readonly></label><label>Mañana — salida<input type="time" value="${q.morning.end}" readonly></label><label>Tarde — entrada<input type="time" value="${q.afternoon.start}" readonly></label><label>Tarde — salida<input type="time" value="${q.afternoon.end}" readonly></label><label>Noche — entrada<input type="time" value="${q.night.start}" readonly></label><label>Noche — salida<input type="time" value="${q.night.end}" readonly></label></div></div>`;}else{e.innerHTML=`<div class="schedule-preview"><h4>Establezca los turnos</h4><p>Introduzca la entrada y salida de cada turno. Se utilizarán para clasificar todos los horarios.</p><div class="grid"><label>Mañana — entrada<input data-shift="morning" data-f="start" type="time" value="${esc(s.shifts.morning.start)}"></label><label>Mañana — salida<input data-shift="morning" data-f="end" type="time" value="${esc(s.shifts.morning.end)}"></label><label>Tarde — entrada<input data-shift="afternoon" data-f="start" type="time" value="${esc(s.shifts.afternoon.start)}"></label><label>Tarde — salida<input data-shift="afternoon" data-f="end" type="time" value="${esc(s.shifts.afternoon.end)}"></label><label>Noche — entrada<input data-shift="night" data-f="start" type="time" value="${esc(s.shifts.night.start)}"></label><label>Noche — salida<input data-shift="night" data-f="end" type="time" value="${esc(s.shifts.night.end)}"></label></div></div>`;}}
  function renderPage(){const s=st(),h=$('workerV3Page'),arr=s.page==='partial'?s.partial:s.full,title=s.page==='partial'?'Horarios parciales':'Horarios de jornada completa';h.innerHTML=`<div class="worker-subpage"><div class="step-title-row"><h3>${title}</h3></div><p>Introduzca entrada, salida y número de personas. Se muestran 5 horarios inicialmente y puede añadir hasta 50.</p><div class="worker-list">${arr.map((r,i)=>`<div class="registry-card worker-row"><div class="registry-card-head"><h4>Horario ${i+1}</h4><button type="button" class="secondary" data-v3-remove="${s.page}" data-v3-i="${i}">Eliminar</button></div><div class="grid"><label>Hora de entrada<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="start" type="time" value="${esc(r.start)}"></label><label>Hora de salida<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="end" type="time" value="${esc(r.end)}"></label><label>Personas<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="people" type="number" min="0" step="1" value="${esc(r.people)}"></label>${s.page==='partial'&&s.full.some(x=>x.start&&x.end)?`<label>Horario completo de referencia<select data-v3-t="partial" data-v3-i="${i}" data-v3-f="reference">${s.full.map((f,j)=>`<option value="${j}" ${Number(r.reference||0)===j?'selected':''}>${j+1}. ${esc(f.start)}–${esc(f.end)}</option>`).join('')}</select></label>`:''}</div></div>`).join('')}</div><button type="button" class="secondary" id="v3Add" ${arr.length>=MAX?'disabled':''}>+ Añadir otro horario</button></div>`;}
  function saveInputs(){const s=st();document.querySelectorAll('[data-v3-t]').forEach(e=>{const a=s[e.dataset.v3T],i=Number(e.dataset.v3I),f=e.dataset.v3F;a[i]??={};a[i][f]=e.type==='number'?(e.value===''?'':Number(e.value)):e.value;});document.querySelectorAll('[data-shift]').forEach(e=>{s.shifts[e.dataset.shift][e.dataset.f]=e.value;});}
  function bind(){document.querySelectorAll('[data-v3-page]').forEach(b=>b.onclick=()=>{saveInputs();st().page=b.dataset.v3Page;render();});document.querySelectorAll('input[name="workerModeV3"]').forEach(b=>b.onchange=()=>{saveInputs();st().mode=b.value;render();});document.querySelectorAll('[data-v3-t]').forEach(e=>e.addEventListener(e.tagName==='SELECT'?'change':'input',()=>{saveInputs();renderResults();}));document.querySelectorAll('[data-shift]').forEach(e=>e.addEventListener('change',()=>{saveInputs();renderResults();}));document.querySelectorAll('[data-v3-remove]').forEach(b=>b.onclick=()=>{saveInputs();const a=st()[b.dataset.v3Remove];if(a.length>INITIAL)a.splice(Number(b.dataset.v3I),1);render();});$('v3Add')?.addEventListener('click',()=>{saveInputs();const s=st(),a=s[s.page];if(a.length>=MAX){return;}a.push(s.page==='partial'?{start:'',end:'',people:'',reference:0}:{start:'',end:'',people:'',label:''});render();});}
  function renderResults(){const e=$('workerV3Results');if(!e)return;try{const r=calc();const sh=r.shifts;e.innerHTML=`<div class="schedule-preview"><h3>Distribución por turnos</h3><table><thead><tr><th>Turno</th><th>Entrada</th><th>Salida</th><th>Jornada completa</th><th>Horario parcial</th></tr></thead><tbody>${r.distribution.map(x=>`<tr><td><strong>${x.name}</strong></td><td>${sh[x.name==='Mañana'?'morning':x.name==='Tarde'?'afternoon':'night'].start}</td><td>${sh[x.name==='Mañana'?'morning':x.name==='Tarde'?'afternoon':'night'].end}</td><td>${x.fullPeople}</td><td>${x.partialPeople}</td></tr>`).join('')}</tbody></table><p><strong>A:</strong> ${r.A} · <strong>B:</strong> ${r.B} · <strong>D:</strong> ${r.D.toFixed(3)} · <strong>OP:</strong> ${r.OP.toFixed(3)}</p><h4>Detalle de horarios completos</h4><table><thead><tr><th>Horario</th><th>Personas</th><th>Turno</th></tr></thead><tbody>${r.fd.map(x=>`<tr><td>${x.start}–${x.end}</td><td>${x.people}</td><td>${x.label}</td></tr>`).join('')}</tbody></table>${r.pd.length?`<h4>Detalle de horarios parciales</h4><table><thead><tr><th>Horario</th><th>Personas</th><th>Turno</th><th>C</th><th>D</th></tr></thead><tbody>${r.pd.map(x=>`<tr><td>${x.start}–${x.end}</td><td>${x.people}</td><td>${x.label}</td><td>${x.C.toFixed(3)}</td><td>${x.D.toFixed(3)}</td></tr>`).join('')}</tbody></table>`:''}</div>`;formData.op=r.OP;formData.workerSchedule.distribution=r.distribution;}catch(err){e.innerHTML=`<div class="error">${esc(err.message)}</div>`;}}
  function isWorker(){return MAPO_STUDIES[selectedStudy]?.steps?.[currentStep]?.shiftSchedule;}
  const oldRender=window.renderStep;window.renderStep=function(){if(isWorker()){render();$('previousStep').hidden=currentStep===0;$('nextStep').hidden=false;$('calculate').hidden=true;$('progressBar').style.width=`${(currentStep+1)/MAPO_STUDIES[selectedStudy].steps.length*100}%`;return;}return oldRender.apply(this,arguments);};
  const oldSave=window.saveStep;window.saveStep=function(){if(isWorker()){saveInputs();const r=calc();formData.op=r.OP;formData.workerSchedule.distribution=r.distribution;return r;}return oldSave.apply(this,arguments);};
})();