/* MAPO Hospitalización — módulo canónico de horarios y personas trabajadoras. */
(function(){
'use strict';
const INITIAL=5;
const ALL_DAYS=['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const DAY_OPTIONS={weekdays:{label:'Lunes a viernes',days:ALL_DAYS.slice(0,5)},weekend:{label:'Sábado y domingo',days:ALL_DAYS.slice(5)},longshort:{label:'Semana larga/semana corta',days:[...ALL_DAYS]}};
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const emptyFull=()=>({start:'',end:'',people:'',label:'',daysWorked:{type:'weekdays',selected:[...DAY_OPTIONS.weekdays.days]}});
const emptyPartial=()=>({start:'',end:'',people:'',label:'',reference:0,daysWorked:{type:'weekdays',selected:[...DAY_OPTIONS.weekdays.days]}});
function normalizeDays(r){if(!r.daysWorked)r.daysWorked={type:'weekdays',selected:[...DAY_OPTIONS.weekdays.days]};if(r.daysWorked.type==='longweek'||r.daysWorked.type==='shortweek')r.daysWorked={type:'longshort',selected:[...ALL_DAYS]};if(!Array.isArray(r.daysWorked.selected))r.daysWorked.selected=[...DAY_OPTIONS.weekdays.days];if(r.daysWorked.type!=='custom'&&!DAY_OPTIONS[r.daysWorked.type])r.daysWorked.type='weekdays';if(r.daysWorked.type==='longshort')r.daysWorked.selected=[...ALL_DAYS];return r.daysWorked;}
function dayFactor(r){const d=normalizeDays(r);return d.type==='longshort'?1:d.selected.length/7;}
function dayLabel(r){const d=normalizeDays(r);return d.type==='custom'?(d.selected.length?d.selected.join(', '):'Sin días seleccionados'):(DAY_OPTIONS[d.type]?.label||'Lunes a viernes');}
function state(){window.formData=window.formData||{};const s=window.formData.workerSchedule=window.formData.workerSchedule||{};s.page=s.page||'full';s.mode=s.mode||'manual';s.full=Array.isArray(s.full)?s.full:[];s.partial=Array.isArray(s.partial)?s.partial:[];s.shifts=s.shifts||{morning:{start:'07:00',end:'15:00'},afternoon:{start:'15:00',end:'23:00'},night:{start:'23:00',end:'07:00'}};if(!s.full.length)for(let i=0;i<INITIAL;i++)s.full.push(emptyFull());if(!s.partial.length)for(let i=0;i<INITIAL;i++)s.partial.push(emptyPartial());s.full.forEach(normalizeDays);s.partial.forEach(normalizeDays);return s;}
function mins(t){if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(t||''))throw Error('Hora no válida. Use formato 24 h (HH:MM).');const [h,m]=t.split(':').map(Number);return h*60+m;}
function dur(a,b){let x=mins(a),y=mins(b);if(y<=x)y+=1440;return y-x;}
function overlap(a,b,c,d){let s=mins(a),e=mins(b),p=mins(c),q=mins(d);if(e<=s)e+=1440;if(q<=p)q+=1440;let best=0;for(const z of [-1440,0,1440])best=Math.max(best,Math.max(0,Math.min(e,q+z)-Math.max(s,p+z)));return best;}
function saveInputs(){const s=state();document.querySelectorAll('[data-v3-t]').forEach(e=>{const a=s[e.dataset.v3T],i=Number(e.dataset.v3I),f=e.dataset.v3F;a[i]??={};a[i][f]=e.type==='number'?(e.value===''?'':Number(e.value)):e.value;});}
/*
 * Unidad matemática única de presencia:
 * cada turno es la unidad de referencia. La contribución no se divide
 * entre 24 h ni entre las horas de la jornada individual.
 *
 * presencia equivalente = personas × días/7 × horas dentro del turno / horas del turno
 *
 * Así, por ejemplo, 07:00–19:00 aporta 1.000 al turno 07–15 y
 * 0.500 al turno 15–23. Los horarios que cruzan medianoche se resuelven
 * mediante overlap(), y semana larga/corta equivale a 7/7.
 */
function presenceInTurn(r,turn){const shiftHours=dur(turn.start,turn.end);if(!shiftHours)return 0;const overlapHours=overlap(r.start,r.end,turn.start,turn.end);if(!overlapHours)return 0;return Number(r.people)*dayFactor(r)*(overlapHours/shiftHours);}
function calculate(){const s=state();const full=s.full.filter(r=>r.start&&r.end&&Number(r.people)>0);const partial=s.partial.filter(r=>r.start&&r.end&&Number(r.people)>0);const rows=[['Mañana','morning'],['Tarde','afternoon'],['Noche','night']].map(([name,key])=>{const sh=s.shifts[key];const fullPresent=full.reduce((n,r)=>n+presenceInTurn(r,sh),0);const partialPresent=partial.reduce((n,r)=>n+presenceInTurn(r,sh),0);return{name,key,fullPresent,partialPresent,totalPresent:fullPresent+partialPresent,op:fullPresent+partialPresent};});const A=rows.reduce((n,r)=>n+r.fullPresent,0);const D=rows.reduce((n,r)=>n+r.partialPresent,0);const OP=A+D;return{A,D,OP,rows,totalBase:OP,numericalDifference:0};}
function renderPage(){const s=state(),h=document.getElementById('workerV3Page'),arr=s.page==='partial'?s.partial:s.full;h.innerHTML=`<div class="worker-subpage"><h3>${s.page==='partial'?'Horarios parciales':'Horarios de jornada completa'}</h3><p>Introduzca entrada, salida, personas y días trabajados.</p>${arr.map((r,i)=>`<div class="registry-card worker-row"><div class="grid"><label>Hora de entrada<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="start" type="time" value="${esc(r.start)}"></label><label>Hora de salida<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="people" type="number" min="0" step="1" value="${esc(r.people)}"></label><label>Personas<input data-v3-t="${s.page}" data-v3-i="${i}" data-v3-f="people" type="number" min="0" step="1" value="${esc(r.people)}"></label><label>Días trabajados><button type="button" class="secondary" data-days-index="${i}">${esc(dayLabel(r))}</button></label></div><div class="worker-row-actions"><button type="button" class="secondary" data-delete-index="${i}">Eliminar horario</button></div></div>`).join('')}</div><button type="button" class="secondary" id="addWorkerSchedule">+ Añadir otro horario</button>`;}
function renderResults(){const b=document.getElementById('workerV3Results');if(!b)return;const r=calculate(),s=state();b.innerHTML=`<table><thead><tr><th>Turno</th><th>Entrada</th><th>Salida</th><th>Jornada completa</th><th>Horario parcial</th><th>Personas presentes</th><th>OP</th></tr></thead><tbody>${r.rows.map(x=>`<tr><td>${x.name}</td><td>${esc(s.shifts[x.key].start)}</td><td>${esc(s.shifts[x.key].end)}</td><td>${x.fullPresent.toFixed(3)}</td><td>${x.partialPresent.toFixed(3)}</td><td><strong>${x.totalPresent.toFixed(3)}</strong></td><td>${x.op.toFixed(3)}</td></tr>`).join('')}</tbody></table><p><strong>A:</strong> ${r.A.toFixed(3)} · <strong>D:</strong> ${r.D.toFixed(3)} · <strong>OP:</strong> ${r.OP.toFixed(3)}</p><p><strong>OP por turnos — global:</strong> ${r.OP.toFixed(3)}</p>`;window.formData.op=r.OP;window.formData.opByShift={};window.formData.presenceByShift={};r.rows.forEach(x=>{window.formData.opByShift[x.key]=x.op;window.formData.presenceByShift[x.key]=x.totalPresent;});}
function ensureDialogStyle(){if(document.getElementById('mapoDaysDialogStyle'))return;const st=document.createElement('style');st.id='mapoDaysDialogStyle';st.textContent=`.mapo-days-dialog{position:fixed;inset:0;z-index:2147483000;font-family:inherit}.mapo-days-dialog[hidden]{display:none!important}.mapo-days-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.48);backdrop-filter:blur(1px)}.mapo-days-modal{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:min(560px,calc(100% - 32px));max-height:calc(100vh - 48px);overflow:auto;background:#fff;color:#222;border:1px solid #d8dde3;border-radius:14px;padding:24px;box-sizing:border-box;box-shadow:0 24px 70px rgba(0,0,0,.32)}.mapo-days-modal h3{margin:0 0 8px;font-size:1.25rem;color:#1f2937}.mapo-days-modal p{margin:0 0 16px;color:#4b5563}.mapo-days-presets{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 18px}.mapo-days-presets button{border:1px solid #cfd6df;background:#f5f7fa;color:#263238;border-radius:8px;padding:8px 11px;cursor:pointer}.mapo-days-presets button:hover{background:#e9edf2}.mapo-days-list{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:0 0 20px}.mapo-days-list label{display:flex;align-items:center;gap:8px;padding:10px 12px;border:1px solid #d9dee5;border-radius:8px;background:#fafbfc;color:#263238;cursor:pointer}.mapo-days-list label:hover{background:#f1f4f7}.mapo-days-list input{margin:0}.mapo-days-modal>[data-days-close],.mapo-days-modal>[data-days-save]{border:0;border-radius:8px;padding:9px 15px;cursor:pointer}.mapo-days-modal>[data-days-close]{background:#eef1f4;color:#263238}.mapo-days-modal>[data-days-save]{background:#2563eb;color:#fff;margin-left:8px}.mapo-days-modal>[data-days-save]:hover{background:#1d4ed8}@media(max-width:600px){.mapo-days-list{grid-template-columns:1fr}.mapo-days-modal{padding:18px}}`;document.head.appendChild(st);}
function openDaysDialog(index){saveInputs();const s=state(),arr=s.page==='partial'?s.partial:s.full,r=arr[index];if(!r)return;normalizeDays(r);ensureDialogStyle();let d=document.getElementById('daysDialog');if(!d){d=document.createElement('div');d.id='daysDialog';d.className='mapo-days-dialog';d.hidden=true;document.body.appendChild(d);}d.dataset.index=index;d.hidden=false;d.innerHTML=`<div class="mapo-days-backdrop" data-days-close></div><div class="mapo-days-modal"><h3>Días trabajados</h3><p>Seleccione los días en los que trabaja este horario.</p><div class="mapo-days-presets"><button type="button" data-preset="weekdays">Lunes a viernes</button><button type="button" data-preset="weekend">Sábado y domingo</button><button type="button" data-preset="longshort">Semana larga/semana corta</button><button type="button" data-preset="custom">Personalizado</button></div><div class="mapo-days-list">${ALL_DAYS.map((day,i)=>`<label><input type="checkbox" data-day="${i}" ${r.daysWorked.selected.includes(day)?'checked':''}> ${day}</label>`).join('')}</div><div><button type="button" data-days-close>Cancelar</button><button type="button" data-days-save>Guardar días</button></div></div>`;d.onclick=e=>{if(e.target.closest('[data-days-close]'))closeDays();if(e.target.closest('[data-days-save]'))saveDays();if(e.target.closest('[data-preset]'))preset(e.target.closest('[data-preset]').dataset.preset);};}
function closeDays(){const d=document.getElementById('daysDialog');if(d)d.hidden=true;}
function saveDays(){const d=document.getElementById('daysDialog');if(!d)return;const s=state(),arr=s.page==='partial'?s.partial:s.full,r=arr[Number(d.dataset.index)],selected=[...d.querySelectorAll('[data-day]')].filter(x=>x.checked).map(x=>ALL_DAYS[Number(x.dataset.day)]);if(!selected.length){alert('Seleccione al menos un día trabajado.');return;}r.daysWorked={type:selected.length===7?'longshort':selected.length===5&&selected.every(x=>DAY_OPTIONS.weekdays.days.includes(x))?'weekdays':selected.length===2&&selected.every(x=>DAY_OPTIONS.weekend.days.includes(x))?'weekend':'custom',selected};closeDays();render();}
function preset(p){const d=document.getElementById('daysDialog');if(!d)return;const days=p==='weekdays'?DAY_OPTIONS.weekdays.days:p==='weekend'?DAY_OPTIONS.weekend.days:p==='longshort'?ALL_DAYS:[];d.querySelectorAll('[data-day]').forEach((x,i)=>x.checked=days.includes(ALL_DAYS[i]));}
function removeSchedule(i){saveInputs();const s=state(),arr=s.page==='partial'?s.partial:s.full;if(arr.length>1)arr.splice(i,1);else arr[0]=s.page==='partial'?emptyPartial():emptyFull();render();}
function addSchedule(){saveInputs();const s=state();(s.page==='partial'?s.partial:s.full).push(s.page==='partial'?emptyPartial():emptyFull());render();}
function bind(){document.querySelectorAll('[data-v3-page]').forEach(e=>e.onclick=()=>{saveInputs();state().page=e.dataset.v3Page;render();});document.querySelectorAll('[data-days-index]').forEach(e=>e.onclick=()=>openDaysDialog(Number(e.dataset.daysIndex)));document.querySelectorAll('[data-delete-index]').forEach(e=>e.onclick=()=>removeSchedule(Number(e.dataset.deleteIndex)));document.getElementById('addWorkerSchedule')?.addEventListener('click',addSchedule);document.querySelectorAll('[data-v3-t]').forEach(e=>e.addEventListener('change',()=>{saveInputs();renderResults();}));const d=document.getElementById('daysDialog');if(d)d.onclick=e=>{if(e.target.closest('[data-days-close]'))closeDays();if(e.target.closest('[data-days-save]'))saveDays();if(e.target.closest('[data-preset]'))preset(e.target.closest('[data-preset]').dataset.preset);};}
function render(){const s=state(),host=document.getElementById('formContainer');if(!host)return;host.innerHTML=`<div class="step-title-row"><h3>Personas trabajadoras que realizan MMP</h3></div><div class="subnav"><button type="button" class="subnav-btn ${s.page==='full'?'active':''}" data-v3-page="full">Jornada completa</button><button type="button" class="subnav-btn ${s.page==='partial'?'active':''}" data-v3-page="partial">Horario parcial</button></div><div id="workerV3Page"></div><div id="workerV3Results"></div>`;renderPage();renderResults();bind();}
function save(){saveInputs();const r=calculate();window.formData.op=r.OP;window.formData.opByShift={};window.formData.presenceByShift={};r.rows.forEach(x=>{window.formData.opByShift[x.key]=x.op;window.formData.presenceByShift[x.key]=x.totalPresent;});return r;}
window.renderWorkerScheduleV3=render;window.saveWorkerScheduleV3=save;window.WorkersScheduleV3={state,render,calculate,dayFactor,save,presenceInTurn};
})();